#pragma once

#include <array>
#include <cstdint>
#include <filesystem>
#include <string>
#include <vector>

namespace aurelion::rmg_native_core {

struct ControlledCase {
	std::string raw;
	std::string id;
	std::string size_class;
	int32_t players = 0;
	uint32_t seed = 0;
	std::string water_mode;
	int32_t level_count = 0;
	int32_t human_count = 0;
	int32_t computer_count = 0;
	bool setup_object_0x44_known = false;
	bool setup_object_0x44_supplied = false;
	int32_t setup_object_0x44 = 0;
	bool parse_ok = false;
	std::string parse_error;
};

struct SharedSourceTownRules {
	int32_t min_towns = 0;
	int32_t min_castles = 0;
	int32_t town_density = 0;
	int32_t castle_density = 0;
};

struct SharedSourceMineRules {
	int32_t minimum_wood = 0;
	int32_t minimum_mercury = 0;
	int32_t minimum_ore = 0;
	int32_t minimum_sulfur = 0;
	int32_t minimum_crystal = 0;
	int32_t minimum_gems = 0;
	int32_t minimum_gold = 0;
	int32_t density_wood = 0;
	int32_t density_mercury = 0;
	int32_t density_ore = 0;
	int32_t density_sulfur = 0;
	int32_t density_crystal = 0;
	int32_t density_gems = 0;
	int32_t density_gold = 0;
};

struct SharedSourceTreasureBand {
	int32_t density = 0;
	int32_t low = 0;
	int32_t high = 0;
};

struct SharedSourceZonePayload {
	int32_t source_row = -1;
	int32_t source_type_code = 0;
	int32_t source_ownership = -1;
	bool same_town_type = false;
	bool monster_match_to_town = false;
	int32_t monster_strength_mode = 3;
	uint16_t allowed_monster_town_mask = 0U;
	SharedSourceTownRules player_towns;
	SharedSourceTownRules neutral_towns;
	SharedSourceMineRules mines;
	SharedSourceTreasureBand treasure_band_0;
	SharedSourceTreasureBand treasure_band_1;
	SharedSourceTreasureBand treasure_band_2;
};

struct SharedSourceObjectRecord0x4c {
	int32_t source_row = -1;
	std::string source;
	std::string def_name;
	int32_t type_id_0x1c = 0;
	std::string type_name;
	int32_t metadata_bucket_index_0x08 = 0;
	int32_t subtype_0x20 = 0;
	int32_t group_0x24 = 0;
	int32_t last_flag_0x28 = 0;
	bool raw_field_0x20_known = false;
	int32_t raw_field_0x20 = 0;
	bool raw_field_0x24_known = false;
	int32_t raw_field_0x24 = 0;
	bool raw_field_0x28_known = false;
	int32_t raw_field_0x28 = 0;
	bool raw_field_0x2c_known = false;
	int32_t raw_field_0x2c = 0;
	bool raw_field_0x30_known = false;
	int32_t raw_field_0x30 = 0;
	bool raw_field_0x34_known = false;
	int32_t raw_field_0x34 = 0;
	bool raw_field_0x38_known = false;
	int32_t raw_field_0x38 = 0;
	bool raw_field_0x3c_known = false;
	int32_t raw_field_0x3c = 0;
	int32_t pass_count = 0;
	int32_t action_count = 0;
	std::string passability_mask;
	std::string action_mask;
	uint16_t terrain_mask_a_0x14 = 0U;
	uint16_t terrain_mask_b_0x18 = 0U;
	bool descriptor_mask_fields_0x34_0x48_known = false;
	bool descriptor_mask_fields_exact_def_msk = false;
	int32_t descriptor_width_0x34 = 0;
	int32_t descriptor_height_0x38 = 0;
	uint64_t descriptor_mask_a_0x3c_0x40 = 0U;
	uint64_t descriptor_mask_b_0x44_0x48 = 0U;
	std::string terrain_a_names;
	std::string terrain_b_names;
	bool rand_trn_backed = false;
};

struct SharedSourceObjectWrapperBucket0xe8 {
	int32_t bucket_index_0x08 = -1;
	int32_t first_type_id_0x1c = -1;
	std::string first_type_name;
	bool initialized_by_0x49db76 = false;
	int32_t record_count = 0;
	int32_t first_source_record_index = -1;
	int32_t last_source_record_index = -1;
	std::vector<int32_t> source_record_index_sample;
};

struct SharedSourceObjectSelectorResult4a9e40 {
	int32_t requested_lane = 0;
	int32_t requested_bucket_index_0x08 = -1;
	int32_t requested_source_field_0x20 = 0;
	bool bucket_found = false;
	int32_t scanned_record_count = 0;
	int32_t source_0x20_reject_count = 0;
	int32_t group_lane8_reject_count = 0;
	int32_t mask_reject_count = 0;
	int32_t accepted_count = 0;
	std::vector<int32_t> accepted_source_record_index_sample;
	bool selected = false;
	int32_t selected_candidate_index = -1;
	int32_t selected_source_record_index = -1;
	int32_t selected_type_id_0x1c = -1;
	int32_t selected_subtype_0x20 = 0;
	int32_t selected_group_0x24 = 0;
	std::string selected_def_name;
	uint32_t rng_state_before = 0U;
	uint32_t rng_state_after = 0U;
	bool rng_consumed = false;
	int32_t rng_value = -1;
};

struct SharedSourceObjectResolverResult4af785 {
	int32_t input_source_catalog_index = -1;
	int32_t input_source_row = -1;
	std::string input_def_name;
	int32_t input_type_id_0x1c = -1;
	int32_t input_subtype_0x20 = 0;
	int32_t metadata_bucket_index_0x08 = -1;
	int32_t resolver_lane_0x04 = 9;
	bool reused_existing_wrapper = false;
	bool created_new_wrapper = false;
	int32_t selected_wrapper_index = -1;
	int32_t scanned_bucket_wrapper_count = 0;
	int32_t lane_reject_count = 0;
	int32_t source_0x20_reject_count = 0;
	int32_t source_copy_mismatch_count = 0;
	int32_t bucket_size_before = 0;
	int32_t bucket_size_after = 0;
	int32_t source_pair_count_before = 0;
	int32_t source_pair_count_after = 0;
	bool appended_source_pair_0xedc = false;
	bool appended_wrapper_to_bucket = false;
	bool copied_source_record = false;
	bool wrapper_0x10_known = false;
	int32_t wrapper_0x10 = 0;
};

struct SharedSourceObjectResolvedWrapper4af785 {
	int32_t wrapper_index = -1;
	int32_t source_catalog_index = -1;
	SharedSourceObjectRecord0x4c source_record_copy;
	int32_t metadata_bucket_index_0x08 = -1;
	int32_t resolver_lane_0x04 = 9;
	int32_t wrapper_0x04 = -1;
	bool wrapper_0x10_known = false;
	int32_t wrapper_0x10 = 0;
	bool initialized_by_0x49db76 = false;
	bool copied_source_record = false;
};

struct SharedSourceObjectDescriptorJoinContext4903e8 {
	int32_t target_context_0x4903e8 = -1;
	int32_t source_key_0x00 = -1;
	int32_t descriptor_type_0x1c = -1;
	int32_t subtype_0x20 = 0;
	int32_t group_0x24 = 0;
	bool projection_enabled_0x29 = false;
	int32_t source_cell_x_0x2c = 0;
	int32_t source_cell_y_0x30 = 0;
	bool score_adjust_0x30_known = false;
	int32_t score_adjust_0x30 = 0;
	bool score_adjust_0x40_known = false;
	int32_t score_adjust_0x40 = 0;
	bool descriptor_mask_fields_0x34_0x48_known = false;
	int32_t descriptor_width_0x34 = 0;
	int32_t descriptor_height_0x38 = 0;
	uint64_t descriptor_mask_a_0x3c_0x40 = 0U;
	uint64_t descriptor_mask_b_0x44_0x48 = 0U;
};

struct SharedSourceObjectResolverSourcePair4af785 {
	int32_t copied_source_catalog_index = -1;
	int32_t wrapper_index = -1;
	bool source_record_pointer_0x00_carried = false;
	SharedSourceObjectRecord0x4c source_record_copy;
	int32_t source_lane_0x1c = -1;
	bool context_pointer_0x04_carried = false;
	SharedSourceObjectResolvedWrapper4af785 context_wrapper_copy;
	int32_t context_wrapper_index_0x04 = -1;
	int32_t context_wrapper_lane_0x04 = -1;
	bool context_wrapper_0x10_known = false;
	int32_t context_wrapper_0x10 = 0;
	bool descriptor_join_0x4903e8_known = false;
	SharedSourceObjectDescriptorJoinContext4903e8 descriptor_join_descriptor_0x4903e8;
	bool descriptor_joined_0x4903e8 = false;
	int32_t descriptor_join_source_pair_index_0xedc = -1;
	bool source_order_relation_context_known = false;
	int32_t source_order_relation_owner_byte2 = -1;
	bool source_order_source_pair_key_0x0c_known = false;
	int32_t source_order_source_pair_key_0x0c = -1;
	bool source_order_anchor_known = false;
	int32_t source_order_anchor_x_0x10 = 0;
	int32_t source_order_anchor_y_0x14 = 0;
	int32_t source_order_anchor_level_0x18 = 0;
	bool source_order_lane_state_0xee4_known = false;
	int32_t source_order_lane_state_0xee4 = -1;
};

struct SharedRuntimeZoneSeedInput {
	int32_t runtime_zone_index = -1;
	int32_t source_zone_id = -1;
	int32_t source_index = -1;
	int32_t h3maped_zone_word_id = -1;
	int32_t source_bucket = -1;
	int32_t source_owner_index = -1;
	int32_t actual_player_color = -1;
	int32_t source_base_size = 0;
	uint16_t allowed_town_mask_0x41_0x49 = 0U;
	int32_t selected_town_choice_index_0x49b3c1 = -1;
	bool terrain_match_to_town_0x84 = false;
	uint16_t allowed_terrain_mask_0x85_0x8c = 0U;
	SharedSourceZonePayload source_payload;
};

struct SharedRuntimeLinkInput {
	int32_t from_index = -1;
	int32_t to_index = -1;
	int32_t guard_value = 0;
	bool wide = false;
	bool border_guard = false;
	int32_t source_zone_a = -1;
	int32_t source_zone_b = -1;
	int32_t source_endpoint_a = -1;
	int32_t source_endpoint_b = -1;
};

struct SharedPlayerSlotAssignmentRecord {
	int32_t source_owner_index = -1;
	int32_t actual_player_color = -1;
	bool human = false;
};

struct SharedTemplateCandidateContainerRecord {
	int32_t vector_index = -1;
	int32_t source_catalog_index = -1;
	std::string template_name;
	int32_t zone_count = 0;
	int32_t link_count = 0;
};

struct SharedRuntimeChainInput {
	std::string input_source;
	bool recovered_template_selection_known = false;
	bool recovered_template_selection_blocked = false;
	bool recovered_setup_mode_known = false;
	bool recovered_setup_mode_randomized_sentinel_3 = false;
	int32_t recovered_setup_object_0x44 = 0;
	int32_t recovered_setup_rng_value = -1;
	int32_t recovered_setup_rng_call_count = 0;
	uint32_t recovered_setup_rng_state_before = 0;
	uint32_t recovered_template_rng_state_before = 0;
	int32_t recovered_generator_mode_0x10b8 = 0;
	int32_t recovered_template_size_score = 0;
	int32_t recovered_template_accepted_count = 0;
	int32_t recovered_template_selected_vector_index = -1;
	int32_t recovered_template_source_catalog_index = -1;
	std::string recovered_template_name;
	std::vector<SharedTemplateCandidateContainerRecord> recovered_candidate_containers_10d4_10d8;
	int32_t recovered_template_rng_value = -1;
	int32_t recovered_template_source_zone_record_count = 0;
	int32_t recovered_template_source_link_record_count = 0;
	bool recovered_template_player_assignment_complete = false;
	int32_t recovered_template_runtime_zone_seed_count = 0;
	int32_t recovered_template_runtime_link_count = 0;
	int32_t recovered_template_skipped_zone_filter_count = 0;
	int32_t recovered_template_skipped_link_filter_count = 0;
	int32_t recovered_template_missing_link_endpoint_count = 0;
	bool recovered_player_slot_assignment_known = false;
	int32_t recovered_player_slot_requested_human_count = 0;
	int32_t recovered_player_slot_requested_player_count = 0;
	int32_t recovered_player_slot_assigned_player_count = 0;
	std::vector<int32_t> recovered_selected_color_order_ed8;
	std::vector<int32_t> recovered_raw_source_owner_slots_ee0;
	std::vector<int32_t> recovered_mapped_source_owner_slots_ee4;
	std::vector<SharedPlayerSlotAssignmentRecord> recovered_player_slot_assignments;
	bool rng_state_after_template_selection_known = false;
	uint32_t rng_state_after_template_selection = 0;
	bool generator_mode_0x10b8_known = false;
	int32_t generator_mode_0x10b8 = 0;
	std::vector<SharedRuntimeZoneSeedInput> runtime_zone_seeds;
	std::vector<SharedRuntimeLinkInput> runtime_links;
};

struct CaseReport {
	ControlledCase input;
	std::string status;
	std::string blocked_reason;
	bool supported_scope = false;
	bool shared_chain_executed = false;
	std::string shared_chain_input_status;
	bool native_workflow_executed = false;
	bool native_workflow_final_writeout_complete = false;
	std::string native_workflow_status;
	std::string native_workflow_current_phase;
	bool phase_snapshot_written = false;
	std::filesystem::path phase_snapshot_path;
	bool native_map_json_written = false;
	std::filesystem::path native_map_json_path;
};

struct TerrainVisualMissingBucketSample {
	int32_t level = 0;
	int32_t x = 0;
	int32_t y = 0;
	int32_t terrain_id = 0;
	int32_t shape_class = 0;
	int32_t flag_a = 0;
	int32_t flag_b = 0;
	int32_t neighbor_mask = 0;
	int32_t row_table_count = 0;
	bool final_sweep = false;
};

struct SharedGeneratedCellRecord0x30 {
	int32_t flat = -1;
	int32_t x = -1;
	int32_t y = -1;
	int32_t level = -1;
	int32_t stride_bytes = 0x30;
	bool object_reference_vector_fields_0x04_0x08_present = true;
	bool object_reference_vector_contents_known = false;
	int32_t object_reference_count = 0;
	std::vector<uint32_t> object_references_0x04_0x08;
	bool word_0x10_known = false;
	uint32_t word_0x10 = 0U;
	bool word_0x14_known = false;
	uint32_t word_0x14 = 0U;
	bool word_0x18_known = false;
	uint32_t word_0x18 = 0U;
	bool word_0x1c_known = false;
	uint32_t word_0x1c = 0U;
	bool word_0x20_known = false;
	uint32_t word_0x20 = 0U;
	bool word_0x24_known = false;
	uint32_t word_0x24 = 0U;
	bool word_0x28_known = false;
	uint32_t word_0x28 = 0U;
	bool byte_0x2b_known = false;
	uint8_t byte_0x2b_known_mask = 0U;
	uint8_t byte_0x2b = 0U;
	bool word_0x2c_known = false;
	uint32_t word_0x2c = 0U;
};

struct SharedGeneratorObjectVectorState {
	std::string label;
	uint32_t begin_offset = 0U;
	uint32_t end_offset = 0U;
	uint32_t capacity_offset = 0U;
	bool present = false;
	bool contents_known = false;
	bool count_known = false;
	int32_t count = 0;
	bool count_sourced_from_vector = false;
	std::string count_source_vector_label;
	bool zero_initialized_contents_known_when_count_known = false;
	int32_t element_size_bytes = 0;
};

struct SharedGeneratorRelationRecordState {
	int32_t source_link_index = -1;
	int32_t owner_runtime_zone_index = -1;
	int32_t owner_source_zone_id = -1;
	int32_t target_runtime_zone_index = -1;
	int32_t target_source_zone_id = -1;
	int32_t guard_value = 0;
	bool wide = false;
	bool border_guard = false;
	bool reciprocal = false;
	uint32_t control_dword_0x08 = 0U;
};

struct SharedGeneratorSourceEndpointRecordState {
	int32_t source_link_index = -1;
	int32_t owner_runtime_zone_index = -1;
	int32_t owner_source_zone_id = -1;
	int32_t target_runtime_zone_index = -1;
	int32_t target_source_zone_id = -1;
	int32_t source_endpoint = -1;
	int32_t target_source_endpoint = -1;
	int32_t guard_value = 0;
	bool wide = false;
	bool border_guard = false;
	bool reciprocal = false;
};

struct SharedCoordinateCandidate4a17f5 {
	int32_t x = 0;
	int32_t y = 0;
	int32_t level = 0;
};

struct SharedGeneratorCoordinateCandidateVectorState4a1f3b {
	int32_t runtime_zone_index = -1;
	std::string pass_id;
	std::string candidate_source;
	int32_t candidate_count_before_prune = 0;
	int32_t candidate_count_after_prune = 0;
	int32_t explicit_link_base_count = 0;
	int32_t selected_candidate_index = -1;
	int32_t rng_value = -1;
	bool blocked = false;
	bool selected_candidate_known = false;
	SharedCoordinateCandidate4a17f5 selected_candidate;
	std::vector<SharedCoordinateCandidate4a17f5> candidates_before_prune_4a17f5;
	std::vector<SharedCoordinateCandidate4a17f5> candidates_after_prune_4a1ad8;
};

struct SharedGeneratorRelationOwnerState {
	int32_t owner_vector_index = -1;
	int32_t runtime_zone_index = -1;
	int32_t source_zone_id = -1;
	int32_t source_index = -1;
	bool constructor_0x49b452_known = false;
	bool source_pointer_0x00_known = false;
	int32_t source_pointer_source_index_0x00 = -1;
	bool relation_owner_byte2_0x4aa9b7_known = false;
	int32_t relation_owner_byte2_0x4aa9b7 = -1;
	bool source_pointer_type_0x04_known = false;
	int32_t source_pointer_type_0x04 = 0;
	bool town_choice_0x04_known = false;
	int32_t town_choice_0x04 = -1;
	bool source_owner_slot_0x1c_known = false;
	int32_t source_owner_slot_0x1c = -1;
	bool coordinate_triple_0x10_0x18_known = false;
	int32_t coordinate_x_0x10 = 0;
	int32_t coordinate_y_0x14 = 0;
	int32_t coordinate_level_0x18 = 0;
	bool terrain_policy_0x0c_known = false;
	int32_t terrain_policy_0x0c = 0;
	bool reward_guard_source_bands_0xa0_0xc0_known = false;
	std::array<SharedSourceTreasureBand, 3> reward_guard_source_bands_0xa0_0xc0;
	bool source_endpoint_vector_0xc8_0xcc_present = false;
	bool source_endpoint_vector_0xc8_0xcc_contents_known = false;
	bool source_endpoint_vector_0xc8_0xcc_count_known = false;
	int32_t source_endpoint_vector_0xc8_0xcc_count = 0;
	int32_t source_endpoint_vector_0xc8_0xcc_stride_bytes = 0x1c;
	bool scan_bounds_0x20_0x2c_known = false;
	int32_t scan_bound_low_x_0x20 = 0x7d00;
	int32_t scan_bound_low_y_0x24 = 0x7d00;
	int32_t scan_bound_high_x_0x28 = -32000;
	int32_t scan_bound_high_y_0x2c = -32000;
	bool byte_0x3c_known = false;
	uint8_t byte_0x3c = 0U;
	bool reward_guard_priority_0x40_known = false;
	int32_t reward_guard_priority_0x40 = 0;
	int32_t reward_guard_priority_before_randomization_0x4ad7f7 = 0;
	int32_t reward_guard_priority_rng_value_0x4e7276 = -1;
	bool reward_guard_priority_source_relation_0x4ad6a8 = false;
	bool descriptor_type_counter_table_0x44_known = false;
	int32_t descriptor_type_counter_table_0x44_byte_size = 0x3a0;
	int32_t descriptor_type_counter_table_0x44_zero_count = 0x3a0 / 4;
	std::vector<uint32_t> descriptor_type_counters_0x44;
	bool owner_local_vectors_0x3e4_0x3f4_0x404_known = false;
	int32_t owner_local_vector_0x3e4_count = 0;
	int32_t owner_local_vector_0x3f4_count = 0;
	int32_t owner_local_vector_0x404_count = 0;
	bool coordinate_candidate_vectors_0x4a1f3b_known = false;
	int32_t coordinate_candidate_vector_step_count = 0;
	int32_t coordinate_candidate_after_prune_total_count = 0;
	int32_t relation_record_count = 0;
	std::vector<SharedGeneratorSourceEndpointRecordState> source_endpoint_records_0xc8_0xcc;
	std::vector<SharedGeneratorCoordinateCandidateVectorState4a1f3b> coordinate_candidate_vectors_0x4a1f3b;
	std::vector<SharedGeneratorRelationRecordState> relation_records;
};

struct SharedObjectRecordReference4a54a7 {
	uint32_t object_record_key = 0U;
	int32_t descriptor_type_0x1c = -1;
	int32_t x = 0;
	int32_t y = 0;
	int32_t level = 0;
	bool connection_fallback_record_0x4a7605_0x4a5e03_known = false;
	uint32_t connection_fallback_arg0_0x4a5e03 = 0U;
	uint32_t connection_fallback_descriptor_pointer = 0U;
	int32_t connection_fallback_expected_owner_byte2 = -1;
	bool object_record_key_allocated_by_0x4a93a2 = false;
	bool source_order_direct_record_0x4a8d2c_0x4a93a2_known = false;
	bool weighted_record_0x4a93a2_known = false;
	uint32_t object_record_vtable_0x00 = 0U;
	int32_t object_record_sequence_0x1c = -1;
	int32_t object_record_selected_index_0x20 = -1;
	uint32_t object_record_enabled_word_0x24 = 0U;
	bool object_record_enabled_low_byte_0x24 = false;
	bool source_descriptor_join_0x4903e8_known = false;
	bool weighted_type98_descriptor_bridge_0x4a93a2_known = false;
	int32_t descriptor_source_key_0x00 = -1;
	int32_t selected_wrapper_index_0x4af785 = -1;
	int32_t source_catalog_index_0x49da08 = -1;
	bool copied_source_record_carried = false;
	SharedSourceObjectRecord0x4c source_record_copy;
};

struct SharedGeneratorEndpointCursorProducerStateD014 {
	bool recovered_supported_land_exclusion_known = false;
	bool supported_land_endpoint_cursor_key_range_known = false;
	int32_t supported_land_endpoint_cursor_key_count = 0;
	bool supported_land_observed_stale_cursor_0xf5c_known = false;
	uint32_t supported_land_observed_stale_cursor_0xf5c = 0U;
	bool setup_zeroed_cursor_0xf58_0x49ecf2_known = false;
	bool endpoint_byte_state_zero_init_from_d8_count_0x49f95a_known = false;
	bool direct_cursor_writer_surface_bounded = false;
	bool setup_seeds_cursor_0xf5c = false;
	bool successful_cursor_0xf5c_seed_source_known = false;
	bool supported_land_success_path_reached = false;
	bool supported_land_live_0x4a606b_reached = false;
	bool supported_land_live_0x4a696b_relation_match_reached = false;
	int32_t direct_cursor_writer_entry_count = 0;
	std::vector<std::string> direct_cursor_writer_entries;
	std::string missing_cursor_seed_source;
};

struct SharedConnectionMaterializationCallerPrepD014 {
	bool recovered_helper_contract_0x4a5e73_known = false;
	bool recovered_explicit_input_0x4a606b_known = false;
	bool recovered_no_object_projection_chain_0x4a5a23_known = false;
	bool live_0x4a5e73_to_0x4a606b_target_mode_excluded = false;
	bool live_0x4a696b_target_mode_excluded = false;
	bool fallback_0x4a7605_to_0x4a5e03_source_backed = false;
	bool live_endpoint_materialization_allowed = false;
	std::string remaining_live_materialization_blocker;
};

struct SharedWeightedSchedulerThreshold4a8db2 {
	bool source_density_fields_known = false;
	int32_t player_castle_density_0x2c = 0;
	int32_t player_town_density_0x28 = 0;
	int32_t neutral_castle_density_0x3c = 0;
	int32_t neutral_town_density_0x38 = 0;
	int32_t positive_density_sum = 0;
	bool threshold_arg_0x18_known = false;
	int32_t threshold_arg_0x18 = 0;
	std::string blocked_reason;
};

struct SharedSourceOrderSchedulerLane4a8db2 {
	int32_t lane_index = -1;
	uint32_t direct_callsite = 0U;
	uint32_t weighted_callsite = 0U;
	int32_t count_field_offset = 0;
	bool count_field_known = false;
	int32_t count_field_value = 0;
	int32_t density_field_offset = 0;
	bool density_field_known = false;
	int32_t density_field_value = 0;
	bool use_lane_state_0xee4 = false;
	int32_t selected_index_0x20 = -1;
	bool enabled_low_byte_0x24 = false;
	bool initially_disabled = true;
	bool disabled_after_replay = true;
	int64_t scheduler_increment = 0;
	int64_t scheduler_score = 0;
	int32_t direct_prepass_call_count = 0;
	int32_t weighted_call_count = 0;
	int32_t committed_call_count = 0;
	std::string blocked_reason;
};

struct SharedSourceOrderSchedulerCall4a8db2 {
	std::string phase;
	uint32_t callsite = 0U;
	int32_t lane_index = -1;
	int32_t loop_index = -1;
	int32_t selected_index_0x20 = -1;
	bool enabled_low_byte_0x24 = false;
	int32_t threshold_arg_0x18 = 0;
	int64_t scheduler_score_before = 0;
	int64_t scheduler_increment = 0;
	int64_t scheduler_score_after = 0;
	bool attempted_0x4a901a = false;
	bool returned_nonzero = false;
	bool committed = false;
	bool disabled_after_false = false;
	int32_t weighted_candidate_vector_index_0x4a901a = -1;
	int32_t weighted_candidate_accepted_count_0x4a901a = 0;
	std::string blocked_reason;
};

struct SharedSourceOrderSchedulerResult4a8db2 {
	bool source_pair_pointer_carried = false;
	int32_t source_pair_copied_source_catalog_index = -1;
	int32_t source_record_id_0x00 = -1;
	int32_t source_record_owner_or_type_0x04 = -1;
	int32_t source_record_relation_selector_0x1c = -1;
	bool context_pointer_carried = false;
	int32_t context_wrapper_index_0x04 = -1;
	int32_t lane_state_0xee4 = -1;
	bool descriptor_source_bridge_known = false;
	bool scan_bounds_known = false;
	bool scan_bounds_non_empty = false;
	bool relation_owner_byte_known = false;
	int32_t relation_owner_byte2 = -1;
	int32_t scan_bound_low_x = 0;
	int32_t scan_bound_low_y = 0;
	int32_t scan_bound_high_x = 0;
	int32_t scan_bound_high_y = 0;
	int32_t level = 0;
	int32_t positive_density_sum = 0;
	int64_t positive_density_product = 1;
	bool threshold_arg_0x18_known = false;
	int32_t threshold_arg_0x18 = 0;
	int32_t direct_prepass_call_count = 0;
	int32_t weighted_call_count = 0;
	int32_t committed_call_count = 0;
	int32_t disabled_lane_count = 0;
	std::vector<SharedSourceOrderSchedulerLane4a8db2> lanes;
	std::vector<SharedSourceOrderSchedulerCall4a8db2> calls;
	bool replay_finished = false;
	std::string blocked_reason;
};

struct SharedWeightedObjectCandidate4a901a {
	int32_t x = 0;
	int32_t y = 0;
	int32_t level = 0;
	uint32_t low_word_score_0x20 = 0U;
};

struct SharedWeightedObjectCandidateVectorState4a901a {
	bool descriptor_source_bridge_known = false;
	bool copied_source_record_carried = false;
	bool scan_bounds_known = false;
	bool scan_bounds_non_empty = false;
	bool relation_owner_byte_known = false;
	bool threshold_arg_0x18_known = false;
	int32_t relation_owner_byte2 = -1;
	int32_t scan_bound_low_x = 0;
	int32_t scan_bound_low_y = 0;
	int32_t scan_bound_high_x = 0;
	int32_t scan_bound_high_y = 0;
	int32_t level = 0;
	int32_t threshold_arg_0x18_initial = 0;
	int32_t threshold_arg_0x18_after_scan = 0;
	int32_t scanned_cell_count = 0;
	int32_t out_of_bounds_cell_count = 0;
	int32_t unknown_cell_word_count = 0;
	int32_t owner_byte_reject_count = 0;
	int32_t value_floor_reject_count = 0;
	int32_t eligibility_reject_count_0x49aa93 = 0;
	int32_t local_vector_clear_count_0x4ae52a = 0;
	int32_t local_vector_append_count_0x4ae1fd = 0;
	int32_t accepted_candidate_count = 0;
	int32_t rng_value_0x4e7276 = -1;
	int32_t selected_candidate_index = -1;
	bool selected_candidate_known = false;
	SharedWeightedObjectCandidate4a901a selected_candidate;
	std::vector<SharedWeightedObjectCandidate4a901a> accepted_candidates_0x4ae1fd;
	bool allocated_record_0x4a93a2 = false;
	bool committed_through_0x4a54a7 = false;
	uint32_t object_record_key = 0U;
	bool object_record_key_known = false;
	int32_t object_vector_count_after = 0;
	std::string blocked_reason;
};

struct SharedGeneratorObjectPrivateState {
	bool present = false;
	uint32_t generated_cell_buffer_offset_0x14 = 0x14U;
	uint32_t width_offset_0x18 = 0x18U;
	uint32_t height_offset_0x1c = 0x1cU;
	uint32_t level_count_offset_0x20 = 0x20U;
	bool generated_cell_buffer_owned = false;
	int32_t generated_cell_buffer_record_count = 0;
	int32_t width = 0;
	int32_t height = 0;
	int32_t level_count = 0;
	SharedGeneratorObjectVectorState endpoint_vector_c8_cc;
	SharedGeneratorObjectVectorState endpoint_vector_d8_dc;
	SharedGeneratorObjectVectorState mine_resource_descriptor_vector_388_38c;
	SharedGeneratorObjectVectorState object_record_vector_ec4_ecc;
	SharedGeneratorObjectVectorState source_pair_vector_edc;
	std::vector<SharedSourceObjectResolverSourcePair4af785> source_pair_records_edc;
	SharedGeneratorObjectVectorState pending_entry_vector_eec_ef0_ef4;
	SharedGeneratorObjectVectorState candidate_container_vector_10d4_10d8;
	std::vector<SharedTemplateCandidateContainerRecord> candidate_container_records_10d4_10d8;
	bool selected_candidate_container_0x4ac552_known = false;
	SharedTemplateCandidateContainerRecord selected_candidate_container_0x4ac552;
	SharedGeneratorObjectVectorState relation_vector_10e4_10e8;
	bool relation_owner_vector_produced_by_0x4ac552_0x4a218c = false;
	bool relation_owner_vector_selected_candidate_input_known = false;
	std::string relation_owner_vector_producer_blocked_reason;
	int32_t relation_owner_vector_selected_candidate_source_catalog_index = -1;
	std::string relation_owner_vector_selected_candidate_template_name;
	int32_t relation_owner_vector_selected_candidate_source_zone_count = 0;
	int32_t relation_owner_vector_selected_candidate_source_link_count = 0;
	SharedGeneratorObjectVectorState reward_guard_candidate_vector_10f4_10f8;
	SharedGeneratorObjectVectorState endpoint_byte_state_vector_1104_1108;
	bool endpoint_cursor_0xf58_present = false;
	bool endpoint_cursor_0xf58_known = false;
	int32_t endpoint_cursor_0xf58 = 0;
	bool endpoint_cursor_0xf5c_present = false;
	bool endpoint_cursor_0xf5c_known = false;
	int32_t endpoint_cursor_0xf5c = 0;
	bool endpoint_projection_vector_c8_cc_source_owned_0x4a1f3b = false;
	int32_t endpoint_projection_vector_c8_cc_record_count = 0;
	std::vector<SharedGeneratorSourceEndpointRecordState> endpoint_projection_records_c8_cc;
	bool endpoint_cursor_vector_d8_dc_source_owned = false;
	bool endpoint_cursor_vector_d8_dc_supported_land_exclusion_known = false;
	SharedGeneratorEndpointCursorProducerStateD014 endpoint_cursor_producer_d014;
	SharedConnectionMaterializationCallerPrepD014 connection_materialization_caller_prep_d014;
	bool connection_fallback_materialization_0x4a7605_0x4a5e03_known = false;
	bool connection_fallback_materialization_scope_known = false;
	std::string connection_fallback_materialization_scope_size_class;
	std::string connection_fallback_materialization_scope_water_mode;
	int32_t connection_fallback_materialization_scope_width = 0;
	int32_t connection_fallback_materialization_scope_height = 0;
	int32_t connection_fallback_materialization_scope_level_count = 0;
	uint32_t connection_fallback_materialization_scope_seed = 0U;
	bool connection_fallback_materialization_records_available_for_scope = false;
	int32_t connection_fallback_materialization_record_count = 0;
	int32_t connection_fallback_materialization_commit_count = 0;
	int32_t connection_fallback_materialization_blocked_count = 0;
	int32_t connection_fallback_materialization_first_blocked_record_index = -1;
	std::string connection_fallback_materialization_first_blocked_reason;
	bool descriptor_counter_table_0x1110_present = false;
	bool descriptor_counter_table_0x1110_contents_known = false;
	int32_t descriptor_counter_table_0x1110_known_count = 0;
	int32_t descriptor_counter_table_0x1110_zero_count = 0;
	bool object_record_sequence_allocator_0xf44_present = false;
	bool object_record_sequence_allocator_0xf44_known = false;
	int32_t object_record_sequence_allocator_0xf44 = 1;
	bool native_object_record_key_allocator_0x4a93a2_known = false;
	uint32_t next_native_object_record_key_0x4a93a2 = 1U;
	int32_t object_record_allocation_count_0x4a93a2 = 0;
	bool weighted_scheduler_thresholds_0x4a8db2_known = false;
	int32_t weighted_scheduler_threshold_count_0x4a8db2 = 0;
	std::vector<SharedWeightedSchedulerThreshold4a8db2> weighted_scheduler_thresholds_0x4a8db2;
	bool source_order_scheduler_replay_0x4a8db2_known = false;
	int32_t source_order_scheduler_replay_count_0x4a8db2 = 0;
	int32_t source_order_scheduler_direct_call_count_0x4a8db2 = 0;
	int32_t source_order_scheduler_weighted_call_count_0x4a8db2 = 0;
	int32_t source_order_scheduler_commit_count_0x4a8db2 = 0;
	int32_t source_order_scheduler_blocked_count_0x4a8db2 = 0;
	std::vector<SharedSourceOrderSchedulerResult4a8db2> source_order_scheduler_replays_0x4a8db2;
	bool generic_source_order_pair_replay_applied_0x4a8d2c_0x4a8db2 = false;
	int32_t generic_source_order_pair_scan_count_0xedc = 0;
	int32_t generic_source_order_pair_type98_skip_count = 0;
	int32_t generic_source_order_pair_descriptor_context_missing_count = 0;
	int32_t generic_source_order_pair_relation_context_missing_count = 0;
	int32_t generic_source_order_pair_source_fields_missing_count = 0;
	int32_t generic_source_order_pair_direct_dispatch_count_0x4a8d2c = 0;
	int32_t generic_source_order_pair_direct_commit_count_0x4a8d2c = 0;
	int32_t generic_source_order_pair_weighted_replay_count_0x4a8db2 = 0;
	int32_t generic_source_order_pair_weighted_commit_count_0x4a8db2 = 0;
	std::vector<std::string> generic_source_order_pair_replay_blockers_0xedc;
	bool materialization_bridge_post_4a4c8e_cleanup_0x4a8c15_ported = false;
	bool materialization_bridge_post_4a4c8e_cleanup_0x4a8c15_input_known = false;
	bool materialization_bridge_post_4a4c8e_cleanup_0x4a8c15_applied = false;
	int32_t materialization_bridge_post_4a4c8e_cleanup_scan_count_0x4a8c15 = 0;
	int32_t materialization_bridge_post_4a4c8e_cleanup_call_count_0x49a962 = 0;
	bool materialization_bridge_relation_loop_0x4a4913_ported = false;
	bool materialization_bridge_relation_loop_0x4a4913_input_known = false;
	bool materialization_bridge_relation_loop_0x4a4913_applied = false;
	int32_t materialization_bridge_relation_loop_relation_count_0x4a4913 = 0;
	int32_t materialization_bridge_relation_loop_call_count_0x4a4913 = 0;
	int32_t materialization_bridge_relation_loop_non_type8_skip_count_0x4a4913 = 0;
	int32_t materialization_bridge_relation_loop_reset_cell_count_0x4a4913 = 0;
	int32_t materialization_bridge_relation_loop_foreign_seed_call_count_0x4a4694 = 0;
	int32_t materialization_bridge_relation_loop_candidate_scan_count_0x4a4913 = 0;
	int32_t materialization_bridge_relation_loop_candidate_append_count_0x4ae1fd = 0;
	int32_t materialization_bridge_relation_loop_rng_call_count_0x4e7276 = 0;
	int32_t materialization_bridge_relation_loop_brush_call_count_0x4a4522 = 0;
	int32_t materialization_bridge_relation_loop_selected_seed_call_count_0x4a4694 = 0;
	int32_t materialization_bridge_relation_loop_queue_relax_count_0x4a4694 = 0;
	int32_t materialization_bridge_relation_loop_brush_bit26_set_count_0x4a4522 = 0;
	bool materialization_bridge_water_edge_writer_0x4a4fc5_ported = false;
	bool materialization_bridge_water_edge_writer_0x4a4fc5_input_known = false;
	bool materialization_bridge_water_edge_writer_0x4a4fc5_applied = false;
	bool materialization_bridge_water_edge_writer_0x4a4fc5_source_backed_land_scope = false;
	int32_t materialization_bridge_water_edge_writer_scan_count_0x4a4fc5 = 0;
	int32_t materialization_bridge_water_edge_writer_owner_low_sentinel_skip_count_0x4a4fc5 = 0;
	int32_t materialization_bridge_water_edge_writer_owner_high_sentinel_skip_count_0x4a4fc5 = 0;
	int32_t materialization_bridge_water_edge_writer_source_water_cell_count_0x4a4fc5 = 0;
	int32_t materialization_bridge_water_edge_writer_relation_lookup_skip_count_0x4a4fc5 = 0;
	int32_t materialization_bridge_water_edge_writer_mutation_source_count_0x4a4fc5 = 0;
	int32_t materialization_bridge_water_edge_writer_bit26_set_count_0x4a4fc5 = 0;
	int32_t materialization_bridge_water_edge_writer_byte2b_clear_count_0x4a4fc5 = 0;
	int32_t materialization_bridge_water_edge_writer_visual_repaint_pending_count_0x4a4fc5 = 0;
	int32_t materialization_bridge_water_edge_writer_neighbor_bit25_probe_count_0x4a4fc5 = 0;
	int32_t materialization_bridge_water_edge_writer_bit26_candidate_count_0x4a4fc5 = 0;
	std::string materialization_bridge_water_edge_writer_blocked_reason_0x4a4fc5;
	bool decorative_flagged_cell_dispatch_0x49eb8d_ported = false;
	bool decorative_flagged_cell_dispatch_0x49eb8d_invoked = false;
	bool decorative_flagged_cell_dispatch_0x49eb8d_applied = false;
	int32_t decorative_flagged_cell_dispatch_bit26_candidate_count = 0;
	int32_t decorative_flagged_cell_dispatch_valid_0x49e700_candidate_count = 0;
	int32_t decorative_flagged_cell_dispatch_invalid_optional_handler_candidate_count = 0;
	bool decorative_dispatch_probe_0x49e700_invoked = false;
	bool decorative_dispatch_type_table_0x54092c_known = false;
	int32_t decorative_dispatch_type_table_0x54092c_count = 0;
	int32_t decorative_dispatch_probe_invocation_count_0x49e700 = 0;
	int32_t decorative_dispatch_probe_source_record_scan_count_0x49e700 = 0;
	int32_t decorative_dispatch_probe_rand_trn_record_count_0x49e700 = 0;
	int32_t decorative_dispatch_probe_rand_trn_score_variant_count_0x49e700 = 0;
	int32_t decorative_dispatch_probe_rand_trn_terrain_score_lookup_count_0x49e700 = 0;
	int32_t decorative_dispatch_probe_rand_trn_terrain_hard_reject_count_0x49e700 = 0;
	int32_t decorative_dispatch_probe_descriptor_footprint_probe_count_0x49e700 = 0;
	int32_t decorative_dispatch_probe_scorer_input_candidate_count_0x49e700 = 0;
	int32_t decorative_dispatch_scorer_first_pass_invocation_count_0x49e1bf = 0;
	int32_t decorative_dispatch_scorer_first_pass_candidate_anchor_count_0x49e1bf = 0;
	int32_t decorative_dispatch_scorer_first_pass_footprint_cell_scan_count_0x49e1bf = 0;
	int32_t decorative_dispatch_scorer_first_pass_terrain_test_count_0x42cc99 = 0;
	int32_t decorative_dispatch_scorer_first_pass_terrain_reject_count_0x42cc99 = 0;
	int32_t decorative_dispatch_scorer_first_pass_bit27_hard_reject_count_0x49e1bf = 0;
	int32_t decorative_dispatch_scorer_first_pass_bounds_reject_count_0x49e1bf = 0;
	int32_t decorative_dispatch_scorer_first_pass_missing_word_reject_count_0x49e1bf = 0;
	int32_t decorative_dispatch_scorer_first_pass_low_score_reject_count_0x49e1bf = 0;
	int32_t decorative_dispatch_scorer_first_pass_positive_count_0x49e1bf = 0;
	bool decorative_dispatch_scorer_input_0x49e1bf_unowned = false;
	bool decorative_dispatch_scorer_neighbor_pass_0x49e1bf_invoked = false;
	int32_t decorative_dispatch_scorer_neighbor_pass_invocation_count_0x49e1bf = 0;
	int32_t decorative_dispatch_scorer_neighbor_pass_cell_scan_count_0x49e1bf = 0;
	int32_t decorative_dispatch_scorer_neighbor_pass_scratch_empty_skip_count_0x49e1bf = 0;
	int32_t decorative_dispatch_scorer_neighbor_pass_bounds_skip_count_0x49e1bf = 0;
	int32_t decorative_dispatch_scorer_neighbor_pass_valid_terrain_skip_count_0x49e1bf = 0;
	int32_t decorative_dispatch_scorer_neighbor_pass_object_reference_vector_missing_count_0x49e1bf = 0;
	int32_t decorative_dispatch_scorer_neighbor_pass_object_reference_scan_count_0x49e1bf = 0;
	int32_t decorative_dispatch_scorer_neighbor_pass_object_record_lookup_missing_count_0x49e1bf = 0;
	int32_t decorative_dispatch_scorer_neighbor_pass_flagged_reference_append_count_0x40bb26 = 0;
	int32_t decorative_dispatch_scorer_neighbor_pass_score_index_missing_count_0x49b89c = 0;
	int32_t decorative_dispatch_scorer_neighbor_pass_hard_reject_count_0x49e1bf = 0;
	int32_t decorative_dispatch_scorer_neighbor_pass_positive_count_0x49e1bf = 0;
	int32_t decorative_dispatch_first_scorer_neighbor_reference_key_0x49e1bf = -1;
	int32_t decorative_dispatch_first_scorer_source_row_0x49e700 = -1;
	int32_t decorative_dispatch_first_scorer_source_type_0x49e700 = -1;
	std::string decorative_dispatch_first_scorer_source_def_name_0x49e700;
	int32_t decorative_dispatch_first_scorer_rand_trn_obstacle_id_0x49e700 = -1;
	std::string decorative_dispatch_first_scorer_rand_trn_obstacle_name_0x49e700;
	int32_t decorative_dispatch_first_scorer_rand_trn_terrain_score_0x49e700 = 0;
	int32_t decorative_dispatch_first_scorer_candidate_x_0x49e700 = -1;
	int32_t decorative_dispatch_first_scorer_candidate_y_0x49e700 = -1;
	int32_t decorative_dispatch_first_scorer_candidate_level_0x49e700 = -1;
	int32_t decorative_dispatch_first_scorer_first_pass_score_0x49e1bf = 0;
	int32_t decorative_dispatch_candidate_append_count_0x49e904 = 0;
	int32_t decorative_dispatch_candidate_weight_append_count_0x49e91f = 0;
	int32_t decorative_dispatch_candidate_weight_total_0x49e700 = 0;
	bool decorative_dispatch_rng_selection_0x49e9ad_invoked = false;
	int32_t decorative_dispatch_rng_value_0x49e9ad = -1;
	int32_t decorative_dispatch_selected_candidate_index_0x49e9ad = -1;
	int32_t decorative_dispatch_selected_candidate_score_0x49e9ad = 0;
	int32_t decorative_dispatch_selected_candidate_source_row_0x49e9ad = -1;
	std::string decorative_dispatch_selected_candidate_def_name_0x49e9ad;
	int32_t decorative_dispatch_selected_object_allocated_0x5044b1_count = 0;
	int32_t decorative_dispatch_selected_object_initialized_0x49ba89_count = 0;
	int32_t decorative_dispatch_selected_object_commit_callback_count_0x49ea25 = 0;
	int32_t decorative_dispatch_post_commit_coordinate_append_count_0x49eb01 = 0;
	int32_t decorative_dispatch_post_commit_bit26_clear_count_0x49eaf1 = 0;
	bool decorative_dispatch_coordinate_worklist_replay_pending_after_first_commit = false;
	std::string decorative_flagged_cell_dispatch_blocked_reason_0x49eb8d;
	bool connection_tail_replay_0x4a79a3_ported = false;
	bool connection_tail_replay_0x4a79a3_invoked = false;
	bool connection_tail_replay_0x4a79a3_applied = false;
	bool connection_tail_replay_generated_cell_grid_owned_0x4a79a3 = false;
	bool connection_tail_replay_endpoint_caller_prep_known_0x4a79a3 = false;
	bool connection_tail_replay_fallback_materialization_known_0x4a79a3 = false;
	bool connection_tail_replay_fallback_materialization_applied_0x4a79a3 = false;
	bool connection_tail_replay_source_backed_frontier_known_0x4a79a3 = false;
	int32_t connection_tail_replay_source_frontier_scan_cell_count_0x4a79a3 = 0;
	int32_t connection_tail_replay_source_frontier_high_owner_candidate_count_0x4a79a3 = 0;
	int32_t connection_tail_replay_source_frontier_terrain8_skip_count_0x4a79a3 = 0;
	int32_t connection_tail_replay_source_frontier_terrain9_skip_count_0x4a79a3 = 0;
	int32_t connection_tail_replay_source_frontier_bit25_skip_count_0x4a79a3 = 0;
	int32_t connection_tail_replay_source_frontier_neighbor_probe_count_0x4a79a3 = 0;
	int32_t connection_tail_replay_source_frontier_candidate_pair_count_0x4a79a3 = 0;
	int32_t connection_tail_replay_source_frontier_neighbor_terrain8_skip_count_0x4a79a3 = 0;
	int32_t connection_tail_replay_source_frontier_same_owner_skip_count_0x4a79a3 = 0;
	int32_t connection_tail_replay_source_frontier_out_of_bounds_skip_count_0x4a79a3 = 0;
	int32_t connection_tail_replay_relation_owner_level_byte2b_clear_pass_count_0x4a79a3 = 0;
	int32_t connection_tail_replay_relation_owner_level_byte2b_clear_cell_count_0x4a79a3 = 0;
	bool connection_tail_replay_internal_growth_known_0x49b3fb_0x4a61bc = false;
	int32_t connection_tail_replay_internal_growth_candidate_pair_count_0x4a79a3 = 0;
	bool connection_tail_replay_internal_growth_0x4a61bc_prefix_owned = false;
	int32_t connection_tail_replay_internal_growth_0x4a61bc_invocation_count = 0;
	int32_t connection_tail_replay_internal_growth_0x4a61bc_entry_gate_pass_count = 0;
	int32_t connection_tail_replay_internal_growth_0x4a61bc_frontier_candidate_count = 0;
	int32_t connection_tail_replay_internal_growth_0x4a61bc_selected_candidate_count = 0;
	int32_t connection_tail_replay_internal_growth_0x4a61bc_selected_loop_count = 0;
	int32_t connection_tail_replay_internal_growth_0x4a61bc_rng_selection_count = 0;
	int32_t connection_tail_replay_internal_growth_0x4a61bc_projection_chain_call_count = 0;
	int32_t connection_tail_replay_internal_growth_0x4a61bc_projection_occupied_stamp_count = 0;
	int32_t connection_tail_replay_internal_growth_0x4a61bc_projection_cleanup_clear_count = 0;
	int32_t connection_tail_replay_internal_growth_0x4a61bc_local_vector_append_count_0x404 = 0;
	int32_t connection_tail_replay_internal_growth_0x4a61bc_guard_budget_positive_count = 0;
	int32_t connection_tail_replay_internal_growth_0x4a61bc_projection_object_branch_blocked_count = 0;
	int32_t connection_tail_replay_internal_growth_0x4a61bc_constructor_blocked_count = 0;
	std::string connection_tail_replay_blocked_reason_0x4a79a3;
	std::string materialization_bridge_0x4a8c15_blocked_reason;
	bool weighted_candidate_vectors_0x4a901a_known = false;
	int32_t weighted_candidate_vector_count_0x4a901a = 0;
	int32_t weighted_candidate_total_count_0x4a901a = 0;
	int32_t weighted_candidate_selected_count_0x4a901a = 0;
	int32_t weighted_candidate_commit_count_0x4a901a = 0;
	std::vector<SharedWeightedObjectCandidateVectorState4a901a> weighted_candidate_vectors_0x4a901a;
	bool source_order_direct_candidates_0x4a93a2_known = false;
	int32_t source_order_direct_candidate_vector_count_0x4a93a2 = 0;
	int32_t source_order_direct_candidate_total_count_0x4a93a2 = 0;
	int32_t source_order_direct_selected_count_0x4a93a2 = 0;
	int32_t source_order_direct_commit_count_0x4a93a2 = 0;
	std::vector<SharedObjectRecordReference4a54a7> object_records_0xec4_ecc;
	int32_t object_record_vector_append_count_0x4a54a7 = 0;
	int32_t generated_cell_object_reference_append_count_0x4a54a7 = 0;
	int32_t descriptor_counter_increment_count_0x4a54a7 = 0;
	int32_t relation_descriptor_counter_increment_count_0x4a54a7 = 0;
	int32_t target_cell_word_mutation_count_0x4a54a7 = 0;
	int32_t projection_score_depletion_count_0x4a54a7 = 0;
	bool source_owner_player_slots_ed8_ee0_ee4_present = false;
	int32_t selected_color_order_ed8_count = 0;
	int32_t raw_source_owner_slots_ee0_count = 0;
	int32_t mapped_source_owner_slots_ee4_count = 0;
	std::vector<int32_t> selected_color_order_ed8;
	std::vector<int32_t> raw_source_owner_slots_ee0;
	std::vector<int32_t> mapped_source_owner_slots_ee4;
	bool relation_owner_records_10e4_10e8_partial_known = false;
	int32_t relation_owner_vector_count_10e4_10e8 = 0;
	int32_t relation_record_count_10e4_10e8 = 0;
	int32_t relation_record_missing_endpoint_count_10e4_10e8 = 0;
	std::vector<SharedGeneratorRelationOwnerState> relation_owner_vectors_10e4_10e8;
	bool reward_guard_relation_priority_helper_0x4ad6a8_0x4ad7f7_ported = false;
	bool reward_guard_relation_priority_live_replay_blocked = false;
	std::string reward_guard_relation_priority_live_replay_blocker;
	bool reward_guard_projection_source_relation_0x4ad947_ported = false;
	bool reward_guard_projection_source_relation_input_known = false;
	bool reward_guard_projection_source_relation_applied_0x4ad947 = false;
	bool reward_guard_projection_source_relation_grid_available_0x4ad947 = false;
	bool reward_guard_projection_source_relation_word_0x20_known = false;
	int32_t reward_guard_projection_source_relation_x_0x4ad947 = 0;
	int32_t reward_guard_projection_source_relation_y_0x4ad947 = 0;
	int32_t reward_guard_projection_source_relation_level_0x4ad947 = 0;
	int64_t reward_guard_projection_source_relation_flat_index_0x4ad947 = -1;
	uint32_t reward_guard_projection_source_relation_word_0x20_0x4ad947 = 0U;
	int32_t reward_guard_projection_source_relation_owner_high_byte_signed_0x4ad947 = -1;
	int32_t reward_guard_projection_source_relation_owner_vector_index_0x4ad947 = -1;
	bool reward_guard_projection_source_relation_known_0x4ad947 = false;
	int32_t reward_guard_projection_source_relation_runtime_zone_index_0x4ad947 = -1;
	std::string reward_guard_projection_source_relation_blocked_reason_0x4ad947;
	bool reward_guard_projection_generator_0x10b4_known = false;
	bool reward_guard_projection_generator_0x10b4 = false;
	bool reward_guard_projection_used_flags_0x1024_known = false;
	int32_t reward_guard_projection_used_flags_0x1024_count = 0;
	int32_t reward_guard_projection_used_flags_0x1024_zero_count = 0;
	bool reward_guard_projection_driver_selection_0x4ad947_ported = false;
	bool reward_guard_projection_driver_selection_input_known = false;
	bool reward_guard_projection_driver_selection_applied_0x4ad947 = false;
	int32_t reward_guard_projection_driver_scanned_entry_count_0x4ad947 = 0;
	int32_t reward_guard_projection_driver_field_unknown_count_0x4ad947 = 0;
	int32_t reward_guard_projection_driver_disabled_reject_count_0x4ad947 = 0;
	int32_t reward_guard_projection_driver_used_flag_reject_count_0x4ad947 = 0;
	int32_t reward_guard_projection_driver_flag_bit_reject_count_0x4ad947 = 0;
	int32_t reward_guard_projection_driver_eligible_count_0x4ad947 = 0;
	bool reward_guard_projection_driver_generator_0x10b4_written = false;
	bool reward_guard_projection_driver_generator_0x10b4_value = false;
	int32_t reward_guard_projection_driver_rng_value_0x4e7276 = -1;
	int32_t reward_guard_projection_driver_selected_eligible_ordinal = -1;
	int32_t reward_guard_projection_driver_selected_global_entry_index = -1;
	bool reward_guard_projection_driver_projection_record_0x1c_written = false;
	std::string reward_guard_projection_driver_blocked_reason_0x4ad947;
	bool reward_guard_selector_0x4a9f1c_counter_limit_contract_ported = false;
	bool reward_guard_candidate_records_10f4_10f8_contents_known = false;
	int32_t reward_guard_candidate_record_count_10f4_10f8 = 0;
	bool reward_guard_selector_0x4a9f1c_applied = false;
	bool reward_guard_selector_0x4a9f1c_candidate_vector_present = false;
	bool reward_guard_selector_0x4a9f1c_candidate_vector_contents_known = false;
	int32_t reward_guard_selector_0x4a9f1c_candidate_scan_count = 0;
	int32_t reward_guard_selector_0x4a9f1c_descriptor_type_missing_count = 0;
	int32_t reward_guard_selector_0x4a9f1c_counter_input_missing_count = 0;
	int32_t reward_guard_selector_0x4a9f1c_global_limit_reject_count = 0;
	int32_t reward_guard_selector_0x4a9f1c_relation_limit_reject_count = 0;
	int32_t reward_guard_selector_0x4a9f1c_value_bound_reject_count = 0;
	int32_t reward_guard_selector_0x4a9f1c_accepted_count = 0;
	std::string reward_guard_selector_0x4a9f1c_blocked_reason;
	bool relation_owner_scan_bounds_0x4a1f3b_applied = false;
	int32_t relation_owner_scan_bounds_known_count_0x4a1f3b = 0;
	int32_t relation_owner_scan_bounds_blocked_count_0x4a1f3b = 0;
	bool relation_normalization_4a5767_full_grid_reset_applied = false;
	int32_t relation_normalization_4a5767_full_grid_reset_visited_count = 0;
	int32_t relation_normalization_4a5767_full_grid_reset_changed_count = 0;
	int32_t relation_normalization_4a5767_full_grid_reset_skipped_count = 0;
	bool relation_scan_consumers_4a5767_applied = false;
	bool relation_scan_consumers_4a5767_no_object_projection_chain_complete = false;
	int32_t relation_scan_consumer_owner_scan_count_4a5767 = 0;
	int32_t relation_scan_consumer_owner_bounds_blocked_count_4a5767 = 0;
	int32_t relation_scan_consumer_scanned_cell_count_4a5767 = 0;
	int32_t relation_scan_consumer_object_branch_blocked_count_4a5767 = 0;
	int32_t relation_scan_consumer_projected_chain_call_count_4a5767 = 0;
	int32_t relation_scan_consumer_projected_chain_occupied_stamp_count_4a5767 = 0;
	int32_t relation_scan_consumer_projected_chain_cleanup_clear_count_4a5767 = 0;
	int32_t relation_scan_consumer_object_branch_attempt_count_4a5767 = 0;
	int32_t relation_scan_consumer_object_branch_commit_count_4a5767 = 0;
	bool relation_high_owner_propagation_49a318_applied = false;
	bool relation_high_owner_propagation_49a318_grid_available = false;
	bool relation_high_owner_propagation_49a318_object_metadata_gate_complete = false;
	int32_t relation_high_owner_seed_attempt_count_49a318 = 0;
	int32_t relation_high_owner_seed_blocked_count_49a318 = 0;
	int32_t relation_high_owner_popped_cell_count_49a318 = 0;
	int32_t relation_high_owner_same_owner_relax_count_49a318 = 0;
	int32_t relation_high_owner_cross_owner_high_byte_write_count_49a318 = 0;
	int32_t relation_high_owner_max_queue_size_49a318 = 0;
	int32_t relation_high_owner_materialized_count_49a318 = 0;
	int32_t relation_high_owner_sentinel_count_49a318 = 0;
	std::vector<std::string> remaining_private_state_blockers;
};

struct RecoveredOwnerGridPayload {
	SharedRuntimeChainInput input;
	std::vector<std::string> missing_inputs;
	bool executable = false;
	bool built = false;
	bool coordinate_seed_blocked = false;
	bool owner_grid_executed = false;
	bool footprint_finalizer_executed = false;
	bool footprint_finalizer_blocked = false;
	std::string footprint_finalizer_status;
	bool source_blocked = false;
	bool generated_cell_private_state_comparable = false;
	std::string generated_cell_private_state_status;
	std::string terrain_selection_repaint_status;
	int32_t width = 0;
	int32_t height = 0;
	int32_t level_count = 0;
	int32_t coordinate_rng_call_count = 0;
	int32_t coordinate_generator_mode_0x10b8 = 0;
	int32_t coordinate_minimum_source_base_size = 0;
	int32_t coordinate_prune_divisor_4a218c = 0;
	int32_t coordinate_prune_span_budget_4a218c = 0;
	int32_t town_choice_rng_call_count_0x49b3c1 = 0;
	int32_t terrain_selection_rng_call_count_0x49b53d = 0;
	int32_t terrain_selection_match_to_town_count = 0;
	int32_t terrain_selection_allowed_flag_choice_count = 0;
	int32_t terrain_selection_no_eligible_default_zero_count = 0;
	int32_t terrain_repaint_write_count_0x4a4163 = 0;
	int32_t terrain_visual_write_count_0x4bb74b = 0;
	int32_t terrain_visual_missing_bucket_count_0x4bcfc3 = 0;
	int32_t terrain_visual_art_nonzero_cell_count = 0;
	int32_t terrain_visual_flag_cell_count = 0;
	int32_t terrain_visual_final_sweep_cell_count_0x4bbfcc = 0;
	int32_t terrain_visual_preserved_current_record_count_0x4bc5a3 = 0;
	int32_t terrain_visual_roundtrip_mismatch_count = 0;
	uint32_t coordinate_rng_state_before = 0;
	uint32_t coordinate_rng_state_after = 0;
	uint32_t terrain_selection_rng_state_after = 0;
	uint32_t terrain_visual_rng_state_after_0x4bb74b = 0;
	int32_t coordinate_placement_step_count = 0;
	int32_t coordinate_boundary_input_count = 0;
	int32_t source_descriptor_node_count = 0;
	int32_t source_descriptor_active_node_count = 0;
	int32_t source_node_walk_count = 0;
	int32_t source_handoff_count = 0;
	int32_t missing_boundary_input_count = 0;
	int32_t missing_source_walk_count = 0;
	int32_t materialization_source_handoff_count = 0;
	int32_t materialization_source_handoff_descriptor_indexed_point_count = 0;
	int32_t materialization_source_handoff_raw_coordinate_point_count = 0;
	int32_t materialization_source_record_seed_count = 0;
	int32_t materialization_missing_source_record_seed_count = 0;
	int32_t materialization_runtime_zone_walk_count = 0;
	int32_t materialization_appended_vertex_count = 0;
	int32_t materialization_span_fill_zone_count = 0;
	int32_t footprint_finalizer_original_same_level_runtime_zone_count = 0;
	int32_t footprint_finalizer_final_runtime_zone_count = 0;
	int32_t footprint_finalizer_appended_runtime_zone_count = 0;
	int32_t footprint_finalizer_zone_order_reset_call_count = 0;
	int32_t footprint_finalizer_per_zone_order_helper_call_count = 0;
	std::vector<std::string> missing_generated_cell_mutation_phases;
	std::vector<std::string> terrain_selection_parity_blockers;
	std::vector<std::string> terrain_repaint_parity_blockers;
	std::vector<TerrainVisualMissingBucketSample> terrain_visual_missing_bucket_samples_0x4bcfc3;
	bool generated_cell_record_shape_0x30_present = false;
	int32_t generated_cell_record_stride_bytes = 0x30;
	std::string generated_cell_record_surface_status;
	SharedGeneratorObjectPrivateState generator_object_private_state;
	std::vector<SharedGeneratedCellRecord0x30> generated_cell_records_0x30;
	std::vector<uint32_t> generated_cell_word_0x10;
	std::vector<uint32_t> generated_cell_word_0x1c;
	std::vector<uint32_t> generated_cell_word_0x20;
	std::vector<uint32_t> generated_cell_word_0x24;
	std::vector<uint32_t> generated_cell_word_0x28;
	std::vector<uint32_t> generated_cell_word_0x2c;
	bool source_object_catalog_0x49da08_present = false;
	int32_t source_object_catalog_0x49da08_record_count = 0;
	int32_t source_object_catalog_0x4c_copy_size_bytes = 0;
	int32_t source_object_catalog_objects_txt_record_count = 0;
	int32_t source_object_catalog_rand_trn_backed_record_count = 0;
	int32_t source_object_catalog_passability_mask_record_count = 0;
	int32_t source_object_catalog_action_mask_record_count = 0;
	int32_t source_object_catalog_descriptor_mask_field_record_count = 0;
	int32_t source_object_catalog_descriptor_mask_exact_def_msk_count = 0;
	int32_t source_object_catalog_descriptor_mask_default_msk_fallback_count = 0;
	int32_t source_object_catalog_type53_record_count = 0;
	int32_t source_object_catalog_type53_ambiguous_subtype_count = 0;
	bool source_object_catalog_descriptor_only_mine_identity_ambiguous = false;
	std::vector<SharedSourceObjectRecord0x4c> source_object_catalog_samples;
	bool source_object_wrapper_buckets_0x49db76_present = false;
	int32_t source_object_wrapper_bucket_count_0xe8 = 0;
	int32_t source_object_wrapper_initialized_bucket_count = 0;
	int32_t source_object_wrapper_non_empty_bucket_count = 0;
	int32_t source_object_wrapper_total_source_record_references = 0;
	int32_t source_object_wrapper_out_of_range_source_record_count = 0;
	int32_t source_object_wrapper_max_bucket_record_count = 0;
	int32_t source_object_wrapper_max_bucket_index_0x08 = -1;
	std::vector<SharedSourceObjectWrapperBucket0xe8> source_object_wrapper_bucket_samples;
	std::vector<SharedSourceObjectSelectorResult4a9e40> source_object_selector_samples_0x4a9e40;
	std::vector<SharedSourceObjectResolverResult4af785> source_object_resolver_samples_0x4af785;
};

struct NativeH3MapedWorkflowPhase {
	std::string id;
	std::string h3maped_anchor;
	std::string status;
	std::string blocker;
};

struct NativeH3MapedWorkflowResult {
	ControlledCase input;
	bool supported_scope = false;
	bool executed = false;
	bool final_payload_owned = false;
	bool final_writeout_complete = false;
	std::string status;
	std::string blocked_reason;
	std::string current_phase_id;
	RecoveredOwnerGridPayload payload;
	std::vector<NativeH3MapedWorkflowPhase> phases;
};

ControlledCase parse_controlled_case(const std::string &raw);
std::vector<std::string> split_case_filter(const std::string &case_filter);
bool case_matches_filter(const ControlledCase &controlled_case, const std::vector<std::string> &filters);
SharedRuntimeChainInput resolved_shared_runtime_chain_input(const ControlledCase &controlled_case, const SharedRuntimeChainInput &input);
RecoveredOwnerGridPayload build_recovered_owner_grid_payload(const ControlledCase &controlled_case, const SharedRuntimeChainInput &input);
NativeH3MapedWorkflowResult run_native_h3maped_workflow(const ControlledCase &controlled_case, const SharedRuntimeChainInput &input);
std::string shared_runtime_chain_input_status(const ControlledCase &controlled_case, const SharedRuntimeChainInput &input);
bool shared_runtime_chain_input_executable(const ControlledCase &controlled_case, const SharedRuntimeChainInput &input);
std::string case_native_h3maped_workflow_json(const ControlledCase &controlled_case, const std::string &status, const std::string &blocked_reason, const SharedRuntimeChainInput &shared_input);
std::string safe_case_filename(const std::string &case_id);

} // namespace aurelion::rmg_native_core
