#!/usr/bin/env python3
"""Author eight long-form Commander Doctrine Expeditions and their landmark art."""

from __future__ import annotations

import json
from pathlib import Path

from PIL import Image

import author_eight_commanders_proving_roads as base


ROOT = Path(__file__).resolve().parents[1]
CONTENT = ROOT / "content"
SOURCE_ROOT = ROOT / "art/overworld/source/generated/resource_sites/commander_doctrine_expeditions_wave1"
ATLAS_PATH = ROOT / "art/overworld/runtime/objects/resource_sites/commander_doctrine_expeditions_atlas.png"
ATLAS_RES = "res://art/overworld/runtime/objects/resource_sites/commander_doctrine_expeditions_atlas.png"
SOURCE_RES = "res://art/overworld/source/generated/resource_sites/commander_doctrine_expeditions_wave1"
ART_MANIFEST = ROOT / "art/overworld/manifest.json"
SLICE_ID = "content-eight-commander-doctrine-expeditions-10184"
GENERATOR_ROOT = Path("/root/.codex/generated_images/019fe72a-30b1-76f3-b911-385c4444bd16")


STACKS = {
    "faction_brasshollow": [("unit_brasshollow_scrip_haulers", 36), ("unit_brasshollow_quenchspool_slingers", 24), ("unit_brasshollow_gaugefire_arbalists", 14), ("unit_brasshollow_boiler_rivetcasters", 8), ("unit_brasshollow_pressure_lancers", 4)],
    "faction_mireclaw": [("unit_mireclaw_reedsnare_kin", 60), ("unit_mireclaw_mudglass_slingers", 40), ("unit_mireclaw_bogplate_maulers", 24), ("unit_mireclaw_ferrychain_lashers", 14), ("unit_mireclaw_mireglass_reedcasters", 8)],
    "faction_sunvault": [("unit_sunvault_shard_wardens", 60), ("unit_sunvault_prism_adepts", 40), ("unit_sunvault_mirror_duelists", 24), ("unit_sunvault_resonant_choristers", 14), ("unit_sunvault_noonfacet_sentinels", 8)],
    "faction_thornwake": [("unit_thornwake_seedcutters", 40), ("unit_thornwake_bramblekite_needlers", 26), ("unit_thornwake_seedshield_wardens", 16), ("unit_thornwake_barkmantle_rams", 9), ("unit_thornwake_seedglass_cantors", 5)],
    "faction_veilmourn": [("unit_veilmourn_bellwake_oars", 36), ("unit_veilmourn_mourning_lanterns", 24), ("unit_veilmourn_maskglass_corsairs", 14), ("unit_veilmourn_undertow_harpooners", 8), ("unit_veilmourn_wakeglass_navigators", 4)],
}


CASES = [
    {"prefix": "heatdoctrine", "scenario_id": "heatpriest-quench-censer-expedition", "scenario_name": "Heatpriest Quench-Censer Expedition", "hero_id": "hero_brasshollow_odrik_heatpriest", "faction_id": "faction_brasshollow", "home_town_id": "town_cindercoil_foundry", "enemy_town_id": "town_veilmourn_fogchart_mooring", "enemy_faction_id": "faction_veilmourn", "enemy_label": "Wakeglass Quench-Takers", "site_id": "site_heatpriest_quench_censer", "site_name": "Heatpriest Quench-Censer", "asset_id": "resource_site_doctrine_heatpriest_quench_censer", "source_name": "heatpriest_quench_censer_source.png", "generation_original": "exec-65b6cfd9-32aa-4c06-a951-c16e218f741f.png", "action_label": "Set the Quench Doctrine", "command_key": "power", "rare_site_id": "site_brass_scrip_mint", "terrain": ("rough", "lava"), "seed": 52100, "encounters": ["encounter_vanehook_named_rival_company", "encounter_wakechain_border_cordon", "encounter_third_hearths_wakeglass_pilots", "encounter_veyra_drowned_orchard"], "subject": "one squat armored furnace censer on three broad iron feet, broken circular heat halo, two offset pressure pipes, hanging coal bowl, narrow chimney capped by hammer-shaped vent", "description": "Three broad feet brace a squat furnace beneath a broken heat halo, offset pipes, a hanging coal bowl, and a hammer-capped vent."},
    {"prefix": "fenhookdoctrine", "scenario_id": "fenhook-blind-levee-expedition", "scenario_name": "Fenhook Blind-Levee Expedition", "hero_id": "hero_tarn", "faction_id": "faction_mireclaw", "home_town_id": "town_murkward_ford", "enemy_town_id": "town_prismhearth", "enemy_faction_id": "faction_sunvault", "enemy_label": "Prism-Levee Surveyors", "site_id": "site_fenhook_blind_levee_snare", "site_name": "Fenhook Blind-Levee Snare", "asset_id": "resource_site_doctrine_fenhook_blind_levee_snare", "source_name": "fenhook_blind_levee_snare_source.png", "generation_original": "exec-ff799d58-e90c-4b29-a953-60bff220a4b6.png", "action_label": "Close the Blind Levee", "command_key": "attack", "rare_site_id": "site_peatwax_reed_yard", "terrain": ("mire", "swamp"), "seed": 52200, "encounters": ["encounter_facetline_named_rival_company", "encounter_muckscript_prism_inquest", "encounter_prismwrit_border_cordon", "encounter_halo_spire_noon_watch"], "subject": "one low crescent levee marker built from dark wet timbers, wrapped by a large hooked rope snare, three uneven reed fins, two hanging bone floats, narrow concealed stepping gate", "description": "A low crescent of wet timbers hides a narrow gate inside one huge hooked snare, three reed fins, and two unequal bone floats."},
    {"prefix": "choirwarddoctrine", "scenario_id": "choirward-resonance-bastion-expedition", "scenario_name": "Choirward Resonance-Bastion Expedition", "hero_id": "hero_thalen", "faction_id": "faction_sunvault", "home_town_id": "town_meridian_choirhold", "enemy_town_id": "town_blackfen_gate", "enemy_faction_id": "faction_mireclaw", "enemy_label": "Moonhook Dissonance Levy", "site_id": "site_choirward_resonance_bastion", "site_name": "Choirward Resonance Bastion", "asset_id": "resource_site_doctrine_choirward_resonance_bastion", "source_name": "choirward_resonance_bastion_source.png", "generation_original": "exec-8653d6ac-c351-4bd4-84ee-ed35401e736a.png", "action_label": "Tune the Bastion", "command_key": "defense", "rare_site_id": "site_aetherglass_lens_house", "terrain": ("sand", "rough"), "seed": 52300, "encounters": ["encounter_moonhook_border_cordon", "encounter_reedbarrow_chain", "encounter_selka_peat_chain_levy", "encounter_tollmoon_named_rival_company"], "subject": "one compact pale-stone bastion with three open singing arches, asymmetrical prism roof, two suspended tuning bells, broad stepped base, tall resonance fork", "description": "Three open singing arches rise from a broad stepped base beneath an uneven prism roof, two bells, and one tall tuning fork."},
    {"prefix": "mirrorstepdoctrine", "scenario_id": "mirrorstep-parallax-gate-expedition", "scenario_name": "Mirrorstep Parallax-Gate Expedition", "hero_id": "hero_varis", "faction_id": "faction_sunvault", "home_town_id": "town_halo_spire", "enemy_town_id": "town_rainwrit_bastion", "enemy_faction_id": "faction_embercourt", "enemy_label": "Lockfire Meridian Claim", "site_id": "site_mirrorstep_parallax_gate", "site_name": "Mirrorstep Parallax Gate", "asset_id": "resource_site_doctrine_mirrorstep_parallax_gate", "source_name": "mirrorstep_parallax_gate_source.png", "generation_original": "exec-1277d061-0aee-470f-87e3-263e40ec270d.png", "action_label": "Align the Parallax Gate", "command_key": "attack", "rare_site_id": "site_aetherglass_lens_house", "terrain": ("sand", "grass"), "seed": 52400, "encounters": ["encounter_mill_levies", "encounter_pikeward_named_rival_company", "encounter_horizon_court_rainwrit_tidewrit_assize", "encounter_jessa_lockfire_boom"], "subject": "two tall offset mirrored arches overlap without touching, narrow zigzag brass walkway, floating diamond lens, three calibration needles, broken side stair", "description": "Two tall mirrored arches overlap without touching above a zigzag walkway, floating diamond lens, three needles, and a broken stair."},
    {"prefix": "mossveindoctrine", "scenario_id": "mossvein-memory-cairn-expedition", "scenario_name": "Mossvein Memory-Cairn Expedition", "hero_id": "hero_thornwake_ralka_mossvein", "faction_id": "faction_thornwake", "home_town_id": "town_crownroot_refuge", "enemy_town_id": "town_blackbell_foundry", "enemy_faction_id": "faction_brasshollow", "enemy_label": "Blackbell Root-Assayers", "site_id": "site_mossvein_memory_cairn", "site_name": "Mossvein Memory Cairn", "asset_id": "resource_site_doctrine_mossvein_memory_cairn", "source_name": "mossvein_memory_cairn_source.png", "generation_original": "exec-beba183e-29b3-4554-81e4-79a1ecc6f635.png", "action_label": "Read the Moss Memory", "command_key": "knowledge", "rare_site_id": "site_verdant_graft_nursery", "terrain": ("forest", "grass"), "seed": 52500, "encounters": ["encounter_bellfounder_named_rival_company", "encounter_blackbell_border_cordon", "encounter_blackbell_quench_watch", "encounter_horizon_court_blackbell_quenchline_assize"], "subject": "one leaning spiral cairn of seven uneven dark stones bound by living moss veins, three shallow memory bowls, forked root crown, hanging seedglass drop", "description": "Seven uneven stones spiral upward in living moss beneath a forked root crown, with three shallow bowls and one hanging seedglass drop."},
    {"prefix": "bramblehounddoctrine", "scenario_id": "bramble-hound-pursuit-kennel-expedition", "scenario_name": "Bramble-Hound Pursuit-Kennel Expedition", "hero_id": "hero_thornwake_silsa_bramblehound", "faction_id": "faction_thornwake", "home_town_id": "town_thornwake_graftroot_caravan", "enemy_town_id": "town_gloamwake_anchorage", "enemy_faction_id": "faction_veilmourn", "enemy_label": "Fogchart False-Trail Crew", "site_id": "site_bramble_hound_pursuit_kennel", "site_name": "Bramble-Hound Pursuit Kennel", "asset_id": "resource_site_doctrine_bramble_hound_pursuit_kennel", "source_name": "bramble_hound_pursuit_kennel_source.png", "generation_original": "exec-bce35ea1-fecf-44cc-9dfa-efda8595d06d.png", "action_label": "Loose the Pursuit Trail", "command_key": "attack", "rare_site_id": "site_verdant_graft_nursery", "terrain": ("forest", "mire"), "seed": 52600, "encounters": ["encounter_vanehook_named_rival_company", "encounter_wakechain_border_cordon", "encounter_third_hearths_wakeglass_pilots", "encounter_veyra_drowned_orchard"], "subject": "one low arched field kennel woven from thorny living branches, crowned by two mismatched antlers, large hooked hunt whistle, three paw-shaped track plaques, open dark passage", "description": "A low open kennel of thorn branches carries two mismatched antlers, one hooked whistle, and three paw-shaped trail plaques."},
    {"prefix": "rootwrightdoctrine", "scenario_id": "rootwright-living-span-expedition", "scenario_name": "Rootwright Living-Span Expedition", "hero_id": "hero_thornwake_tova_rootwright", "faction_id": "faction_thornwake", "home_town_id": "town_thornwake_rootgate_nursery", "enemy_town_id": "town_dawnmirror_observatory", "enemy_faction_id": "faction_sunvault", "enemy_label": "Noonfacet Span-Breakers", "site_id": "site_rootwright_living_span", "site_name": "Rootwright Living Span", "asset_id": "resource_site_doctrine_rootwright_living_span", "source_name": "rootwright_living_span_source.png", "generation_original": "exec-6ec54d26-9041-42ef-821a-43200bcad09b.png", "action_label": "Set the Living Span", "command_key": "defense", "rare_site_id": "site_verdant_graft_nursery", "terrain": ("forest", "sand"), "seed": 52700, "encounters": ["encounter_muckscript_prism_inquest", "encounter_prismwrit_border_cordon", "encounter_horizon_meridian_choir_array", "encounter_three_banner_zenith_lensbearers"], "subject": "one compact arched bridge scaffold grown from three braided living roots, two asymmetrical bark piers, leaf tension braces, hanging seed counterweight, narrow woven crossing deck", "description": "Three braided living roots form a compact bridge between unequal bark piers, leaf braces, a woven deck, and one hanging seed weight."},
    {"prefix": "nightchartdoctrine", "scenario_id": "nightchart-false-star-orrery-expedition", "scenario_name": "Nightchart False-Star Orrery Expedition", "hero_id": "hero_veilmourn_orso_nightchart", "faction_id": "faction_veilmourn", "home_town_id": "town_pale_sounding_harbor", "enemy_town_id": "town_briarwheel_enclave", "enemy_faction_id": "faction_thornwake", "enemy_label": "Graftwake Star-Hunters", "site_id": "site_nightchart_false_star_orrery", "site_name": "Nightchart False-Star Orrery", "asset_id": "resource_site_doctrine_nightchart_false_star_orrery", "source_name": "nightchart_false_star_orrery_source.png", "generation_original": "exec-20070e7b-3729-4a3c-880b-d4a150907ea8.png", "action_label": "Chart the False Star", "command_key": "knowledge", "rare_site_id": "site_memory_salt_pan", "terrain": ("snow", "mire"), "seed": 52800, "encounters": ["encounter_greenbarrow_named_rival_company", "encounter_horizon_court_crownroot_rootglass_jury", "encounter_mistcorsair_graftwake_cordon", "encounter_damar_worldroot_wake"], "subject": "one crooked nautical orrery on a tripod sounding pole, with three mismatched orbit rings, a false eight-point star lens, a crescent tide dial, two hanging memory bells, and one long direction hook", "description": "A crooked tripod orrery carries three mismatched orbit rings, an eight-point false star, crescent dial, two bells, and a long hook."},
]


def terrain_map(primary: str, secondary: str, seed: int) -> list[list[str]]:
    return [[secondary if (x * 7 + y * 11 + seed) % 19 in (0, 1, 2, 3) else primary for x in range(18)] for y in range(12)]


def render_art() -> tuple[str, list[dict]]:
    ATLAS_PATH.parent.mkdir(parents=True, exist_ok=True)
    atlas = Image.new("RGBA", (384, 48), (0, 0, 0, 0))
    rows: list[dict] = []
    for index, case in enumerate(CASES):
        source = SOURCE_ROOT / case["source_name"]
        atlas.alpha_composite(base.transparent_frame(source), (index * 48, 0))
        prompt = (
            "Use case: stylized-concept; Asset type: production 2D fantasy strategy-game overworld command landmark source; "
            f"Primary request: Create {case['site_name']} for the original Aurelion Reach setting; Scene/backdrop: genuinely transparent background; Subject: {case['subject']}; "
            "Style/medium: polished hand-painted 2D original fantasy game landmark art with crisp material separation; Composition/framing: isolated high three-quarter view, centered with generous padding, strong silhouette readable at 48x48; "
            "Constraints: one landmark only; preserved alpha; no ground, scenery, characters, text, letters, numbers, logos, watermark, border, frame, cast shadow, or copied franchise design."
        )
        rows.append({"site_id": case["site_id"], "hero_id": case["hero_id"], "asset_id": case["asset_id"], "source_path": f"{SOURCE_RES}/{case['source_name']}", "source_sha256": base.sha256(source), "generation_original": str(GENERATOR_ROOT / case["generation_original"]), "atlas_region": [index * 48, 0, 48, 48], "prompt": prompt, "accessible_description": case["description"]})
    atlas.save(ATLAS_PATH, optimize=True, compress_level=9)
    atlas_sha = base.sha256(ATLAS_PATH)
    base.write_pretty(SOURCE_ROOT / "manifest.json", {"schema_id": "eight_commander_doctrine_expeditions_art_v1", "content_batch_id": SLICE_ID, "generation_mode": "built_in_imagegen", "source_model": "built_in_imagegen_original_commander_doctrine_expeditions_atlas", "prompt_set_summary": "Eight original transparent command landmarks for eight underused live heroes, with non-color silhouettes readable at 48px and no packaged source-master dependency.", "runtime_atlas": ATLAS_RES, "runtime_atlas_size": [384, 48], "runtime_atlas_sha256": atlas_sha, "source_package_policy": "retained_for_provenance_excluded_from_linux_and_windows_exports", "items": rows})
    return atlas_sha, rows


def scenario_record(case: dict, hero_name: str, army_id: str) -> dict:
    prefix = case["prefix"]
    stacks = STACKS[case["faction_id"]]
    coords = [(5, 2), (7, 9), (11, 3), (13, 8)]
    encounters = [{"placement_id": f"{prefix}_front_{index}", "encounter_id": encounter_id, "x": xy[0], "y": xy[1], "difficulty": "medium" if index < 4 else "high", "combat_seed": case["seed"] + index, "prefer_identity_landmark": True, "guardian_role": "commander_doctrine_front"} for index, (encounter_id, xy) in enumerate(zip(case["encounters"], coords), start=1)]
    victories = [{"id": f"{prefix}_hold_command", "label": f"Keep {hero_name} in command of the five-company expedition", "type": "hero_army_meets_requirements", "hero_id": case["hero_id"], "requirements": [{"unit_id": stacks[0][0], "minimum_count": 1}]}, {"id": f"{prefix}_claim_doctrine", "label": f"Claim {case['site_name']}", "type": "flag_true", "flag": f"{prefix}_doctrine_landmark_claimed"}]
    victories.extend({"id": f"{prefix}_clear_front_{index}", "label": f"Resolve doctrine front {index}", "type": "encounter_resolved", "placement_id": f"{prefix}_front_{index}"} for index in range(1, 5))
    return {
        "id": case["scenario_id"], "name": case["scenario_name"],
        "selection": {"summary": f"Lead {hero_name} across four contested fronts, secure {case['site_name']}, and hold both ends of a long command route before Day 19.", "recommended_difficulty": "hard", "map_size_label": "Commander Doctrine Expedition (18x12)", "player_summary": f"{hero_name} commands an exact five-stack field company across a long-form route with a guarded doctrine landmark.", "enemy_summary": f"{case['enemy_label']} hold an enemy town, four distinct fronts, and a late reserve route.", "availability": {"campaign": False, "skirmish": True}},
        "map_size": {"width": 18, "height": 12}, "player_faction_id": case["faction_id"], "player_army_id": army_id, "hero_id": case["hero_id"],
        "starting_resources": {"gold": 11000, "wood": 12, "ore": 12, "embergrain": 4, "aetherglass": 4, "peatwax": 4, "verdant_grafts": 4, "brass_scrip": 4, "memory_salt": 4},
        "map": terrain_map(*case["terrain"], case["seed"]), "start": {"x": 1, "y": 6}, "hero_starts": [case["hero_id"]],
        "objectives": {"victory_text": f"{hero_name} holds the full expedition route and carries its doctrine into active command.", "defeat_text": "The home town falls, enemy pressure closes the route, or the nineteenth day arrives before the doctrine is secured.", "victory": victories, "defeat": [{"id": f"{prefix}_lose_home", "label": "Keep the expedition's home town", "type": "town_not_owned_by_player", "placement_id": f"{prefix}_home"}, {"id": f"{prefix}_pressure", "label": "Keep route pressure below 26", "type": "enemy_pressure_at_least", "faction_id": case["enemy_faction_id"], "threshold": 26}, {"id": f"{prefix}_deadline", "label": "Complete the doctrine expedition before Day 19", "type": "day_at_least", "day": 19}]},
        "script_hooks": [
            {"id": f"{prefix}_day_two_muster", "priority": 130, "conditions": [{"type": "day_at_least", "day": 2}, {"type": "town_owned_by_player", "placement_id": f"{prefix}_home"}], "effects": [{"type": "add_resources", "resources": {"gold": 3600, "wood": 2, "ore": 2}}, {"type": "town_add_recruits", "placement_id": f"{prefix}_home", "recruits": {stacks[0][0]: 5, stacks[1][0]: 3}}, {"type": "message", "text": "The home council opens the long-route muster before the expedition departs."}]},
            {"id": f"{prefix}_first_front_relief", "priority": 120, "conditions": [{"type": "encounter_resolved", "placement_id": f"{prefix}_front_1"}], "effects": [{"type": "add_army_units", "units": {stacks[0][0]: 4, stacks[2][0]: 2}}, {"type": "message", "text": "Freed route hands reinforce the commander's active expedition."}]},
            {"id": f"{prefix}_second_front_stores", "priority": 110, "conditions": [{"type": "encounter_resolved", "placement_id": f"{prefix}_front_2"}], "effects": [{"type": "add_resources", "resources": {"gold": 900, "wood": 2, "ore": 2}}, {"type": "message", "text": "The second front yields stores for the exposed middle route."}]},
            {"id": f"{prefix}_doctrine_recorded", "priority": 100, "conditions": [{"type": "objective_met", "objective_id": f"{prefix}_claim_doctrine"}], "effects": [{"type": "add_resources", "resources": {"gold": 700}}, {"type": "message", "text": "The command landmark records its doctrine and the return route opens."}]},
            {"id": f"{prefix}_day_ten_reserve", "priority": 80, "conditions": [{"type": "day_at_least", "day": 10}, {"type": "objective_not_met", "objective_id": f"{prefix}_claim_doctrine"}], "effects": [{"type": "add_enemy_pressure", "faction_id": case["enemy_faction_id"], "amount": 3}, {"type": "town_add_recruits", "placement_id": f"{prefix}_home", "recruits": {stacks[2][0]: 2, stacks[3][0]: 1}}, {"type": "spawn_encounter", "placement": {"placement_id": f"{prefix}_late_reserve", "encounter_id": case["encounters"][3], "x": 16, "y": 10, "difficulty": "scripted", "spawned_by_faction_id": case["enemy_faction_id"], "days_active": 0, "arrived": False, "goal_distance": 9999}}, {"type": "message", "text": "The enemy town commits a reserve while the doctrine remains unclaimed."}]},
        ],
        "towns": [{"placement_id": f"{prefix}_home", "town_id": case["home_town_id"], "x": 0, "y": 6, "owner": "player", "built_buildings": ["building_market_square"]}, {"placement_id": f"{prefix}_enemy_town", "town_id": case["enemy_town_id"], "x": 17, "y": 6, "owner": "enemy"}],
        "enemy_factions": [{"faction_id": case["enemy_faction_id"], "label": case["enemy_label"], "pressure_per_day": 1, "pressure_per_enemy_town": 1, "raid_threshold": 9, "max_active_raids": 1, "raid_pillage_delay": 2, "raid_pillage": {"gold": 200}, "raid_encounter_ids": case["encounters"], "spawn_points": [{"x": 17, "y": 1}, {"x": 17, "y": 10}], "siege_target_placement_id": f"{prefix}_home", "siege_active_raid_threshold": 2, "siege_capture_progress": 2, "priority_target_placement_ids": [f"{prefix}_home", f"{prefix}_landmark"]}],
        "resource_nodes": [{"placement_id": f"{prefix}_wood_north", "site_id": "site_wood_wagon", "x": 1, "y": 0}, {"placement_id": f"{prefix}_ore_north", "site_id": "site_ore_crates", "x": 5, "y": 0}, {"placement_id": f"{prefix}_rare_north", "site_id": case["rare_site_id"], "x": 9, "y": 0}, {"placement_id": f"{prefix}_exchange", "site_id": "site_frontier_rare_exchange", "x": 14, "y": 0}, {"placement_id": f"{prefix}_wood_south", "site_id": "site_wood_wagon", "x": 2, "y": 11}, {"placement_id": f"{prefix}_ore_south", "site_id": "site_ore_crates", "x": 6, "y": 11}, {"placement_id": f"{prefix}_rare_south", "site_id": case["rare_site_id"], "x": 10, "y": 11}, {"placement_id": f"{prefix}_waystone", "site_id": "site_waystone_cache", "x": 14, "y": 11}, {"placement_id": f"{prefix}_mid_cache", "site_id": "site_waystone_cache", "x": 9, "y": 6}, {"placement_id": f"{prefix}_landmark", "site_id": case["site_id"], "x": 14, "y": 6, "guard_front_id": f"{prefix}_front_4"}],
        "artifact_nodes": [], "encounters": encounters, "content_status": "commander_doctrine_expedition_live", "content_batch_id": SLICE_ID, "scenario_family": "commander_doctrine_expedition", "deterministic_seed": case["seed"], "commander_doctrine_expedition": {"hero_id": case["hero_id"], "landmark_site_id": case["site_id"], "home_town_id": case["home_town_id"], "enemy_town_id": case["enemy_town_id"], "front_count": 4},
    }


def main() -> None:
    scenarios = base.load(CONTENT / "scenarios.json")
    groups = base.load(CONTENT / "army_groups.json")
    sites = base.load(CONTENT / "resource_sites.json")
    heroes = {row["id"]: row for row in base.load(CONTENT / "heroes.json")["items"]}
    art = base.load(ART_MANIFEST)
    atlas_sha, source_rows = render_art()
    for index, case in enumerate(CASES):
        hero = heroes[case["hero_id"]]
        army_id = f"army_{case['prefix']}_expedition_company"
        base.upsert(groups["items"], {"id": army_id, "name": f"{hero['name']} Doctrine Expedition Company", "faction_id": case["faction_id"], "stacks": [{"unit_id": unit_id, "count": count} for unit_id, count in STACKS[case["faction_id"]]], "content_status": "commander_doctrine_expedition_company_live", "content_batch_id": SLICE_ID})
        base.upsert(sites["items"], {"id": case["site_id"], "name": case["site_name"], "family": "scenario_objective", "action_label": case["action_label"], "summary": f"{case['site_name']} teaches {hero['name']} one durable command doctrine after its four-front route is opened.", "claim_rewards": {"experience": 250}, "hero_command_bonus": {case["command_key"]: 1}, "claim_flags": {f"{case['prefix']}_doctrine_landmark_claimed": True}, "runtime_boundary": {"status": "commander_doctrine_expedition_live", "live_reward_grants": True, "save_payload_required": True, "renderer_sprite_required": True, "pathing_runtime_adopted": True, "route_effect_runtime_adopted": False, "hero_progression_activation": True, "scenario_placement_migration": True}, "content_batch_id": SLICE_ID, "public_text": {"public_summary": case["description"], "no_internal_debug_score_fields": True, "large_text_panel_required": False}})
        base.upsert(scenarios["items"], scenario_record(case, hero["name"], army_id))
        art["object_assets"][case["asset_id"]] = {"path": ATLAS_RES, "atlas_region": [index * 48, 0, 48, 48], "atlas_size": [384, 48], "runtime_sha256": atlas_sha, "source_trimmed": source_rows[index]["source_path"], "source_generated": source_rows[index]["source_path"], "source_model": "built_in_imagegen_original_commander_doctrine_expeditions_atlas", "asset_policy": "original_generated_runtime_sprite_no_homm3_art_import", "distinct_sprite_assignment": True, "assigned_resource_site_id": case["site_id"], "assigned_hero_id": case["hero_id"], "presentation_role": case["site_id"].removeprefix("site_"), "accessible_description": case["description"]}
        art["resource_site_sprites"][case["site_id"]] = {"asset_id": case["asset_id"], "unclaimed_asset_id": case["asset_id"], "fit": f"Exact original {case['site_name']} remains visible before and after its one-time doctrine claim."}
    scenarios["player_facing_active_scenario_count"] = len(scenarios["items"])
    base.write_compact(CONTENT / "scenarios.json", scenarios)
    base.write_groups(CONTENT / "army_groups.json", groups)
    base.write_pretty(CONTENT / "resource_sites.json", sites)
    base.write_pretty(ART_MANIFEST, art)
    print(json.dumps({"slice_id": SLICE_ID, "scenario_count": len(scenarios["items"]), "army_group_count": len(groups["items"]), "resource_site_count": len(sites["items"]), "atlas_sha256": atlas_sha}, sort_keys=True))


if __name__ == "__main__":
    main()
