#!/usr/bin/env python3
"""Author twelve large Marchland grand-route operations and landmark art."""

from __future__ import annotations

import json
from pathlib import Path

from PIL import Image

import author_eight_commanders_proving_roads as base


ROOT = Path(__file__).resolve().parents[1]
CONTENT = ROOT / "content"
SOURCE_ROOT = ROOT / "art/overworld/source/generated/resource_sites/marchland_grand_route_operations_wave1"
ATLAS_PATH = ROOT / "art/overworld/runtime/objects/resource_sites/marchland_grand_route_operations_atlas.png"
ATLAS_RES = "res://art/overworld/runtime/objects/resource_sites/marchland_grand_route_operations_atlas.png"
SOURCE_RES = "res://art/overworld/source/generated/resource_sites/marchland_grand_route_operations_wave1"
ART_MANIFEST = ROOT / "art/overworld/manifest.json"
SLICE_ID = "content-twelve-marchland-grand-route-operations-10184"
GENERATOR_ROOT = Path("/root/.codex/generated_images/019fe72a-30b1-76f3-b911-385c4444bd16")


FACTIONS = {
    "ember": {"faction_id": "faction_embercourt", "home_town_id": "town_amberweir_granary", "forward_town_id": "town_cinderlock_bastion", "enemy_town_id": "town_nightglass_redoubt", "enemy_faction_id": "faction_mireclaw", "enemy_label": "Nightglass Drowned Ward", "rare_site_id": "site_embergrain_warm_granary", "rare_resource": "embergrain", "terrain": ("grass", "rough"), "stacks": [("unit_embercourt_fordhook_cadets", 90), ("unit_embercourt_lantern_sappers", 60), ("unit_embercourt_bargebow_crews", 36), ("unit_embercourt_amberweir_lockpike_wardens", 20), ("unit_embercourt_amberweir_sluicebrand_mangonels", 12)], "encounters": ["encounter_ghoul_grove", "encounter_reedbarrow_chain", "encounter_drum_circle", "encounter_mirror_causeway", "encounter_bone_ferry_watch", "encounter_nightglass_drowned_watch"]},
    "mire": {"faction_id": "faction_mireclaw", "home_town_id": "town_moonbite_reedshrine", "forward_town_id": "town_reedbarrow_ferry", "enemy_town_id": "town_rainwrit_bastion", "enemy_faction_id": "faction_embercourt", "enemy_label": "Rainwrit Charter Host", "rare_site_id": "site_peatwax_reed_yard", "rare_resource": "peatwax", "terrain": ("mire", "swamp"), "stacks": [("unit_mireclaw_reedsnare_kin", 90), ("unit_mireclaw_mudglass_slingers", 60), ("unit_mireclaw_bogplate_maulers", 36), ("unit_mireclaw_moonbite_votive_drummers", 20), ("unit_mireclaw_moonbite_mirehorn_breakers", 12)], "encounters": ["encounter_tarn_daybreak_hunt", "encounter_facetline_named_rival_company", "encounter_mill_levies", "encounter_horizon_rainwrit_charter_gate", "encounter_lockglass_citation_field", "encounter_pikeward_named_rival_company"]},
    "sun": {"faction_id": "faction_sunvault", "home_town_id": "town_splitprism_duelcourt", "forward_town_id": "town_halo_spire", "enemy_town_id": "town_crownroot_refuge", "enemy_faction_id": "faction_thornwake", "enemy_label": "Crownroot Shade Jury", "rare_site_id": "site_aetherglass_lens_house", "rare_resource": "aetherglass", "terrain": ("sand", "grass"), "stacks": [("unit_sunvault_shard_wardens", 90), ("unit_sunvault_prism_adepts", 60), ("unit_sunvault_mirror_duelists", 36), ("unit_sunvault_splitprism_parallax_fencers", 20), ("unit_sunvault_splitprism_heliograph_ballistae", 12)], "encounters": ["encounter_dovan_greenline_survey", "encounter_third_hearths_canopy_breachers", "encounter_horizon_crownroot_oathseed_ring", "encounter_horizon_court_crownroot_rootglass_jury", "encounter_rootshade_facet_breaker", "encounter_greenbarrow_named_rival_company"]},
    "thorn": {"faction_id": "faction_thornwake", "home_town_id": "town_woundroot_hearthgrove", "forward_town_id": "town_thornwake_graftroot_caravan", "enemy_town_id": "town_cindercoil_foundry", "enemy_faction_id": "faction_brasshollow", "enemy_label": "Cindercoil Furnace Court", "rare_site_id": "site_verdant_graft_nursery", "rare_resource": "verdant_grafts", "terrain": ("forest", "grass"), "stacks": [("unit_thornwake_seedcutters", 90), ("unit_thornwake_bramblekite_needlers", 60), ("unit_thornwake_seedshield_wardens", 36), ("unit_thornwake_woundroot_hearthseed_slingers", 20), ("unit_thornwake_woundroot_rootmaul_behemoths", 12)], "encounters": ["encounter_mirrorstep_redline_calibrators", "encounter_halen_furnace_railbreak", "encounter_brakka_hive_foreclosure", "encounter_thalen_foundry_eclipse", "encounter_third_hearths_redline_lancers", "encounter_bellfounder_named_rival_company"]},
    "brass": {"faction_id": "faction_brasshollow", "home_town_id": "town_whitegauge_calibration_yard", "forward_town_id": "town_brasshollow_clauseworks_depot", "enemy_town_id": "town_pale_sounding_harbor", "enemy_faction_id": "faction_veilmourn", "enemy_label": "Pale Sounding Tide Court", "rare_site_id": "site_brass_scrip_mint", "rare_resource": "brass_scrip", "terrain": ("rough", "lava"), "stacks": [("unit_brasshollow_scrip_haulers", 90), ("unit_brasshollow_quenchspool_slingers", 60), ("unit_brasshollow_gaugefire_arbalists", 36), ("unit_brasshollow_whitegauge_datum_lancers", 20), ("unit_brasshollow_whitegauge_datum_breach_cannons", 12)], "encounters": ["encounter_tollglass_drowned_tally", "encounter_roadward_lodge_watch", "encounter_reedbarge_mooring_watch", "encounter_dustjack_yard_watch", "encounter_frostbeacon_bothy_watch", "encounter_orchard_levy_watch"]},
    "veil": {"faction_id": "faction_veilmourn", "home_town_id": "town_dreamwake_oracle_harbor", "forward_town_id": "town_veilmourn_bellwake_harbor", "enemy_town_id": "town_highwater_keep", "enemy_faction_id": "faction_embercourt", "enemy_label": "Highwater Ember Patrol", "rare_site_id": "site_memory_salt_pan", "rare_resource": "memory_salt", "terrain": ("snow", "mire"), "stacks": [("unit_veilmourn_bellwake_oars", 90), ("unit_veilmourn_mourning_lanterns", 60), ("unit_veilmourn_maskglass_corsairs", 36), ("unit_veilmourn_dreamwake_tideglass_oracles", 20), ("unit_veilmourn_dreamwake_foganchor_colossi", 12)], "encounters": ["encounter_nix_reedflame_vigil", "encounter_merek_cinder_writ", "encounter_three_banner_beaconline_writguard", "encounter_mistcorsair_graftwake_cordon", "encounter_morwen_rootwake_vigil", "encounter_brambleback_crown_watch"]},
}


CASES = [
    {"key": "ember", "prefix": "cinderquill", "scenario_id": "cinderquill-grand-route-kiln", "scenario_name": "Cinderquill Grand-Route Kiln", "hero_id": "hero_embercourt_orra_cinderquill", "site_id": "site_cinderquill_route_kiln_desk", "site_name": "Cinderquill Route-Kiln Desk", "asset_id": "resource_site_route_cinderquill_kiln_desk", "source_name": "cinderquill_route_kiln_desk_source.png", "generation_original": "exec-4f344f04-3001-46c3-afd8-a927afa9a5d6.png", "action_label": "Seal the Route-Kiln Ledger", "seed": 54300, "width": 24, "height": 14, "description": "A brick route kiln supports blank charter slates beneath a feather-shaped iron chimney and curled brass paper rail."},
    {"key": "ember", "prefix": "sevenlock", "scenario_id": "lockmaster-seven-lock-march", "scenario_name": "Lockmaster Seven-Lock March", "hero_id": "hero_embercourt_saren_lockmaster", "site_id": "site_lockmaster_seven_lock_march_gate", "site_name": "Lockmaster Seven-Lock March Gate", "asset_id": "resource_site_route_lockmaster_seven_lock_gate", "source_name": "lockmaster_seven_lock_march_gate_source.png", "generation_original": "exec-789e52a3-d668-49be-90ee-18bab86c76f6.png", "action_label": "Open the Seven-Lock Gate", "seed": 54400, "width": 24, "height": 16, "description": "A narrow river gate carries seven visibly different locks, a broken counterweight, chain loops, and one hooded lantern."},
    {"key": "mire", "prefix": "chainboom", "scenario_id": "chainboom-grand-route-breach", "scenario_name": "Chainboom Grand-Route Breach", "hero_id": "hero_mireclaw_kessa_chainboom", "site_id": "site_chainboom_reed_breach_drum", "site_name": "Chainboom Reed-Breach Drum", "asset_id": "resource_site_route_chainboom_breach_drum", "source_name": "chainboom_reed_breach_drum_source.png", "generation_original": "exec-29c93eea-e1d1-4485-a5ce-8943cc427fc4.png", "action_label": "Sound the Reed-Breach", "seed": 54500, "width": 24, "height": 14, "description": "A chained marsh drum bears a split reed-boom arm, bone beaters, hooked float cages, and a muddy keel foot."},
    {"key": "mire", "prefix": "floodledger", "scenario_id": "reedscript-flood-ledger-route", "scenario_name": "Reedscript Flood-Ledger Route", "hero_id": "hero_mireclaw_pell_reedscript", "site_id": "site_reedscript_flood_ledger_stand", "site_name": "Reedscript Flood-Ledger Stand", "asset_id": "resource_site_route_reedscript_flood_ledger", "source_name": "reedscript_flood_ledger_stand_source.png", "generation_original": "exec-4562bb86-8543-4f30-86ce-fd842cb1a6ee.png", "action_label": "Read the Flood Ledger", "seed": 54600, "width": 24, "height": 16, "description": "A crooked reed lectern holds blank wax leaves beside a crescent water gauge, clay plumb, and flood markers."},
    {"key": "sun", "prefix": "dawnchime", "scenario_id": "daynote-dawn-chime-route", "scenario_name": "Daynote Dawn-Chime Route", "hero_id": "hero_sunvault_essa_daynote", "site_id": "site_daynote_dawn_chime_array", "site_name": "Daynote Dawn-Chime Array", "asset_id": "resource_site_route_daynote_dawn_chime", "source_name": "daynote_dawn_chime_array_source.png", "generation_original": "exec-51ad8acf-54df-4fa9-a116-be9e98834f0f.png", "action_label": "Ring the Dawn-Chime Array", "seed": 54700, "width": 24, "height": 14, "description": "An asymmetric radiant frame carries five crystal chimes, a split sundial, diagonal striker, and prism plumbs."},
    {"key": "sun", "prefix": "prismrank", "scenario_id": "glassmarshal-prism-rank-march", "scenario_name": "Glassmarshal Prism-Rank March", "hero_id": "hero_sunvault_ilyr_glassmarshal", "site_id": "site_glassmarshal_prism_rank_beacon", "site_name": "Glassmarshal Prism-Rank Beacon", "asset_id": "resource_site_route_glassmarshal_prism_beacon", "source_name": "glassmarshal_prism_rank_beacon_source.png", "generation_original": "exec-27ecd7fd-92c4-4e14-bb3c-2130620d4b68.png", "action_label": "Align the Prism Ranks", "seed": 54800, "width": 24, "height": 16, "description": "Four staggered prism blades rise from a stepped base above a mirrored rail, crossing rods, and diamond lens."},
    {"key": "thorn", "prefix": "rootomen", "scenario_id": "graftsibyl-root-omen-march", "scenario_name": "Graft-Sibyl Root-Omen March", "hero_id": "hero_thornwake_nara_graftsibyl", "site_id": "site_graftsibyl_root_omen_frame", "site_name": "Graft-Sibyl Root-Omen Frame", "asset_id": "resource_site_route_graftsibyl_root_omen", "source_name": "graftsibyl_root_omen_frame_source.png", "generation_original": "exec-6233c077-7e0e-4df7-a4ac-ce952e9b8f94.png", "action_label": "Read the Root Omen", "seed": 54900, "width": 24, "height": 14, "description": "A living-root frame surrounds an empty seed cradle with leaf mirrors, a bark pointer, graft vials, and clawed feet."},
    {"key": "thorn", "prefix": "windseed", "scenario_id": "seedseer-windseed-route", "scenario_name": "Seedseer Windseed Route", "hero_id": "hero_thornwake_veyra_seedseer", "site_id": "site_seedseer_windseed_orrery", "site_name": "Seedseer Windseed Orrery", "asset_id": "resource_site_route_seedseer_windseed_orrery", "source_name": "seedseer_windseed_orrery_source.png", "generation_original": "exec-fc9c5491-46e6-4689-9e20-216cc674ecbe.png", "action_label": "Turn the Windseed Orrery", "seed": 55000, "width": 24, "height": 16, "description": "Three unequal seed pods circle on branch orbits above a leaf vane, root plumb, antler braces, and vine tripod."},
    {"key": "brass", "prefix": "roadbell", "scenario_id": "bellfounder-road-bell-march", "scenario_name": "Bellfounder Road-Bell March", "hero_id": "hero_brasshollow_oren_bellfounder", "site_id": "site_bellfounder_road_bell_gantry", "site_name": "Bellfounder Road-Bell Gantry", "asset_id": "resource_site_route_bellfounder_road_bell", "source_name": "bellfounder_road_bell_gantry_source.png", "generation_original": "exec-294fad39-14d9-48ad-b820-751b1f9c2191.png", "action_label": "Cast the Road Bell", "seed": 55100, "width": 24, "height": 14, "description": "A mobile casting gantry suspends an unfinished faceted bell beside a pouring arm, mold clamps, and warning hammer."},
    {"key": "brass", "prefix": "cinderscale", "scenario_id": "ashmeter-cinder-scale-route", "scenario_name": "Ashmeter Cinder-Scale Route", "hero_id": "hero_brasshollow_pava_ashmeter", "site_id": "site_ashmeter_cinder_scale_station", "site_name": "Ashmeter Cinder-Scale Station", "asset_id": "resource_site_route_ashmeter_cinder_scale", "source_name": "ashmeter_cinder_scale_station_source.png", "generation_original": "exec-d0e33f53-e5cc-4a81-bbf9-1060acda1800.png", "action_label": "Balance the Cinder Scale", "seed": 55200, "width": 24, "height": 16, "description": "A low assay station carries a tilted balance scale, ash cups, calibration arc, chain weights, and furnace pot."},
    {"key": "veil", "prefix": "blankbell", "scenario_id": "vowless-blank-bell-route", "scenario_name": "Vowless Blank-Bell Route", "hero_id": "hero_veilmourn_nacre_vowless", "site_id": "site_vowless_blank_bell_mast", "site_name": "Vowless Blank-Bell Mast", "asset_id": "resource_site_route_vowless_blank_bell", "source_name": "vowless_blank_bell_mast_source.png", "generation_original": "exec-cc1eb9e4-0ec5-474f-9535-5f0b18de8ce6.png", "action_label": "Raise the Blank Bell", "seed": 55300, "width": 24, "height": 14, "description": "A bare harbor mast raises a broad white clapperless bell with a crescent sail rib, pendants, and anchor hook."},
    {"key": "veil", "prefix": "crosswind", "scenario_id": "vanehook-crosswind-mooring", "scenario_name": "Vanehook Crosswind Mooring", "hero_id": "hero_veilmourn_ruln_vanehook", "site_id": "site_vanehook_crosswind_mooring", "site_name": "Vanehook Crosswind Mooring", "asset_id": "resource_site_route_vanehook_crosswind_mooring", "source_name": "vanehook_crosswind_mooring_source.png", "generation_original": "exec-1afcd48d-50b2-4e66-9b88-3b675fa95826.png", "action_label": "Set the Crosswind Mooring", "seed": 55400, "width": 24, "height": 16, "description": "A crooked harbor mooring bears opposing wind fins, a rope drum, direction discs, storm lantern, and split anchor base."},
]


def terrain_map(primary: str, secondary: str, seed: int, width: int, height: int) -> list[list[str]]:
    return [[secondary if (x * 7 + y * 11 + seed) % 23 in (0, 1, 2, 3, 4) else primary for x in range(width)] for y in range(height)]


def render_art() -> tuple[str, list[dict]]:
    ATLAS_PATH.parent.mkdir(parents=True, exist_ok=True)
    atlas = Image.new("RGBA", (576, 48), (0, 0, 0, 0))
    rows = []
    for index, case in enumerate(CASES):
        source = SOURCE_ROOT / case["source_name"]
        atlas.alpha_composite(base.transparent_frame(source), (index * 48, 0))
        prompt = f"Use case: stylized-concept; Asset type: production 2D fantasy strategy-game overworld command landmark source; Primary request: Create {case['site_name']} for the original Aurelion Reach setting; Scene/backdrop: genuinely transparent background; Subject and readable identity: {case['description']}; Style/medium: polished hand-painted original fantasy game landmark art; Composition/framing: isolated high three-quarter view, centered with padding, strong non-color silhouette readable at 48x48; Constraints: one landmark only; preserved alpha; no ground, scenery, characters, text, letters, numbers, logos, watermark, border, frame, cast shadow, or copied franchise design."
        rows.append({"site_id": case["site_id"], "hero_id": case["hero_id"], "asset_id": case["asset_id"], "source_path": f"{SOURCE_RES}/{case['source_name']}", "source_sha256": base.sha256(source), "generation_original": str(GENERATOR_ROOT / case["generation_original"]), "atlas_region": [index * 48, 0, 48, 48], "prompt": prompt, "accessible_description": case["description"]})
    atlas.save(ATLAS_PATH, optimize=True, compress_level=9)
    atlas_sha = base.sha256(ATLAS_PATH)
    base.write_pretty(SOURCE_ROOT / "manifest.json", {"schema_id": "twelve_marchland_grand_route_operations_art_v1", "content_batch_id": SLICE_ID, "generation_mode": "built_in_imagegen", "source_model": "built_in_imagegen_original_marchland_grand_route_operations_atlas", "prompt_set_summary": "Twelve transparent original route-command landmarks for twelve underused heroes, built around strong faction-readable silhouettes at 48px.", "runtime_atlas": ATLAS_RES, "runtime_atlas_size": [576, 48], "runtime_atlas_sha256": atlas_sha, "source_package_policy": "retained_for_provenance_excluded_from_linux_and_windows_exports", "items": rows})
    return atlas_sha, rows


def scenario_record(case: dict, hero_name: str, army_id: str) -> dict:
    faction = FACTIONS[case["key"]]
    prefix, width, height = case["prefix"], case["width"], case["height"]
    stacks = faction["stacks"]
    coords = [(5, 2), (7, height - 3), (10, 4), (14, height - 4), (18, 3), (20, height - 3)]
    encounters = [{"placement_id": f"{prefix}_front_{i}", "encounter_id": encounter_id, "x": xy[0], "y": xy[1], "difficulty": "medium", "combat_seed": case["seed"] + i, "prefer_identity_landmark": True, "guardian_role": "marchland_grand_route_front"} for i, (encounter_id, xy) in enumerate(zip(faction["encounters"], coords), start=1)]
    victory = [{"id": f"{prefix}_hold_retinue", "label": f"Keep both {hero_name} Marchland companies in the route host", "type": "hero_army_meets_requirements", "hero_id": case["hero_id"], "requirements": [{"unit_id": stacks[3][0], "minimum_count": 1}, {"unit_id": stacks[4][0], "minimum_count": 1}]}, {"id": f"{prefix}_claim_command", "label": f"Claim {case['site_name']}", "type": "flag_true", "flag": f"{prefix}_route_command_claimed"}]
    victory.extend({"id": f"{prefix}_clear_front_{i}", "label": f"Resolve grand-route front {i}", "type": "encounter_resolved", "placement_id": f"{prefix}_front_{i}"} for i in range(1, 7))
    middle_y, last_y = height // 2, height - 1
    node_specs = [("wood_nw", "site_wood_wagon", 1, 0), ("ore_nw", "site_ore_crates", 4, 0), ("rare_n", faction["rare_site_id"], 8, 0), ("exchange_n", "site_frontier_rare_exchange", 13, 0), ("waystone_n", "site_waystone_cache", 18, 0), ("ore_ne", "site_ore_crates", 22, 0), ("wood_sw", "site_wood_wagon", 2, last_y), ("ore_sw", "site_ore_crates", 6, last_y), ("rare_s", faction["rare_site_id"], 10, last_y), ("exchange_s", "site_frontier_rare_exchange", 15, last_y), ("waystone_s", "site_waystone_cache", 19, last_y), ("wood_se", "site_wood_wagon", 22, last_y), ("mid_cache", "site_waystone_cache", 11, middle_y), ("landmark", case["site_id"], 20, middle_y)]
    if height == 16:
        node_specs.extend([("west_stores", "site_wood_wagon", 3, middle_y - 3), ("east_stores", "site_ore_crates", 21, middle_y + 3)])
    resource_nodes = [{"placement_id": f"{prefix}_{name}", "site_id": site_id, "x": x, "y": y, **({"guard_front_id": f"{prefix}_front_6"} if name == "landmark" else {})} for name, site_id, x, y in node_specs]
    deadline = 28 if height == 14 else 32
    return {
        "id": case["scenario_id"], "name": case["scenario_name"], "selection": {"summary": f"Lead {hero_name}'s five-stack host across six real battle fronts and claim {case['site_name']} before Day {deadline}.", "recommended_difficulty": "normal", "map_size_label": f"Grand-Route Operation ({width}x{height})", "player_summary": f"{hero_name} commands the complete local Marchland line through two friendly towns.", "enemy_summary": f"{faction['enemy_label']} hold six distinct fronts, an enemy town, and a late reserve.", "availability": {"campaign": False, "skirmish": True}},
        "map_size": {"width": width, "height": height}, "player_faction_id": faction["faction_id"], "player_army_id": army_id, "hero_id": case["hero_id"], "starting_resources": {"gold": 14000, "wood": 18, "ore": 18, "embergrain": 5, "aetherglass": 5, "peatwax": 5, "verdant_grafts": 5, "brass_scrip": 5, "memory_salt": 5}, "map": terrain_map(*faction["terrain"], case["seed"], width, height), "start": {"x": 1, "y": middle_y}, "hero_starts": [case["hero_id"]],
        "objectives": {"victory_text": f"{hero_name} has opened every grand-route front and established route command.", "defeat_text": f"A friendly town falls, pressure closes the march, or Day {deadline} arrives before command is established.", "victory": victory, "defeat": [{"id": f"{prefix}_lose_home", "label": "Keep the Marchland home town", "type": "town_not_owned_by_player", "placement_id": f"{prefix}_home"}, {"id": f"{prefix}_lose_forward", "label": "Keep the forward town", "type": "town_not_owned_by_player", "placement_id": f"{prefix}_forward"}, {"id": f"{prefix}_pressure", "label": "Keep route pressure below 40", "type": "enemy_pressure_at_least", "faction_id": faction["enemy_faction_id"], "threshold": 40}, {"id": f"{prefix}_deadline", "label": f"Complete the operation before Day {deadline}", "type": "day_at_least", "day": deadline}]},
        "script_hooks": [
            {"id": f"{prefix}_day_two_stores", "priority": 140, "conditions": [{"type": "day_at_least", "day": 2}, {"type": "town_owned_by_player", "placement_id": f"{prefix}_home"}], "effects": [{"type": "add_resources", "resources": {"gold": 3200, "wood": 3, "ore": 3}}, {"type": "town_add_recruits", "placement_id": f"{prefix}_forward", "recruits": {stacks[0][0]: 6, stacks[1][0]: 4}}, {"type": "message", "text": "The two Marchland towns open their grand-route stores."}]},
            {"id": f"{prefix}_first_front_relief", "priority": 130, "conditions": [{"type": "encounter_resolved", "placement_id": f"{prefix}_front_1"}], "effects": [{"type": "add_army_units", "units": {stacks[3][0]: 2, stacks[0][0]: 5}}, {"type": "message", "text": "Freed route hands reinforce the local warworks line."}]},
            {"id": f"{prefix}_second_front_stores", "priority": 120, "conditions": [{"type": "encounter_resolved", "placement_id": f"{prefix}_front_2"}], "effects": [{"type": "add_resources", "resources": {"gold": 900, "wood": 2, "ore": 2}}, {"type": "message", "text": "The second front yields the route's field stores."}]},
            {"id": f"{prefix}_third_front_rare", "priority": 110, "conditions": [{"type": "encounter_resolved", "placement_id": f"{prefix}_front_3"}], "effects": [{"type": "add_resources", "resources": {faction["rare_resource"]: 1}}, {"type": "message", "text": "The third front releases a sealed strategic reserve."}]},
            {"id": f"{prefix}_command_recorded", "priority": 100, "conditions": [{"type": "objective_met", "objective_id": f"{prefix}_claim_command"}], "effects": [{"type": "add_resources", "resources": {"gold": 700}}, {"type": "message", "text": "The landmark records the opened grand route."}]},
            {"id": f"{prefix}_day_fourteen_reserve", "priority": 80, "conditions": [{"type": "day_at_least", "day": 14}, {"type": "objective_not_met", "objective_id": f"{prefix}_claim_command"}], "effects": [{"type": "add_enemy_pressure", "faction_id": faction["enemy_faction_id"], "amount": 4}, {"type": "town_add_recruits", "placement_id": f"{prefix}_forward", "recruits": {stacks[2][0]: 2, stacks[3][0]: 1}}, {"type": "spawn_encounter", "placement": {"placement_id": f"{prefix}_late_reserve", "encounter_id": faction["encounters"][5], "x": 22, "y": height - 2, "difficulty": "scripted", "spawned_by_faction_id": faction["enemy_faction_id"], "days_active": 0, "arrived": False, "goal_distance": 9999}}, {"type": "message", "text": "The enemy town commits a reserve while route command remains unclaimed."}]},
        ],
        "towns": [{"placement_id": f"{prefix}_home", "town_id": faction["home_town_id"], "x": 0, "y": middle_y, "owner": "player", "built_buildings": ["building_market_square"]}, {"placement_id": f"{prefix}_forward", "town_id": faction["forward_town_id"], "x": 12, "y": height - 2, "owner": "player", "built_buildings": ["building_market_square"]}, {"placement_id": f"{prefix}_enemy_town", "town_id": faction["enemy_town_id"], "x": 23, "y": middle_y, "owner": "enemy"}],
        "enemy_factions": [{"faction_id": faction["enemy_faction_id"], "label": faction["enemy_label"], "pressure_per_day": 1, "pressure_per_enemy_town": 1, "raid_threshold": 12, "max_active_raids": 1, "raid_pillage_delay": 2, "raid_pillage": {"gold": 250}, "raid_encounter_ids": faction["encounters"], "spawn_points": [{"x": 23, "y": 1}, {"x": 23, "y": height - 2}], "siege_target_placement_id": f"{prefix}_forward", "siege_active_raid_threshold": 2, "siege_capture_progress": 2, "priority_target_placement_ids": [f"{prefix}_forward", f"{prefix}_home", f"{prefix}_landmark"]}],
        "resource_nodes": resource_nodes, "artifact_nodes": [], "encounters": encounters, "content_status": "marchland_grand_route_operation_live", "content_batch_id": SLICE_ID, "scenario_family": "marchland_grand_route_operation", "deterministic_seed": case["seed"], "marchland_grand_route_operation": {"hero_id": case["hero_id"], "landmark_site_id": case["site_id"], "home_town_id": faction["home_town_id"], "forward_town_id": faction["forward_town_id"], "enemy_town_id": faction["enemy_town_id"], "front_count": 6, "local_unit_ids": [stacks[3][0], stacks[4][0]]},
    }


def main() -> None:
    scenarios = base.load(CONTENT / "scenarios.json")
    groups = base.load(CONTENT / "army_groups.json")
    sites = base.load(CONTENT / "resource_sites.json")
    heroes = {row["id"]: row for row in base.load(CONTENT / "heroes.json")["items"]}
    art = base.load(ART_MANIFEST)
    atlas_sha, source_rows = render_art()
    for index, case in enumerate(CASES):
        faction = FACTIONS[case["key"]]
        hero = heroes[case["hero_id"]]
        army_id = f"army_{case['prefix']}_grand_route_host"
        base.upsert(groups["items"], {"id": army_id, "name": f"{hero['name']} Grand-Route Host", "faction_id": faction["faction_id"], "stacks": [{"unit_id": unit_id, "count": count} for unit_id, count in faction["stacks"]], "content_status": "marchland_grand_route_host_live", "content_batch_id": SLICE_ID})
        base.upsert(sites["items"], {"id": case["site_id"], "name": case["site_name"], "family": "scenario_objective", "action_label": case["action_label"], "summary": f"{case['site_name']} establishes {hero['name']}'s command after six battle fronts are opened.", "claim_rewards": {"gold": 800, faction["rare_resource"]: 2, "experience": 250}, "claim_recruits": {faction["stacks"][3][0]: 3, faction["stacks"][4][0]: 1}, "claim_flags": {f"{case['prefix']}_route_command_claimed": True}, "runtime_boundary": {"status": "marchland_grand_route_operation_live", "live_reward_grants": True, "save_payload_required": True, "renderer_sprite_required": True, "pathing_runtime_adopted": True, "route_effect_runtime_adopted": False, "hero_progression_activation": True, "scenario_placement_migration": True}, "content_batch_id": SLICE_ID, "public_text": {"public_summary": case["description"], "no_internal_debug_score_fields": True, "large_text_panel_required": False}})
        base.upsert(scenarios["items"], scenario_record(case, hero["name"], army_id))
        art["object_assets"][case["asset_id"]] = {"path": ATLAS_RES, "atlas_region": [index * 48, 0, 48, 48], "atlas_size": [576, 48], "runtime_sha256": atlas_sha, "source_trimmed": source_rows[index]["source_path"], "source_generated": source_rows[index]["source_path"], "source_model": "built_in_imagegen_original_marchland_grand_route_operations_atlas", "asset_policy": "original_generated_runtime_sprite_no_homm3_art_import", "distinct_sprite_assignment": True, "assigned_resource_site_id": case["site_id"], "assigned_hero_id": case["hero_id"], "presentation_role": case["site_id"].removeprefix("site_"), "accessible_description": case["description"]}
        art["resource_site_sprites"][case["site_id"]] = {"asset_id": case["asset_id"], "unclaimed_asset_id": case["asset_id"], "fit": f"Exact original {case['site_name']} remains visible before and after its one-time route-command claim."}
    scenarios["player_facing_active_scenario_count"] = len(scenarios["items"])
    base.write_compact(CONTENT / "scenarios.json", scenarios)
    base.write_groups(CONTENT / "army_groups.json", groups)
    base.write_pretty(CONTENT / "resource_sites.json", sites)
    base.write_pretty(ART_MANIFEST, art)
    print(json.dumps({"slice_id": SLICE_ID, "scenario_count": len(scenarios["items"]), "army_group_count": len(groups["items"]), "resource_site_count": len(sites["items"]), "atlas_sha256": atlas_sha}, sort_keys=True))


if __name__ == "__main__":
    main()
