#!/usr/bin/env python3
"""Emit the canonical H3MapEd RMG recovery manifest.

The manifest is intentionally about reverse-engineering state, not final map
counts. It records the binary identity, required function addresses, generated
cell layout, and checkpoint targets that must be proven before native behavior
changes are allowed.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
from pathlib import Path
from typing import Any


DEFAULT_H3MAPED = Path(".artifacts/rmg_20seed_2p_small_h3maped_20260605/small_2p_seed_58_manual20/runtime/h3maped.exe")
DEFAULT_OUT = Path(".artifacts/rmg_recovery/h3maped_recovery_manifest.json")

FUNCTIONS: list[dict[str, Any]] = [
    {
        "address": "0x499e65",
        "name": "generated_cell_constructor",
        "status": "recovered_static_ghidra",
        "writes": ["cell+0x00 byte argument", "cell+0x04/+0x08/+0x0c zero", "calls 0x499ea3"],
    },
    {
        "address": "0x49a072",
        "name": "generated_cell_grid_reset",
        "status": "recovered_static_ghidra",
        "reads": ["grid+0x08 cell buffer", "grid+0x0c width", "grid+0x10 height", "grid+0x14 level count"],
        "writes": ["calls 0x499ea3 for width*height*levels cells with stride 0x30"],
        "ghidra_dump": "Focused dump .artifacts/rmg_recovery/ghidra_cell_reset_flag_helper_dump recovers this as the full-grid reset loop that walks the wrapper cell buffer by stride 0x30 and delegates each record to 0x499ea3.",
    },
    {
        "address": "0x499ea3",
        "name": "generated_cell_initializer",
        "status": "recovered_static_ghidra",
        "writes": [
            "cell+0x10 = 0xffffffff",
            "cell+0x1c = 0x7fbc7fbc",
            "cell+0x20 = 0xffff7fbc",
            "cell+0x24 = (old & 0xc0000548) | 0x00000548",
            "cell+0x28 = (old & bit24) | bit25 | bit27",
            "cell+0x2c clears bit0",
        ],
        "reason": "This is the source prefill; the bit27 reduction before 0x4a4c8e is caused by later callers of 0x49a932/0x49aa63, not by a different initializer.",
        "ghidra_dump": "Focused dump .artifacts/rmg_recovery/ghidra_cell_record_reset_leaf_dump recovers the generated-cell initializer leaf and its exact field writes.",
    },
    {
        "address": "0x49a1d8",
        "name": "generated_cell_validity_predicate",
        "status": "recovered_static_ghidra",
        "returns_true_when": ["cell+0x2b has bit 0x02 set", "terrain id (cell+0x24 & 0x3f) is not 9"],
        "ghidra_dump": "Focused dump .artifacts/rmg_recovery/ghidra_cell_reset_flag_helper_dump recovers this predicate as a bit0x02 check on cell+0x2b followed by a terrain-id-not-9 check on cell+0x24 low six bits.",
    },
    {
        "address": "0x49a85d",
        "name": "generated_cell_bit27_neighborhood_stamp",
        "status": "recovered_static_ghidra",
        "writes": [
            "calls 0x49a932(true) for the center cell",
            "calls 0x49a932(true) for every cell in clipped [x-1,x+2) by [y-1,y+2) neighborhood on the same level",
        ],
        "coordinate_formula": "cell = grid+0x08 + 0x30 * (((level * grid_height) + y) * grid_width + x)",
    },
    {
        "address": "0x49a932",
        "name": "generated_cell_occupied_bit_writer",
        "status": "recovered_static_ghidra_hot_helper",
        "writes": ["when cell+0x2c bit0 clear: arg false clears bit27", "arg true sets bit27 then clears bit26"],
        "runtime_trace": "Direct seed58 helper tracing is intentionally bounded because repeated 0x49a85d stamps make 0x49a932 too hot; caller-side traces now explain the pre-0x4a4c8e bit27 surface.",
        "ghidra_dump": "Focused dump .artifacts/rmg_recovery/ghidra_cell_reset_flag_helper_dump confirms cell+0x2c bit0 suppresses mutation; otherwise false clears bit27, while true sets bit27 and clears bit26.",
    },
    {
        "address": "0x49aa63",
        "name": "generated_cell_decor_candidate_writer",
        "status": "recovered_static_and_seed58_pre_0x4a4c8e_runtime",
        "writes": ["when cell+0x2c bit0 clear: arg false clears bit26", "arg true sets bit26 then clears bit27"],
        "runtime_trace": "seed58_interactive_49aa63_to_4a4c8e shows 490 calls, all arg true, 490 unique generated-cell flats, then 0x4a4c8e. This matches the seed-58 pre-0x4a4c8e bit26 count.",
        "ghidra_dump": "Focused dump .artifacts/rmg_recovery/ghidra_cell_reset_flag_helper_dump confirms cell+0x2c bit0 suppresses mutation; otherwise false clears bit26, while true sets bit26 and clears bit27.",
    },
    {
        "address": "0x49a962",
        "name": "generated_cell_bit26_center_and_bit27_neighborhood_clear",
        "status": "recovered_static_and_seed58_pre_0x4a4c8e_runtime_replay",
        "writes": [
            "calls 0x49aa63(true) for the center cell",
            "for the clipped 3x3 neighborhood, calls 0x49a932(false) only when bit22 is clear, 0x49a1d8 is true, and terrain id is not 8",
        ],
        "coordinate_formula": "cell = grid+0x08 + 0x30 * (((level * grid_height) + y) * grid_width + x)",
        "runtime_trace": "seed58_interactive_49a962_to_4a4c8e_lite records 490 calls before 0x4a4c8e; replaying its clear rule leaves exactly the 407 dumped bit27 cells.",
    },
    {
        "address": "0x49acf6",
        "name": "generated_cell_terrain_art_and_flag_writer",
        "status": "recovered_static_ghidra",
        "writes": [
            "cell+0x24 = (old & 0xffffc000) | (terrain_arg & 0x3f) | ((arg2 & 0xff) << 6)",
            "cell+0x28 = (old & 0xfffe7fff) | (((arg3 & 1) | ((arg4 & 1) << 1)) << 15)",
        ],
        "callers": ["0x49ce64 full-grid loop after 0x49a072 reset", "0x4af463", "0x49acee local/internal path"],
        "ghidra_dump": "Focused dump .artifacts/rmg_recovery/ghidra_cell_reset_flag_helper_dump recovers terrain/art packing into cell+0x24 and two private bits packed into cell+0x28 bits 15..16.",
    },
    {
        "address": "0x4a59e2",
        "name": "generated_cell_projection_field_packer",
        "status": "recovered_static_contract",
        "reads": [
            "generated-cell pointer in ecx",
            "stack+0x04 high-word projection/local argument",
            "stack+0x08 direction/order argument masked to three bits",
            "stack+0x0c owner/source byte argument",
        ],
        "writes": [
            "writes stack+0x04 into the high word of cell+0x1c while preserving the low word",
            "writes (stack+0x08 & 7) into cell+0x28 bits 12..14 while preserving the other bits",
            "writes stack+0x0c into byte3 of cell+0x20 while preserving the lower 24 bits",
        ],
        "callers": ["0x4a5767"],
        "ghidra_dump": "Focused dump .artifacts/rmg_recovery/ghidra_cell_reset_flag_helper_dump recovers this helper directly. It is the only direct caller-visible 0x4a59e2 contract and is used by 0x4a5767 during generated-cell normalization.",
    },
    {
        "address": "0x49abd6",
        "name": "object_mask_stamp_generated_cell_mutator",
        "status": "recovered_static_and_seed58_body_cell_trace",
        "writes": ["cell+0x28 bit22", "cell+0x28 bit25", "cell+0x28 bit27 via 0x49a932"],
        "runtime_trace": "seed58_interactive_49abd6_to_4a8c15 records five object-footprint calls; seed58_interactive_49abd6_body_cells_to_4a8c15 records five 0x49ac6b body-cell writes at flats 184, 666, 604, 975, and 1059.",
    },
    {
        "address": "0x49d2c7",
        "name": "coord12_triple_store",
        "status": "recovered_static_contract",
        "reads": [
            "destination pointer in ecx",
            "coordinate dword 0 at stack+0x04",
            "coordinate dword 1 at stack+0x08",
            "coordinate dword 2 at stack+0x0c",
        ],
        "writes": [
            "writes stack+0x04 to destination+0x00",
            "writes stack+0x08 to destination+0x04",
            "writes stack+0x0c to destination+0x08",
            "returns the destination pointer in eax",
        ],
        "callers": ["0x49cf34", "0x4aa603", "0x4aa3e9", "0x4a79a3", "0x4ab6ac", "0x4aba05", "0x4abd5f"],
        "ghidra_dump": "Focused dump .artifacts/rmg_recovery/ghidra_reward_guard_probe_helper_dump recovers this as a direct 12-byte coordinate-triple store helper used by reward/guard probe and projection callers.",
    },
    {
        "address": "0x4ae1fd",
        "name": "coord12_vector_append_one",
        "status": "recovered_static_contract",
        "calls": ["0x430b35"],
        "reads": [
            "12-byte vector anchor in ecx",
            "vector end pointer at ecx+0x08",
            "source 12-byte coordinate record pointer at stack+0x04",
        ],
        "writes": [
            "delegates to 0x430b35 with insertion position vector+0x08, count 1, and the source coordinate record pointer",
            "appends one 12-byte coordinate record to the vector",
        ],
        "ghidra_dump": "Focused dump .artifacts/rmg_recovery/ghidra_coord12_candidate_vector_helper_dump recovers this as the common 12-byte coordinate append wrapper used by reward/guard, connection, terrain, and decorative candidate scans.",
    },
    {
        "address": "0x4ae52a",
        "name": "coord12_vector_erase_range",
        "status": "recovered_static_contract",
        "reads": [
            "12-byte vector anchor in ecx",
            "vector end pointer at ecx+0x08",
            "destination pointer at stack+0x04",
            "source pointer at stack+0x08",
        ],
        "writes": [
            "moves 12-byte records from [source, vector_end) down to destination",
            "updates vector end pointer at ecx+0x08 to destination plus the moved tail length",
        ],
        "ghidra_dump": "Focused dump .artifacts/rmg_recovery/ghidra_coord12_candidate_vector_helper_dump recovers this as a 12-byte coordinate-vector range erase/shift helper used by candidate-vector filters.",
    },
    {
        "address": "0x4ae2d0",
        "name": "coord8_vector_erase_range",
        "status": "recovered_static_contract",
        "reads": [
            "8-byte vector anchor in ecx",
            "vector end pointer at ecx+0x08",
            "destination pointer at stack+0x04",
            "source pointer at stack+0x08",
        ],
        "writes": [
            "moves 8-byte records from [source, vector_end) down to destination",
            "updates vector end pointer at ecx+0x08 to destination plus the moved tail length",
        ],
        "ghidra_dump": "Focused dump .artifacts/rmg_recovery/ghidra_coord12_candidate_vector_helper_dump recovers this as an 8-byte coordinate-vector range erase/shift helper used by wrapper candidate cleanup and other coordinate-vector paths.",
    },
    {
        "address": "0x4aa3e9",
        "name": "reward_object_final_commit_and_wrapper_projection",
        "status": "recovered_static_contract_replay_pending",
        "calls": ["0x49d2c7", "0x49a1d8", "0x49a932", "0x49aa63"],
        "reads": [
            "generator/context pointer in ecx",
            "reward/guard wrapper pointer at stack+0x08",
            "selected coordinate triple args at stack+0x0c/+0x10/+0x14",
            "wrapper generated-cell grid at +0x08/+0x0c/+0x10",
            "wrapper selected-member vector begin/end at +0x2c/+0x30",
            "selected-member vtable at record+0x00 and relative coordinate triple at +0x08/+0x0c/+0x10",
            "generator generated-cell buffer/width/height at +0x14/+0x18/+0x1c",
            "generated-cell owner/score word at +0x20",
            "generated-cell terrain/art word at +0x24",
            "generated-cell bit-state word at +0x28, including bit22, bit26, and bit27",
        ],
        "writes": [
            "copies the selected coordinate triple into wrapper+0x54/+0x58/+0x5c",
            "iterates wrapper selected-member pointers and calls generator/context vtable slot +0x04 with each member pointer and member-relative coordinate plus the selected coordinate triple",
            "computes the overlap rectangle between the wrapper grid and generator grid at the selected coordinate",
            "for each overlapped cell, maps a source generator cell at selected x/y/level plus local offset and a destination wrapper cell at the local offset",
            "captures source bit26 and bit27 from source cell +0x28",
            "when source terrain is not 8, destination bit27 is clear, destination/source cells are valid, and destination/source bit22 are clear, calls 0x49a932(false) on the source cell",
            "under the same accepted branch, if destination bit26 is set, calls 0x49aa63(true) on the source cell",
            "copies captured source bit26 to the destination wrapper cell through 0x49aa63(captured_bit26)",
            "copies captured source bit27 to the destination wrapper cell through 0x49a932(captured_bit27)",
            "after projection, iterates wrapper selected-member pointers again and calls each member vtable slot +0x08",
        ],
        "ghidra_dump": "Called by 0x4aa9b7 after that caller selects a candidate coordinate. Static recovery shows the final reward/guard wrapper projection shell: selected coordinate storage at wrapper+0x54, selected-member coordinate dispatch using object-record +0x08/+0x0c/+0x10 through the generator/context vtable slot +0x04, overlap projection from generator cells into wrapper cells while preserving source bit26/bit27 through 0x49aa63/0x49a932, conditional source bit27 clear/source bit26 set based on destination/source validity and bit22/terrain gates, and final selected-member vtable slot +0x08 callbacks. Exact callback contracts and runtime ordered replay remain pending.",
    },
    {
        "address": "0x4a4c8e",
        "name": "land_edge_generated_cell_bit_writer_entry_checkpoint",
        "status": "checkpoint_authority",
        "reads": ["generator+0x14 generated cells", "generator+0x10e4 runtime-zone relation vectors"],
    },
    {
        "address": "0x4a80dc",
        "name": "route_line_cut_point_picker",
        "status": "recovered_static_and_seed58_runtime_pairs",
        "reads": ["grid generated-cell bit27 neighborhoods along a Bresenham-style line"],
        "returns": ["an output coordinate pair written through the caller-provided pointer"],
        "runtime_trace": "seed58_interactive_4a80dc_return_to_4a4c8e records 52 entry/return pairs before 0x4a4c8e.",
    },
    {
        "address": "0x4072b5",
        "name": "route_coordinate_vector_insert",
        "status": "recovered_static_ghidra",
        "reads": ["ecx vector begin/end/capacity at +0x04/+0x08/+0x0c", "insert position pointer", "count", "source pointer"],
        "writes": ["inserts count 8-byte coordinate records", "reallocates through 0x5044b1 when capacity is insufficient", "updates vector begin/end/capacity"],
        "returns": ["ret 0x0c; no caller-visible data return used by the traced route path"],
    },
    {
        "address": "0x40bb15",
        "name": "route_coordinate_vector_append_one",
        "status": "recovered_static_ghidra",
        "calls": ["0x4072b5"],
        "reads": ["ecx vector end at +0x08", "stack source pointer to one 8-byte coordinate"],
        "writes": ["appends one 8-byte coordinate record at vector end"],
    },
    {
        "address": "0x4ccecb",
        "name": "dword_vector_insert",
        "status": "recovered_static_ghidra",
        "reads": ["ecx vector begin/end/capacity at +0x04/+0x08/+0x0c", "insert position pointer", "count", "source pointer"],
        "writes": ["inserts count 4-byte records", "reallocates through 0x5044b1 when capacity is insufficient", "updates vector begin/end/capacity"],
        "returns": ["ret 0x0c; no caller-visible data return used by 0x40bb26"],
    },
    {
        "address": "0x40bb26",
        "name": "dword_vector_append_one",
        "status": "recovered_static_ghidra",
        "calls": ["0x4ccecb"],
        "reads": ["ecx vector end at +0x08", "stack source pointer to one 4-byte record"],
        "writes": ["appends one 4-byte record at vector end"],
    },
    {
        "address": "0x41e951",
        "name": "object_mask_bit_test",
        "status": "recovered_static_ghidra",
        "reads": ["object descriptor bitset at ecx+0x04", "x arg", "y arg"],
        "returns": ["true when bit 47 - 8*y - x is set in the descriptor bitset", "false when that bit is clear"],
        "ghidra_dump": "Focused dump .artifacts/rmg_recovery/ghidra_object_projection_helper_dump recovers the exact bit index formula and bitset base. Calls 0x42f2ec when computed index is outside the expected 0..47 range.",
    },
    {
        "address": "0x4268eb",
        "name": "object_mask_secondary_bit_test",
        "status": "recovered_static_ghidra",
        "reads": ["object descriptor bitset at ecx+0x0c", "x arg", "y arg"],
        "returns": ["true when bit 47 - 8*y - x is set in the descriptor bitset", "false when that bit is clear"],
        "callers": [
            "0x42650e",
            "0x42b4b1",
            "0x49a6f9",
            "0x49b76d",
            "0x49abd6",
            "0x4aa195",
            "0x4ad3eb",
            "0x46b686",
            "0x47dac4",
            "0x4af910",
            "0x4add76",
        ],
        "ghidra_dump": "Focused dump .artifacts/rmg_recovery/ghidra_4268eb_descriptor_mask_helper_dump recovers the exact bit index formula and bitset base. It is the ecx+0x0c sibling of 0x41e951's ecx+0x04 lookup and calls 0x42f2ec when computed index is outside 0..47.",
    },
    {
        "address": "0x41e915",
        "name": "object_mask_tertiary_bit_test",
        "status": "recovered_static_ghidra",
        "reads": ["object descriptor bitset at ecx+0x3c", "x arg", "y arg"],
        "returns": ["true when bit 47 - 8*y - x is set in the descriptor bitset", "false when that bit is clear"],
        "callers": ["0x41e84b", "0x428d45", "0x42ac12", "0x4205b9", "0x49b89c"],
        "ghidra_dump": "Focused dump .artifacts/rmg_recovery/ghidra_41e915_descriptor_mask_helper_dump recovers the exact bit index formula and bitset base. It is the ecx+0x3c sibling of 0x41e951's ecx+0x04 lookup and 0x4268eb's ecx+0x0c lookup, and calls 0x42f2ec when computed index is outside 0..47.",
    },
    {
        "address": "0x4ae501",
        "name": "route_coordinate_vector_insert_one_return_position",
        "status": "recovered_static_ghidra",
        "calls": ["0x4072b5"],
        "reads": ["ecx vector begin at +0x04", "insert position pointer", "source pointer"],
        "writes": ["inserts one 8-byte coordinate record at the requested position"],
        "returns": ["pointer to the inserted coordinate after possible reallocation"],
    },
    {
        "address": "0x4afaea",
        "name": "route_coordinate_vector_erase_one",
        "status": "recovered_static_ghidra",
        "reads": ["ecx vector end at +0x08", "stack pointer to an 8-byte coordinate record"],
        "writes": ["shifts following 8-byte coordinate records left by one slot", "decrements vector end by 8 bytes"],
    },
    {
        "address": "0x4ae64c",
        "name": "route_coordinate_list_node_alloc",
        "status": "recovered_static_ghidra",
        "writes": ["allocates a 16-byte node", "node+0x00 prev pointer", "node+0x04 next pointer"],
        "payload": "node+0x08 contains one 8-byte coordinate record when used by 0x4ae5a8.",
    },
    {
        "address": "0x4ae5a8",
        "name": "route_coordinate_list_insert_after",
        "status": "recovered_static_ghidra",
        "calls": ["0x4ae64c"],
        "reads": ["existing node pointer", "source pointer to one 8-byte coordinate"],
        "writes": ["inserts a linked-list node after the existing node", "copies the 8-byte coordinate into node+0x08", "increments list count at ecx+0x08", "writes new node pointer through the caller output pointer"],
    },
    {
        "address": "0x4ae5e6",
        "name": "route_coordinate_list_remove_node",
        "status": "recovered_static_ghidra",
        "reads": ["node pointer"],
        "writes": ["unlinks and frees the node through 0x5044da", "decrements list count at ecx+0x08", "writes previous node pointer through the caller output pointer"],
    },
    {
        "address": "0x4a8260",
        "name": "pre_land_edge_route_and_boundary_phase",
        "status": "recovered_seed58_route_call_site_stream_and_static_route_helpers",
        "calls": [
            "0x40bb15 route coordinate append helper",
            "0x4ae501 route coordinate insert helper",
            "0x4afaea route coordinate erase helper",
            "0x4ae5a8 route coordinate list insert helper",
            "0x4ae5e6 route coordinate list remove helper",
            "0x4a80dc route cut helper",
            "0x49a85d route/neighborhood stamp",
            "0x49a962 boundary center and neighborhood clear",
        ],
        "runtime_trace": "For seed 58, caller-side traces before 0x4a4c8e record 1,686 route insertion call-site events, 52 0x4a80dc pairs, 340 0x49a85d route stamps, and 490 0x49a962 boundary clears. The 0x4a858f stamp coordinate order exactly matches the direct 0x49a85d trace, and the 11 far-cut insertion pairs match the 0x4a80dc squared-distance >= 25 gate.",
    },
    {
        "address": "0x4a8c15",
        "name": "generated_cell_post_terrain_phase_driver",
        "status": "recovered_static_and_seed58_runtime_prefix",
        "calls_in_order": ["0x4a8260", "0x4a4c8e", "per-cell scan calling 0x49a962", "0x4a4913 loop over generator+0x10e4 vector", "0x4a5767", "0x4a4fc5", "0x4a79a3"],
        "runtime_trace": "seed58_interactive_49aa63_to_4a4c8e confirms 0x4a8c15 -> 0x4a8260 -> 490 calls to 0x49aa63 -> 0x4a4c8e for the bit26 writer stream.",
    },
    {
        "address": "0x49b3fb",
        "name": "generator_c8_record_lookup",
        "status": "recovered_static_contract_replay_pending",
        "reads": [
            "generator pointer in ecx",
            "lookup key at stack+0x08",
            "generator+0xc8/+0xcc record vector",
        ],
        "returns": [
            "matching generator+0xc8 slot address when the first dword of a 0x1c-byte record equals the lookup key",
            "null when no matching 0x1c-byte record exists",
        ],
        "ghidra_dump": "Called by 0x4a4c8e, 0x4a4fc5, and 0x4a79a3. Static recovery shows +0xc8/+0xcc is consumed here as 0x1c-byte records with slot[0] compared to the lookup key. Exact producer semantics and same-run replay remain pending.",
    },
    {
        "address": "0x49cf34",
        "name": "reward_guard_attach_generated_cell_pass",
        "status": "recovered_static_contract_replay_pending",
        "calls": [
            "0x49d7c3",
            "0x49d2c7",
            "0x49a1d8",
            "0x49aa63",
            "0x49a932",
            "0x49d2e0",
            "0x4afaea",
            "0x4e7276",
            "0x49d69d",
            "0x4ae2d0",
            "0x49d6e0",
        ],
        "reads": [
            "reward/guard wrapper pointer in ecx",
            "object/member record pointer at stack+0x08",
            "wrapper generated-cell grid at +0x08/+0x0c/+0x10",
            "wrapper selected-member vector begin/end at +0x2c/+0x30",
            "wrapper candidate-coordinate vector begin/end at +0x3c/+0x40",
            "selected-member vtable at record+0x00, used later by 0x4aa3e9",
            "selected-member descriptor/payload pointer at record+0x04",
            "selected-member relative coordinate triple at record+0x08/+0x0c/+0x10",
            "selected-member descriptor/payload chain including bounds/anchor words at descriptor +0x2c/+0x30 and a class/terrain-like value at +0x1c",
            "direction table 0x5a2658..0x5a2698",
            "direction-policy table pointer at 0x57c648 used to choose five or eight reverse offsets from descriptor +0x1c",
            "generated-cell terrain/art word at +0x24",
            "generated-cell bit-state word at +0x28, including bit22, bit26, and bit27",
        ],
        "writes": [
            "calls 0x49d7c3 first to populate or refresh wrapper candidate coordinates",
            "iterates the existing selected-member vector and, for each member, probes direction offsets through 0x49d2c7",
            "for each selected-member probe that maps to a valid wrapper cell with bit22 clear, calls 0x49aa63(true) on that cell",
            "after each accepted selected-member probe, scans the 3x3 neighborhood around the probe result and calls 0x49a932(false) on valid cells whose bit22 is clear",
            "filters the candidate-coordinate vector in reverse; candidates whose cell bit26 is clear are erased through 0x4afaea",
            "for candidates whose cell bit26 is set, calls 0x49d2e0(wrapper, candidate coordinate, object/member descriptor) and erases the candidate when that helper rejects it",
            "returns false if the filtered candidate-coordinate vector is empty",
            "chooses one remaining candidate with 0x4e7276 modulo candidate count",
            "calls 0x49d69d(wrapper, object/member record, chosen x, chosen y) to append the member and stamp its footprint",
            "computes the chosen member relative coordinate from the selected coordinate and prior selected-member anchor fields",
            "walks the eight direction offsets around the chosen relative coordinate and calls 0x49a932(true) on valid accepted wrapper cells",
            "writes wrapper+0x4c/+0x50 to the chosen relative x/y and sets wrapper+0x48 to 1",
            "calls 0x4ae2d0 over the candidate-coordinate vector range, then refreshes bounds/candidates through 0x49d6e0 and 0x49d7c3",
            "returns true after successful candidate selection and wrapper refresh",
        ],
        "ghidra_dump": "Called by 0x4aa354 and 0x4adb72. Static recovery shows a three-phase reward/guard attach pass: selected-member neighborhood mutation using object-record fields +0x04 and +0x08/+0x0c/+0x10, reverse filtering of wrapper candidate coordinates through bit26 and 0x49d2e0, then random candidate selection with 0x49d69d stamping, direction-neighborhood bit27 writes, wrapper+0x4c/+0x50/+0x48 finalization, candidate-vector range cleanup, and wrapper bounds/candidate refresh. Exact descriptor/payload semantics, direction-policy class values, and runtime ordered replay remain pending.",
    },
    {
        "address": "0x4adb72",
        "name": "reward_guard_vector_attachment_attempt",
        "status": "recovered_static_contract_replay_pending",
        "calls": ["0x49ce04", "0x49ba89", "0x4aa1db", "0x49cf34", "0x49d6e0", "0x49d7c3", "0x49cefb", "0x4ad7f7", "0x49cebd", "0x4aad8e"],
        "reads": [
            "generator pointer in ecx",
            "input object/member record at stack+0x08",
            "input object/member descriptor through record+0x04",
            "descriptor-side id at descriptor+0x20",
            "generator+0xc8/+0xcc entry vector searched by dereferenced record+0x20",
            "input record relative coordinate triple at +0x08/+0x0c/+0x10",
            "generated-cell buffer/width/height at generator+0x14/+0x18/+0x1c",
            "source generated-cell +0x20 byte2 owner/relation id",
            "relation pointer from generator+0x10e4 indexed by source owner/relation id",
            "byte-state vector at generator+0x1104/+0x1108 and cursor at +0xf5c",
        ],
        "writes": [
            "returns false immediately when no generator+0xc8 entry has dereferenced record+0x20 matching the descriptor-side id",
            "constructs a stack-local reward/guard wrapper through 0x49ce04",
            "allocates a 0x1c-byte object record from the matched +0xc8 entry through 0x49ba89",
            "temporarily marks generator+0x1104[descriptor_id] = 1",
            "resets generator+0xf5c to zero and advances it over marked byte-state entries",
            "runs 0x4aa1db and then 0x49cf34 for the wrapper/object attempt",
            "on success refreshes wrapper bounds/candidates through 0x49d6e0 and 0x49d7c3, finalizes through 0x49cefb and 0x4ad7f7, and returns true",
            "on failure destroys the allocated object, tears down the wrapper, clears generator+0x1104[descriptor_id], resets/advances +0xf5c again, and returns false",
        ],
        "ghidra_dump": "Instruction recovery shows this is the reward/guard attachment attempt wrapper around 0x49cf34 and a temporary consumer/mutator of +0xc8, +0x1104, and +0xf5c. Runtime ordered replay remains pending.",
    },
    {
        "address": "0x499f60",
        "name": "reward_guard_wrapper_grid_constructor",
        "status": "recovered_static_contract",
        "reads": ["wrapper pointer in ecx", "width arg", "height arg", "level-count arg"],
        "writes": [
            "wrapper vtable 0x540a14 at +0x00",
            "wrapper+0x0c width, +0x10 height, +0x14 level count",
            "allocates width*height*level_count generated-cell records with stride 0x30 plus a leading count dword",
            "constructs generated-cell records through 0x499e65",
            "stores the generated-cell buffer pointer at wrapper+0x08",
        ],
        "ghidra_dump": "Used by 0x49ce04 with arguments 0x10, 0x10, 1 to construct the reward/guard wrapper grid.",
    },
    {
        "address": "0x49ce04",
        "name": "reward_guard_wrapper_constructor",
        "status": "recovered_static_contract",
        "calls": ["0x499f60", "0x49ce64"],
        "writes": [
            "calls 0x499f60(wrapper, 0x10, 0x10, 1)",
            "initializes selected-member vector anchor at +0x28 with begin/end/capacity at +0x2c/+0x30/+0x34",
            "initializes candidate-coordinate vector anchor at +0x38 with begin/end/capacity at +0x3c/+0x40/+0x44",
            "clears wrapper flags +0x48 and +0x60",
            "calls 0x49ce64 to reset vectors and wrapper generated-cell state",
        ],
        "ghidra_dump": "Focused dump .artifacts/rmg_recovery/ghidra_reward_guard_wrapper_helper_dump recovers the constructor shell.",
    },
    {
        "address": "0x49ce64",
        "name": "reward_guard_wrapper_reset",
        "status": "recovered_static_contract",
        "calls": ["0x42bde9", "0x4ae2d0", "0x49a072", "0x49acf6"],
        "writes": [
            "clears selected-member vector range +0x2c..+0x30 through 0x42bde9",
            "clears candidate-coordinate vector range +0x3c..+0x40 through 0x4ae2d0",
            "calls 0x49a072 to reset the wrapper generated-cell grid",
            "clears wrapper flags +0x48 and +0x60",
            "walks every wrapper generated cell and calls 0x49acf6(cell, 0, 0, 0, 0)",
        ],
        "ghidra_dump": "Called by 0x49ce04, 0x49cebd, and 0x4aa354. Static reset contract is recovered; runtime phase ordering remains replay-pending.",
    },
    {
        "address": "0x49cebd",
        "name": "reward_guard_wrapper_selected_member_destroy_and_reset",
        "status": "recovered_static_contract",
        "calls": ["selected_member_vtable+0x04", "selected_member_vtable+0x00", "0x49ce64"],
        "reads": ["selected-member vector begin/end at wrapper+0x2c/+0x30"],
        "writes": [
            "iterates selected-member pointers",
            "calls each selected member vtable slot +0x04",
            "destroys non-null selected members through vtable slot +0x00 with argument true",
            "calls 0x49ce64 after the selected-member sweep",
        ],
        "ghidra_dump": "Focused dump recovers the selected-member cleanup and reset path.",
    },
    {
        "address": "0x49cefb",
        "name": "reward_guard_wrapper_candidate_cell_marker",
        "status": "recovered_static_contract",
        "reads": ["candidate-coordinate vector begin/end at wrapper+0x3c/+0x40", "wrapper generated-cell buffer/width at +0x08/+0x0c"],
        "writes": [
            "sets wrapper byte +0x60 to 1",
            "iterates 8-byte candidate coordinate records",
            "maps each candidate x/y into the wrapper generated-cell grid",
            "sets byte cell+0x2a |= 0x80 for each candidate coordinate",
        ],
        "ghidra_dump": "Called before final reward/guard projection from 0x4adb72, 0x4ad947, and 0x4aa354.",
    },
    {
        "address": "0x4aad8e",
        "name": "reward_guard_wrapper_destructor",
        "status": "recovered_static_contract",
        "calls": ["0x42c92d", "0x49a030"],
        "writes": [
            "destroys candidate-coordinate vector at +0x38 through 0x42c92d",
            "destroys selected-member vector at +0x28 through 0x42c92d",
            "calls 0x49a030 to release wrapper generated-cell grid storage",
        ],
        "ghidra_dump": "Focused dump recovers the reward/guard wrapper teardown shell.",
    },
    {
        "address": "0x4aa1db",
        "name": "reward_guard_wrapper_object_seed_helper",
        "status": "recovered_static_contract_replay_pending",
        "calls": ["0x4a9f1c", "0x40bb26", "0x49abd6", "0x49d471", "0x49d6e0"],
        "reads": [
            "generator/context pointer in ecx",
            "selector/object bucket arg at stack+0x08",
            "reward/guard wrapper pointer at stack+0x0c",
            "budget/value args at stack+0x10/+0x14",
            "wrapper dimensions at +0x0c/+0x10",
            "selected object descriptor dimensions at descriptor +0x34/+0x38",
        ],
        "writes": [
            "tries initial object selection through 0x4a9f1c up to three times",
            "appends the selected object record to wrapper+0x28 through 0x40bb26",
            "computes a centered wrapper coordinate from selected descriptor dimensions and wrapper dimensions",
            "stamps the selected object through 0x49abd6",
            "uses remaining budget/value space to attempt secondary object selections through 0x4a9f1c",
            "validates secondary records through 0x49d471 and destroys rejected records through their vtable",
            "calls 0x49d6e0 before returning the consumed/current value",
        ],
        "ghidra_dump": "Focused dump recovers the selection/stamp/retry shell. Exact budget argument names and same-run object sequence remain replay-pending.",
    },
    {
        "address": "0x4ad7f7",
        "name": "reward_guard_relation_ordering_projection_driver",
        "status": "recovered_static_contract_replay_pending",
        "calls": ["0x4ad6a8", "0x4e7276", "0x4ccecb", "0x4aa9b7", "0x42c92d"],
        "reads": [
            "generator pointer in ecx",
            "wrapper arg at stack+0x08",
            "source relation pointer arg at stack+0x0c",
            "relation pointer vector at generator+0x10e4/+0x10e8",
            "relation leading descriptor pointer and descriptor+0x04",
            "relation type/class at +0x0c",
            "relation priority/value at +0x40",
        ],
        "writes": [
            "calls 0x4ad6a8 first",
            "randomizes each relation +0x40 priority with 0x4e7276 % 10",
            "when old +0x40 is 1, writes 1000 + random_mod_10",
            "otherwise writes old_value * 10 + random_mod_10",
            "builds a sorted local relation pointer vector through 0x4ccecb",
            "skips the source relation, relations whose leading descriptor +0x04 is 3, relations with +0x40 > 2000, and relation type/class 8",
            "calls 0x4aa9b7(generator, wrapper, relation, true) for sorted relations until one succeeds",
            "destroys the local relation vector through 0x42c92d",
        ],
        "returns": ["true after the first successful 0x4aa9b7 projection", "false if no sorted relation succeeds"],
        "ghidra_dump": "Focused dump recovers reward/guard relation ordering and projection dispatch. Runtime ordered replay remains pending.",
    },
    {
        "address": "0x4ad6a8",
        "name": "reward_guard_relation_distance_priority_prepass",
        "status": "recovered_static_contract_replay_pending",
        "calls": ["0x42d8d8", "0x4cce95", "0x4ccecb", "0x42c92d"],
        "reads": [
            "generator pointer in ecx",
            "source relation pointer at stack+0x08",
            "relation pointer vector at generator+0x10e4/+0x10e8",
            "relation leading descriptor pointer at relation+0x00",
            "relation priority/value at +0x40",
            "leading descriptor 0x1c-byte records at +0xc8/+0xcc",
        ],
        "writes": [
            "initializes every relation +0x40 priority/value to 0x4e20",
            "sets source relation +0x40 to 0",
            "appends the source relation to a stack-local work vector through 0x42d8d8",
            "pops/erases work-vector entries through 0x4cce95",
            "for each current relation, scans its leading descriptor +0xc8/+0xcc records with stride 0x1c",
            "reads each record's first pointed dword as a relation index into generator+0x10e4",
            "lowers target relation +0x40 when the existing target priority is greater than current +0x40 + 1",
            "inserts lowered target relations back into the work vector through 0x4ccecb using relation +0x40 ordering",
            "destroys the local work vector through 0x42c92d",
        ],
        "ghidra_dump": "Focused dump .artifacts/rmg_recovery/ghidra_reward_guard_projection_callee_dump recovers the relation-distance priority propagation prepass called by 0x4ad7f7. Descriptor +0xc8 producer semantics and same-run replay remain pending.",
    },
    {
        "address": "0x4aa9b7",
        "name": "reward_guard_coordinate_scan_and_commit",
        "status": "recovered_static_contract_replay_pending",
        "calls": ["0x4aa603", "0x4ae52a", "0x4ae1fd", "0x4e7276", "0x4aa3e9", "0x42c92d"],
        "reads": [
            "generator pointer in ecx",
            "reward/guard wrapper pointer at stack+0x08",
            "relation pointer at stack+0x0c",
            "minimum low-word score/value at stack+0x10",
            "boolean policy byte at stack+0x13",
            "relation leading descriptor through relation+0x00",
            "relation coordinate/range fields at +0x10..+0x1c",
            "relation scan bounds at +0x20..+0x2c",
            "wrapper bounds at +0x18..+0x24",
            "generator generated-cell buffer/width/height/depth at +0x14/+0x18/+0x1c/+0x20",
            "generated-cell owner/score word at +0x20",
        ],
        "writes": [
            "builds the overlap scan rectangle between relation bounds and wrapper bounds",
            "scans generator cells in that rectangle",
            "keeps candidates whose generated-cell +0x20 byte2 matches relation leading descriptor +0x00",
            "requires the generated-cell +0x20 low word to be at least the current threshold",
            "calls 0x4aa603(generator, wrapper, candidate coordinate, relation) for each score-passing candidate",
            "when an accepted candidate raises the low-word threshold, clears the previous local coordinate vector through 0x4ae52a",
            "appends accepted 12-byte coordinates at the current threshold through 0x4ae1fd",
            "selects one accepted coordinate with 0x4e7276 % candidate_count",
            "calls 0x4aa3e9(generator, wrapper, selected coordinate) to project the selected wrapper into the generator",
            "destroys the local coordinate vector through 0x42c92d",
        ],
        "returns": ["true after selecting and projecting a coordinate", "false when the accepted coordinate vector is empty"],
        "ghidra_dump": "Focused dump recovers the coordinate scan, best-score candidate vector, random selection, and 0x4aa3e9 commit call. Runtime ordered replay remains pending.",
    },
    {
        "address": "0x4aa603",
        "name": "reward_guard_coordinate_feasibility_filter",
        "status": "recovered_static_contract_replay_pending",
        "calls": ["0x49a6f9", "0x49d2c7", "0x49a1d8", "0x49d65c", "0x49a09c"],
        "reads": [
            "generator pointer in ecx",
            "reward/guard wrapper pointer at stack+0x08",
            "candidate x/y/level at stack+0x0c/+0x10/+0x14",
            "relation pointer at stack+0x18",
            "wrapper selected-member vector at +0x2c/+0x30",
            "wrapper selected-member attached flag and relative coordinates at +0x48/+0x4c/+0x50",
            "wrapper candidate-coordinate vector anchor at +0x38",
            "member descriptor pointer at member+0x04",
            "member relative coordinate triple at +0x08/+0x0c/+0x10",
            "last selected member descriptor bounds +0x2c/+0x30 and type/class +0x1c",
            "policy table 0x57c648 and direction offsets 0x5a2658",
            "generator generated-cell grid through +0x14/+0x18/+0x1c",
            "wrapper generated-cell grid through +0x08/+0x0c",
            "generated-cell terrain/art word +0x24 and bit-state +0x28",
        ],
        "writes": [
            "tests every selected member footprint at the candidate coordinate through 0x49a6f9",
            "when wrapper +0x48 is set, probes from wrapper +0x4c/+0x50 plus the candidate coordinate through 0x49d2c7",
            "rejects the probe neighborhood when a bit22 object resolves to descriptor type/class 0x36",
            "uses last selected member descriptor policy to scan either the reduced or full direction-offset set",
            "requires at least one wrapper source direction cell with bit27 set, valid state, bit22 clear, and bit23 set",
            "requires the mapped generator destination cell to match the terrain-8 policy implied by relation+0x0c == 8, be valid, bit22 clear, and bit27 clear",
            "calls 0x49a09c(generator+0x0c, wrapper+0x38, candidate coordinate, require_unattached_flag, relation, true)",
            "scans the wrapper/generator overlap rectangle after 0x49a09c and rejects candidates that would cover an already bit26-marked generator destination from a wrapper cell whose bit27 is clear",
        ],
        "returns": ["true only when all footprint, probe, directional, rectangle, and overlap gates pass", "false on the first rejected gate"],
        "ghidra_dump": "Focused dump recovers the candidate feasibility filter underneath 0x4aa9b7. Runtime ordered replay remains pending.",
    },
    {
        "address": "0x49d65c",
        "name": "reward_guard_selected_member_policy_table_check",
        "status": "recovered_static_contract_replay_pending",
        "reads": [
            "reward/guard wrapper pointer in ecx",
            "wrapper selected-member vector at +0x2c/+0x30",
            "selected member descriptor through member+0x04",
            "descriptor type/class at descriptor+0x1c",
            "policy table 0x57c648 at slot (descriptor_type << 4) + 2",
        ],
        "returns": [
            "true when the selected-member vector is empty",
            "true when every selected member has a nonzero policy byte at table slot +2",
            "false on the first selected member whose policy byte is zero",
        ],
        "ghidra_dump": "Focused dump .artifacts/rmg_recovery/ghidra_reward_guard_filter_side_effect_dump recovers the selected-member policy helper called by 0x4aa603.",
    },
    {
        "address": "0x49a09c",
        "name": "reward_guard_candidate_offset_contour_validator",
        "status": "recovered_static_contract_replay_pending",
        "calls": ["0x49a1d8"],
        "reads": [
            "generated-cell grid wrapper in ecx",
            "candidate-offset vector anchor at stack+0x08 with begin/end at anchor+0x04/+0x08",
            "candidate x/y/level at stack+0x0c/+0x10/+0x14",
            "allow-existing-bit22 flag at stack+0x18",
            "relation pointer at stack+0x1c",
            "require-bit27 flag at stack+0x20",
            "relation type/class at +0x0c",
            "relation leading descriptor id through relation+0x00 -> descriptor -> +0x00",
            "grid generated-cell buffer/width/height at +0x08/+0x0c/+0x10",
            "generated-cell owner/score word +0x20, terrain/art word +0x24, and bit-state +0x28",
        ],
        "returns": [
            "false on hard existing-bit22 rejection when allow-existing-bit22 is false",
            "false on disallowed invalid/gap patterns across the offset contour",
            "true when the contour passes bounds, validity, terrain, owner, bit22, and optional bit27 checks",
        ],
        "writes": ["no generated-cell mutation observed; only stack-local flags are mutated"],
        "ghidra_dump": "Focused dump recovers the contour/vector validator called by 0x49aa93 and 0x4aa603. Same-run replay and exact contour-gap semantic naming remain pending.",
    },
    {
        "address": "0x49aa93",
        "name": "source_relation_object_coordinate_eligibility_gate",
        "status": "recovered_static_contract_replay_pending",
        "calls": ["0x49a6f9", "0x49b76d", "0x49a09c", "0x49a1d8"],
        "reads": [
            "generated-cell grid wrapper pointer in ecx",
            "object record/descriptor argument at stack+0x08",
            "candidate x/y/level at stack+0x0c/+0x10/+0x14",
            "source/relation record pointer at stack+0x18",
            "source/relation leading pointer chain used to derive relation id",
            "object descriptor through the object argument, including type/class +0x1c, policy byte +0x29, offsets +0x2c/+0x30, and candidate-offset anchor at object argument +0x14",
            "policy table pointer 0x57c648, including slots (descriptor_type << 4) + 1 and +2",
            "generated-cell grid buffer/width/height at wrapper+0x08/+0x0c/+0x10",
            "generated-cell owner/score word +0x20, terrain/art word +0x24, and bit-state +0x28",
            "source/relation type/class at +0x0c for the terrain-8 comparison",
        ],
        "returns": [
            "false when 0x49a6f9 reports the object footprint is rejected",
            "false when 0x49a09c rejects the candidate-offset contour",
            "true after 0x49a09c when descriptor byte +0x29 is clear",
            "false when descriptor byte +0x29 is set and the descriptor-offset source cell is out of bounds, invalid, has a mismatched owner/relation byte, fails occupied-cell policy checks, or fails the terrain-8 relation policy comparison",
            "true when all footprint, contour, descriptor-offset source-cell, owner, occupied-cell, and terrain-policy gates pass",
        ],
        "writes": ["no generated-cell mutation observed; only stack-local temporaries and copied coordinate triples are mutated"],
        "callers": ["0x4a696b", "0x4a6cf2", "0x4a7312", "0x4a901a", "0x4a93a2", "0x4a9911", "0x4a9641"],
        "ghidra_dump": "Focused dump .artifacts/rmg_recovery/ghidra_49aa93_eligibility_helper_dump recovers the source/relation object-coordinate eligibility gate from instruction/reference evidence. Ghidra decompile still fails, so exact semantic names and ordered replay remain pending.",
    },
    {
        "address": "0x49b76d",
        "name": "object_descriptor_contour_vector_cache_builder",
        "status": "recovered_static_contract_replay_pending",
        "calls": ["0x41e951", "0x4268eb", "0x40bb15"],
        "reads": [
            "object descriptor/cache record pointer in ecx",
            "descriptor pointer at record+0x00",
            "8-byte vector begin/end pointers at record+0x18/+0x1c for the vector anchored at record+0x14",
            "descriptor dimensions at descriptor+0x34/+0x38",
            "descriptor mask tests through 0x41e951 and 0x4268eb",
            "direction offsets at 0x5a2658..0x5a2698",
        ],
        "writes": [
            "early-outs without mutation when record+0x18 is nonzero and the record+0x14 vector has a nonzero 8-byte record count",
            "uses stack-local x/y trace coordinates and direction ordinals to walk descriptor-mask contour edges",
            "appends 8-byte coordinate records to the vector anchored at record+0x14 through 0x40bb15",
        ],
        "returns": ["no explicit boolean return contract observed; callers use it as a cache-populating side-effect helper"],
        "callers": ["0x49aa93", "0x4a9641"],
        "ghidra_dump": "Focused dump .artifacts/rmg_recovery/ghidra_49b76d_policy_helper_dump recovers the descriptor contour/vector cache builder. Ghidra decompile still fails; exact descriptor-mask semantic names and ordered vector replay remain pending.",
    },
    {
        "address": "0x49a6f9",
        "name": "object_descriptor_footprint_acceptance_gate",
        "status": "recovered_static_contract_replay_pending",
        "calls": ["0x4268eb", "0x49a1d8", "0x41e951"],
        "reads": [
            "object descriptor pointer through arg1",
            "object width/height at descriptor+0x34/+0x38",
            "candidate x/y/level/owner/mode args",
            "wrapper grid at ecx+0x08/+0x0c/+0x10",
            "generated cell +0x20 owner, +0x24 terrain, +0x28 bit state",
        ],
        "returns": [
            "false when every footprint/body cell passes bounds, validity, owner, terrain, optional bit26, and 0x41e951 mask tests",
            "true when any footprint/body cell rejects the candidate",
        ],
        "ghidra_dump": "Called by 0x49aa93, 0x49d2e0, and 0x4aa603. Static contract is recovered; exact descriptor field names beyond dimensions and terrain policy branches remain replay-pending.",
    },
    {
        "address": "0x49d2e0",
        "name": "reward_guard_candidate_acceptance_helper",
        "status": "recovered_static_contract_replay_pending",
        "calls": ["0x49a1d8", "0x49a6f9"],
        "reads": ["object descriptor through arg1", "candidate x/y/level args", "wrapper grid at ecx+0x08/+0x0c/+0x10", "direction tables 0x5a2658 and 0x5a2680"],
        "returns": ["true when the candidate passes object terrain/footprint/ring checks", "false when bit22/object adjacency/terrain rules reject it"],
        "ghidra_dump": "Called by 0x49cf34 and 0x49d471. Static pass recovers direction-table scans and 0x49a6f9 footprint probes; exact object descriptor field naming remains replay-pending.",
    },
    {
        "address": "0x49d69d",
        "name": "reward_guard_member_stamp_helper",
        "status": "recovered_static_contract_replay_pending",
        "calls": ["0x40bb26", "0x49abd6"],
        "reads": ["arg1 object/member pointer", "arg2 x", "arg3 y"],
        "writes": ["appends arg1 to wrapper+0x28 dword vector", "stamps arg2/arg3/level 0 through 0x49abd6"],
        "ghidra_dump": "Called by 0x49cf34. Static contract is recovered; member object projection into final package/object vector remains replay-pending.",
    },
    {
        "address": "0x49d6e0",
        "name": "reward_guard_candidate_grid_refresh_helper",
        "status": "recovered_static_contract_replay_pending",
        "calls": ["0x49a1d8"],
        "writes": ["wrapper+0x18/+0x1c initialized to 0x7d00", "wrapper+0x20/+0x24 initialized to 0xffff8300", "updates bounds over cells that are invalid, bit22 set, or bit27 clear"],
        "ghidra_dump": "Called by 0x49cf34, 0x4aa1db, 0x4adb72, and 0x4ad947. Static bounds recomputation is recovered; exact caller ordering and vector contents remain replay-pending.",
    },
    {
        "address": "0x49d7c3",
        "name": "reward_guard_candidate_vector_rebuild_helper",
        "status": "recovered_static_contract_replay_pending",
        "calls": ["0x49a1d8", "0x40bb15"],
        "writes": ["when wrapper+0x38 vector is empty, appends 8-byte coordinates to wrapper+0x38 vector", "traces the contour starting from the first valid bit27 cell with bit22 clear"],
        "ghidra_dump": "Called by 0x49cf34 and reward/guard setup callers. Static contour/vector rebuild contract is recovered; exact runtime coordinate sequence must still be traced and replayed.",
    },
    {
        "address": "0x49eb8d",
        "name": "bit26_decorative_candidate_budget_pass",
        "status": "recovered_static_contract_seed58_breakpoint_layout_replay_pending",
        "calls": ["0x49a1d8", "0x49e700", "0x49a932"],
        "reads": [
            "generator pointer in ecx",
            "generated-cell buffer at generator+0x14",
            "map width/height/level count at generator+0x18/+0x1c/+0x20",
            "GeneratedCell+0x28 bit-state word",
            "optional handler pointer at generator+0xed4",
        ],
        "writes": [
            "calls 0x49e700 for valid bit26 candidate cells with x/y/level and budget",
            "calls optional generator+0xed4 vtable slot +0x08 for invalid bit26 candidate cells",
            "calls 0x49a932(true) for valid cells whose bit27 is clear after decorative attempts",
        ],
        "runtime_trace": "tools/rmg_h3maped_49eb8d_trace_summary.py parses the existing seed58 raw winedbg logs into .artifacts/rmg_recovery/seed58_49eb8d_trace_summary.json. The 0x49ec01 breakpoint log proves generated-cell dimensions 36x36x1, bit26 count local [EBP-0x8] = 406, and computed budget 0x4374c // 406 = 680 for that run. A separate 0x49e700 entry breakpoint log proves stack argument layout x=3, y=0, level=0, budget=678 for its first captured dispatch. These are separate debugger runs, so they are layout/count evidence and not a same-run ordered replay.",
        "ghidra_dump": "Instruction dump recovers three ordered full-grid passes. Pass 1 counts cells where (GeneratedCell+0x28 >> 26) & 1 is set. If count is nonzero, pass 2 computes budget = 0x4374c / count and scans z/y/x in generator +0x20/+0x1c/+0x18 order; for each bit26 cell it calls 0x49e700 when 0x49a1d8 is true, otherwise calls an optional generator+0xed4 indirect handler with the same budget. Pass 3 scans the grid again and calls 0x49a932(true) when bit27 is clear and 0x49a1d8 is true. Same-run coordinate/count/dispatch replay remains pending.",
    },
    {
        "address": "0x49eb6d",
        "name": "generated_cell_at_xyz_helper",
        "status": "recovered_static_ghidra",
        "reads": ["wrapper cell buffer at ecx+0x08", "width at ecx+0x0c", "height at ecx+0x10", "x/y/level args"],
        "returns": ["cell pointer = buffer + (((level * height) + y) * width + x) * 0x30"],
    },
    {
        "address": "0x49ba89",
        "name": "object_record_constructor",
        "status": "recovered_static_ghidra",
        "calls": ["0x49bae3"],
        "reads": ["descriptor pointer arg"],
        "writes": ["record vtable 0x540a74 at +0x00", "descriptor pointer at +0x04", "increments descriptor+0x08 refcount", "initializes record +0x08/+0x0c/+0x10 to -1"],
        "returns": ["constructed record pointer in eax"],
    },
    {
        "address": "0x49b89c",
        "name": "object_record_mask_score_cache_builder",
        "status": "recovered_static_contract_replay_pending",
        "calls": ["0x41e915", "0x41e951"],
        "reads": ["object record pointer in ecx", "descriptor pointer at record+0x00", "descriptor dimensions at +0x34/+0x38", "descriptor mask tests"],
        "writes": ["record+0xe4 cache-built byte", "record-local dword table beginning at +0x18"],
        "ghidra_dump": "Focused dump shows the helper is idempotent on record+0xe4, walks descriptor width/height, calls descriptor mask helpers, and fills a record-local dword table with relative mask classifications. Exact table semantic names remain replay-pending.",
    },
    {
        "address": "0x4a9e40",
        "name": "object_descriptor_random_selector",
        "status": "recovered_static_contract_replay_pending",
        "calls": ["0x401b93", "0x40bb26", "0x4e7276"],
        "reads": ["bucket/context pointer in ecx", "selector args", "descriptor pointer vector at bucket+0x38/+0x3c", "descriptor type/category field at +0x20", "descriptor class field at +0x24", "descriptor bitset at +0x18"],
        "returns": ["one candidate descriptor pointer selected by 0x4e7276 % candidate_count", "null when no candidate matches"],
        "ghidra_dump": "Focused dump recovers candidate filtering and random tie selection. Exact semantic names for selector args and descriptor class values remain replay-pending.",
    },
    {
        "address": "0x49e1bf",
        "name": "decorative_object_scoring_and_emission_feasibility",
        "status": "recovered_static_contract_replay_pending",
        "calls": ["0x42ccc6", "0x42cc99", "0x49b89c", "0x40bb26", "0x42c92d"],
        "reads": [
            "generator pointer in ecx with generated-cell buffer/width/height at +0x14/+0x18/+0x1c",
            "object record arg at stack+0x08 and descriptor pointer at record+0x00",
            "candidate x/y/level args at stack+0x0c/+0x10/+0x14",
            "descriptor dimensions at +0x34/+0x38",
            "descriptor mask ranges at +0x04/+0x14/+0x3c",
            "candidate descriptor terrain policy at +0x14 checked through 0x42cc99",
            "candidate object terrain score table at record+0x10 with ten terrain-class contributions",
            "candidate descriptor neighbor score tables at +0x30 and +0x40",
            "GeneratedCell+0x04/+0x08 object-reference vector",
            "GeneratedCell+0x24 terrain/art word",
            "GeneratedCell+0x28 bit-state word",
            "GeneratedCell+0x2b validity byte",
        ],
        "writes": [
            "stack-local footprint records with flags 0x1/0x2/0x4 and stride 0x20",
            "stack-local terrain-class hit vector with ten buckets",
            "stack-local scratch rectangle used for neighbor scans",
            "temporary object-reference flags at +0x14/+0x15/+0x16/+0x17/+0x18",
            "appends flagged object-reference pointers to a local dword vector through 0x40bb26",
            "adds descriptor +0x30/+0x40 table contributions for flagged neighbor references",
            "clears the temporary object-reference flags at +0x14..+0x18 before returning",
        ],
        "returns": [
            "positive candidate emission score when accepted by 0x49e700",
            "-1 when no positive terrain-class contribution is found",
            "-5000 when a hard placement/neighbor conflict path is hit",
            "terrain-weight total directly when the total is below -1000",
        ],
        "ghidra_dump": "Focused dump recovers the ordered footprint pass and neighbor-reference pass. The footprint pass walks descriptor height/width, checks descriptor masks through 0x42ccc6, validates terrain through descriptor+0x14/0x42cc99, rejects bit27 cells, records ten terrain-class hits, and expands a stack-local scratch rectangle. The neighbor pass walks descriptor dimensions plus a one-cell border, gates on the scratch rectangle, scans GeneratedCell+0x04/+0x08 object references, prepares referenced records through 0x49b89c, sets temporary flags +0x14..+0x18, appends flagged references through 0x40bb26, applies descriptor +0x30/+0x40 score-table adjustments, clears flags, and returns the final score/rejection. Exact semantic names for record+0x10 terrain scores, descriptor +0x30/+0x40 neighbor tables, object-reference flag classes, and runtime ordered replay remain pending.",
    },
    {
        "address": "0x49e700",
        "name": "decorative_object_candidate_filler",
        "status": "recovered_static_contract_replay_pending",
        "calls": ["0x4ae20e", "0x4ae23e", "0x49eb6d", "0x41e951", "0x49e1bf", "0x40bb26"],
        "reads": [
            "generator/wrapper pointer in ecx",
            "candidate x/y/level args",
            "generated cell via 0x49eb6d",
            "terrain-object descriptor table 0x54092c..0x5409e0",
            "object descriptor width/height at +0x34/+0x38",
            "object descriptor type/subtype fields including +0x1c",
        ],
        "writes": [
            "accumulates accepted object emission weights",
            "appends accepted emission weights through 0x40bb26",
            "after weighted selection, creates/projects one decorative object and clears bit26 around the selected footprint unless cell+0x2c bit0 suppresses mutation",
        ],
        "ghidra_dump": "Called by 0x49eb8d. Static pass recovers the terrain-object table loop, local footprint scan through 0x41e951, 0x49e1bf scoring/emission feasibility, weighted-selection setup, and surrounding bit26 cleanup. Exact object record allocation/projection fields remain replay-pending.",
    },
    {
        "address": "0x4a54a7",
        "name": "object_footprint_commit_and_local_owner_projection",
        "status": "recovered_static_contract_replay_pending",
        "calls": ["0x49abd6", "0x42d8d8", "0x4ae20e", "0x4ae23e", "0x4cce95", "0x430b35", "0x4ccecb", "0x42c92d"],
        "reads": [
            "generator pointer in ecx",
            "generated-cell grid wrapper at generator+0x0c with buffer/width/height at +0x08/+0x0c/+0x10",
            "object record arg at stack+0x08",
            "candidate x/y/level args at stack+0x0c/+0x10/+0x14",
            "object descriptor fields reached through record+0x04",
            "generator object vector anchored at +0xec4",
            "generator relation table at +0x10e4",
            "direction tables 0x5a2658..0x5a2698",
        ],
        "writes": [
            "calls 0x49abd6 to stamp the object footprint into generated cells",
            "inserts the object record into the generator object vector anchored at +0xec4 through 0x42d8d8",
            "increments generator+0x1110 descriptor-type counter indexed by descriptor+0x1c",
            "if descriptor byte +0x29 is zero, exits after object commit and counter update",
            "computes the descriptor-offset source cell from candidate x/y/level minus descriptor +0x2c/+0x30",
            "when source GeneratedCell+0x20 byte2 is nonnegative, increments relation +0x44 + descriptor_type*4",
            "clears the source cell +0x20 low word to zero",
            "seeds a 12-byte coordinate work vector with the source coordinate through 0x4ae20e",
            "seeds a parallel 4-byte low-word score vector with zero through 0x42d8d8",
            "removes the last coordinate and score through 0x4ae23e and 0x4cce95",
            "derives a proposed neighbor score from current GeneratedCell+0x20 low word + 2, with one additional cost on odd direction indices",
            "for each in-bounds direction neighbor whose +0x20 low word is greater than the proposed score, rewrites the low word while preserving the high 16 bits",
            "binary-searches the score vector, inserts the neighbor coordinate into the 12-byte work vector through 0x430b35, and inserts the proposed score into the dword vector through 0x4ccecb",
            "destroys both local vectors through 0x42c92d",
        ],
        "ghidra_dump": "Focused dump .artifacts/rmg_recovery/ghidra_object_commit_projection_vector_dump recovers the object commit shell and its sorted low-word projection loop. Exact semantic names for descriptor +0x29/+0x2c/+0x30, relation counter roles, and runtime ordered replay remain pending.",
    },
    {
        "address": "0x4ae20e",
        "name": "coord12_vector_append_one_and_return_slot",
        "status": "recovered_static_contract",
        "calls": ["0x430b35"],
        "reads": ["12-byte vector anchor in ecx", "insert/source coordinate pointer args"],
        "writes": [
            "delegates to 0x430b35 with count 1 to insert one 12-byte coordinate record",
            "returns the address corresponding to the inserted 12-byte slot after delegating insertion",
        ],
        "ghidra_dump": "Focused vector-helper dump recovers this as a thin 12-byte vector append/insert wrapper used by 0x4a54a7, 0x49a318, and 0x49e700.",
    },
    {
        "address": "0x4ae23e",
        "name": "coord12_vector_erase_one",
        "status": "recovered_static_contract",
        "reads": ["12-byte vector anchor in ecx", "slot pointer at stack+0x08"],
        "writes": [
            "moves following 12-byte records down by one slot",
            "decrements vector end pointer by 12 bytes",
        ],
        "ghidra_dump": "Focused vector-helper dump recovers this as a 12-byte coordinate-vector erase helper used by 0x4a54a7, 0x49a318, 0x49e700, and connection helpers.",
    },
    {
        "address": "0x430b35",
        "name": "coord12_vector_insert_count",
        "status": "recovered_static_contract",
        "reads": ["12-byte vector anchor in ecx", "insert position pointer", "record count", "source record pointer"],
        "writes": [
            "grows allocation when needed through allocator/free helpers 0x5044b1/0x5044da",
            "moves existing 12-byte records around the insertion point",
            "copies count 12-byte records from the source pointer",
            "updates vector begin/end/capacity pointers",
        ],
        "ghidra_dump": "Focused vector-helper dump recovers this as the generic 12-byte coordinate vector insertion helper used by 0x4a54a7 and related projection code.",
    },
    {
        "address": "0x4cce95",
        "name": "dword_vector_erase_one",
        "status": "recovered_static_contract",
        "reads": ["dword vector anchor in ecx", "slot pointer at stack+0x08"],
        "writes": [
            "moves following 4-byte entries down by one slot",
            "decrements vector end pointer by 4 bytes",
        ],
        "ghidra_dump": "Focused vector-helper dump recovers this as a dword-vector erase helper used by relation/score work vectors.",
    },
    {
        "address": "0x4ccecb",
        "name": "dword_vector_insert_count",
        "status": "recovered_static_contract",
        "reads": ["dword vector anchor in ecx", "insert position pointer", "entry count", "source pointer"],
        "writes": [
            "grows allocation when needed through allocator/free helpers 0x5044b1/0x5044da",
            "moves existing 4-byte entries around the insertion point",
            "copies count dword entries from the source pointer",
            "updates vector begin/end/capacity pointers",
        ],
        "ghidra_dump": "Focused vector-helper dump recovers this as the generic dword vector insertion helper used by 0x4a54a7, 0x4ad6a8, 0x4ad7f7, and 0x49a318.",
    },
    {
        "address": "0x4a5767",
        "name": "cell_occupancy_reset_and_object_anchor_normalization",
        "status": "recovered_static_contract_replay_pending",
        "calls": ["0x4a59e2", "0x49a1d8", "0x49a932", "0x49a318", "0x4a5a23"],
        "reads": [
            "generator pointer in ecx",
            "generated-cell buffer/width/height/level count at generator+0x14/+0x18/+0x1c/+0x20",
            "relation pointer vector at generator+0x10e4..+0x10e8",
            "relation record +0x0c type/class value compared with 8",
            "relation record +0x10..+0x1b copied as a 12-byte coordinate/range triple",
            "relation record +0x20..+0x2f copied as four dwords of scan bounds",
            "generated-cell +0x04/+0x08 object-reference vector begin/end",
            "generated-cell +0x1c local word gate",
            "generated-cell +0x20 byte2 owner/relation index",
            "generated-cell +0x24 terrain id",
            "generated-cell +0x28 bit27 occupancy",
        ],
        "writes": [
            "full-grid pass calls 0x4a59e2(cell, 0x7d00, 0, -1), forces cell+0x1c low word to 0x7d00, and copies a local triple into cell+0x10/+0x14/+0x18",
            "for each relation pointer, scans the relation +0x20 bounds for matching generated-cell owner byte2 and valid bit27 candidate cells",
            "when the first scan does not find a candidate, computes a generated-cell pointer from the current local triple and calls 0x49a932(true)",
            "calls 0x49a318 with generator+0x0c grid wrapper, a 12-byte local coordinate triple, and a boolean derived from relation+0x0c == 8",
            "runs a second relation-bounds scan and calls 0x4a5a23(generator, coordinate triple, false) for valid occupied cells, followed by another 0x49a318 call",
        ],
        "ghidra_dump": "Called by 0x4a8c15, 0x4a746b, and 0x4ac552. Instruction recovery shows the full-grid reset/normalization pass, the relation-vector scan over generator+0x10e4..+0x10e8, generated-cell owner/bit27/terrain/object-ref gates, and the helper calls into 0x49a932/0x49a318/0x4a5a23. Exact relation-record field semantics and runtime ordered replay remain pending.",
    },
    {
        "address": "0x49a318",
        "name": "object_anchor_owner_projection_helper",
        "status": "recovered_static_contract_replay_pending",
        "calls": ["0x4ae20e", "0x42d8d8", "0x4ae23e", "0x4cce95", "0x4ccecb", "0x430b35"],
        "reads": [
            "generated-cell grid wrapper pointer in ecx with buffer/width/height at +0x08/+0x0c/+0x10",
            "coordinate triple args at stack+0x08/+0x0c/+0x10",
            "policy boolean at stack+0x14",
            "direction table 0x5a2658..0x5a2698",
            "generated-cell projection triple at +0x10/+0x14/+0x18",
            "generated-cell local word gate/priority word at +0x1c",
            "generated-cell owner/score word at +0x20, including byte2 owner/relation index",
            "generated-cell terrain/art word at +0x24",
            "generated-cell bit-state word at +0x28, including bit22, bit25, and bit27",
            "object descriptor policy table through 0x57c648 when bit22 is set",
        ],
        "writes": [
            "seeds a local 12-byte coordinate work vector with the input coordinate through 0x4ae20e/0x42d8d8",
            "resets the source coordinate cell by clearing the low word of +0x1c and writing -1/-1/-1 to +0x10/+0x14/+0x18",
            "pops/scans 12-byte coordinates from the work vector through 0x4ae23e/0x4cce95",
            "for each work coordinate, scans direction offsets from 0x5a2658 with an eight-direction or five-direction policy depending on bit22/descriptor-table gates",
            "rejects candidate cells that are out of bounds, have a negative owner word, lack bit25, or have terrain id 9",
            "applies additional descriptor-table gates for bit22 object cells",
            "when the candidate owner differs from the source owner but matches the previous owner relation, updates the high word of candidate +0x1c, packs the direction ordinal into +0x28 bits 12..14, and writes the source owner into +0x20 byte3",
            "when the candidate owner matches the source owner, updates the low word of candidate +0x1c and copies the current coordinate into candidate +0x10/+0x14/+0x18",
            "for zero-score same-owner candidates with bit27 set, may force the propagated score to zero based on terrain id 8 and the policy boolean",
            "inserts propagated scores into a sorted local dword vector through 0x4ccecb",
            "inserts propagated coordinates into the work vector through 0x430b35",
            "continues until the local coordinate work vector is empty",
        ],
        "ghidra_dump": "Called by 0x4a5767 and 0x4a89da with generator+0x0c grid wrapper, a coordinate triple, and a boolean policy flag. Static recovery shows a work-vector projection/priority propagation helper: it resets the source cell projection, walks direction neighbors, gates on owner/bit25/bit22/terrain/descriptor-table policy, updates GeneratedCell+0x1c high or low word depending on owner relationship, writes projection triples, packs direction bits into +0x28, writes owner byte3 in +0x20, and maintains sorted score plus coordinate work vectors until exhausted. Exact semantic names for the propagated scores, owner-byte roles, descriptor-table policy bytes, and runtime ordered replay remain pending.",
    },
    {
        "address": "0x4a5a23",
        "name": "connection_object_selection_helper",
        "status": "recovered_static_contract_replay_pending",
        "calls": ["0x49eb6d", "0x4a9e40", "0x5044b1", "0x49ba89"],
        "reads": [
            "generator pointer in ecx",
            "coordinate triple args at stack+0x08/+0x0c/+0x10",
            "cleanup-suppression boolean at stack+0x14",
            "generated-cell grid wrapper at generator+0x0c through 0x49eb6d",
            "generated-cell projection triple at +0x10/+0x14/+0x18",
            "generated-cell local word gate at +0x1c",
            "generated-cell owner/score word at +0x20, including byte2 owner/relation index",
            "generated-cell bit-state word at +0x28",
            "generated-cell validity/private byte at +0x2b",
            "generated-cell private flags at +0x2c, including bit0 and bits 1..4 packed source",
        ],
        "writes": [
            "maps the input coordinate through 0x49eb6d using generator+0x0c",
            "returns immediately when the mapped cell +0x1c low word is zero or >= 0x7530",
            "when mapped cell +0x2c bit0 is set, calls 0x4a9e40(generator, 0, 9, ((cell+0x2c >> 1) & 0x0f))",
            "allocates a 0x1c-byte object record and initializes it through 0x49ba89 with the selected descriptor",
            "clears the mapped cell +0x2c low five bits",
            "sets mapped cell bit27 and clears bit26 in +0x28 unless cell+0x2c bit0 suppresses mutation",
            "calls generator vtable slot +0x04 with the current coordinate triple and allocated object record",
            "when cell +0x2c bit0 is clear, sets bit27 and clears bit26 in +0x28",
            "copies the mapped cell +0x10/+0x14/+0x18 projection triple and uses it as the next coordinate",
            "when the cleanup-suppression boolean is false, scans a clipped rectangle from x-1/y-1 through x+1/y+1 around the input coordinate",
            "for same-owner cells in that rectangle whose +0x2c bit0 is clear, clears bit 0x04 in +0x2b",
            "continues following the projection triple chain while the next mapped cell +0x1c low word remains positive",
        ],
        "ghidra_dump": "Called by 0x4a5767 and 0x4a61bc. Static recovery shows a projected-cell chain helper: it maps coordinates through generator+0x0c, gates on GeneratedCell+0x1c, optionally materializes an object from the packed GeneratedCell+0x2c low-nibble source via 0x4a9e40/0x49ba89 and generator vtable slot +0x04, forces bit27/clears bit26, optionally clears GeneratedCell+0x2b bit0x04 in nearby same-owner cells, and follows +0x10/+0x14/+0x18 projection triples until the chain terminates. Exact descriptor category semantics, +0x2b bit0x04 meaning, and runtime ordered replay remain pending.",
    },
    {
        "address": "0x4a606b",
        "name": "connection_region_generated_cell_writer",
        "status": "recovered_static_contract_replay_pending",
        "calls": ["0x49aa63", "0x49a932"],
        "reads": [
            "generator pointer in ecx",
            "coordinate triple args at stack+0x08/+0x0c/+0x10",
            "low-nibble source/flag arg at stack+0x14; both 0x4a61bc callers pass the nonnegative return value from 0x4a5e73",
            "generated-cell buffer/width/height at generator+0x14/+0x18/+0x1c",
            "generated-cell object-reference vector begin/end at +0x04/+0x08",
            "generated-cell projection triple at +0x10/+0x14/+0x18",
            "generated-cell private flags at +0x2c",
        ],
        "writes": [
            "clamps a 3x3 rectangle around the x/y coordinate args to [0,width) and [0,height) on the supplied level",
            "for cells in that rectangle whose object-reference vector is empty, calls 0x49aa63(true)",
            "for the same accepted cells, writes cell+0x2c = (old & 0xffffffe1) | ((arg4 & 0x0f) << 1) | 1",
            "after the rectangle pass, reads the source coordinate cell's +0x10/+0x14/+0x18 projection triple",
            "when that projected x/y is in bounds, clears low five bits of the projected target cell +0x2c and calls 0x49a932(true)",
        ],
        "caller_contract": "Both 0x4a61bc call sites are gated by control byte [arg2+0x09] and a successful 0x4a5e73 return. The first call passes the selected 12-byte temporary candidate coordinate at EBP-0x3c..-0x34 after 0x4a5e73(generator, selected_candidate, true, relation_record_from_generator+0x10e4) returns nonnegative. The second call passes the direction-adjacent coordinate at EBP-0x48..-0x40, computed from the selected candidate plus direction offset 0x5a2658[(selected_cell+0x28 >> 12) & 7], after 0x4a5e73(generator, direction_adjacent, true, stack_arg+0x08) returns nonnegative. In both calls the 0x4a606b low-nibble arg is the 0x4a5e73 return value.",
        "ghidra_dump": "Called twice by 0x4a61bc. Static recovery shows a clamped connection-region pass around the provided x/y/level coordinate, object-reference-vector emptiness gating, bit26 writes through 0x49aa63(true), private low-bit flag packing in GeneratedCell+0x2c, and a follow-up projected target cell bit27 write through 0x49a932(true). Caller coordinate meanings are statically recovered from 0x4a61bc; runtime ordered replay remains pending.",
    },
    {
        "address": "0x4a746b",
        "name": "connection_endpoint_writer",
        "status": "recovered_static_contract_caller_offsets_replay_pending",
        "calls": ["0x4a5767", "0x4a5e73", "0x49aa63"],
        "reads": [
            "generator pointer in ecx",
            "coordinate triple args at stack+0x08/+0x0c/+0x10",
            "source/flag arg at stack+0x14",
            "generated-cell buffer/width/height at generator+0x14/+0x18/+0x1c",
            "generated-cell local word gate at +0x1c",
            "generated-cell projection triple at +0x10/+0x14/+0x18",
            "generated-cell owner/score dword at +0x20, including byte2 owner/relation index",
            "generated-cell bit-state dword at +0x28, including bit27",
            "generated-cell private flags at +0x2c",
            "stack-local five-entry endpoint offset table at ebp-0x48..ebp-0x20: (0,1), (1,0), (-1,0), (1,1), (-1,1)",
        ],
        "writes": [
            "calls 0x4a5767(generator) before endpoint selection",
            "derives the source generated cell from the input x/y/level coordinate triple",
            "returns false before endpoint helper work when the source cell +0x1c low word is >= 0x7530",
            "when the source cell +0x1c low word is positive, uses source cell +0x10/+0x14/+0x18 as the selected endpoint triple",
            "otherwise scans the five local endpoint offsets for a candidate cell whose +0x20 byte2 matches the source owner/relation index and whose +0x28 bit27 is set",
            "when no local endpoint offset matches, falls back to selected endpoint triple (x, y + 1, level)",
            "calls 0x4a5e73(generator, selected endpoint triple, true, arg4)",
            "when 0x4a5e73 returns nonnegative, stamps the same five local offset cells with 0x49aa63(true)",
            "for each stamped cell, writes cell+0x2c = (old & 0xffffffe1) | ((result & 0x0f) << 1) | 1",
            "returns true when 0x4a5e73 returns nonnegative and false otherwise",
        ],
        "caller_contract": "Both 0x4a7605 call sites are gated by control byte [arg2+0x09] and pass the newly allocated object record's relative coordinate triple at record+0x08/+0x0c/+0x10. The first call validates the allocated record against the original stack arg1, appends it to the generator+0x14c0/0x14d0 vector selected by local flag -0x14, records the coordinate in arg1+0x404, and calls 0x4a746b(generator, record+0x08 triple, relation record selected from generator+0x10e4 by arg2 index). The second call validates against that selected relation record, appends to the generator vector, records the coordinate in relation+0x404, and calls 0x4a746b(generator, record+0x08 triple, original stack arg1).",
        "ghidra_dump": "Called twice by 0x4a7605. Static recovery shows the normalize-first endpoint writer: it calls 0x4a5767, derives a source cell from the input coordinate, chooses an endpoint either from source projection fields, one of five local offset records with matching owner/bit27, or fallback (x,y+1,level), calls 0x4a5e73, and on success stamps the five endpoint-offset cells (0,1), (1,0), (-1,0), (1,1), and (-1,1) through 0x49aa63(true) plus GeneratedCell+0x2c low-bit packing. Caller coordinate meanings, local endpoint offsets, and the downstream 0x4a7312 selection policy are statically recovered; runtime ordered replay remains pending.",
    },
    {
        "address": "0x4a5e73",
        "name": "connection_endpoint_selection_helper",
        "status": "recovered_static_contract_replay_pending",
        "calls": ["0x5044b1", "0x49ba89", "0x4a7312"],
        "reads": [
            "generator pointer in ecx",
            "coordinate triple args at stack+0x08/+0x0c/+0x10",
            "repeat/count arg at stack+0x14",
            "mode/source arg passed to 0x4a7312 at stack+0x18",
            "current generator index at +0xf5c",
            "index-keyed pointer vector at generator+0xd8/+0xdc",
            "index-keyed pointer vector at generator+0xc8/+0xcc",
            "generated-cell buffer/width/height at generator+0x14/+0x18/+0x1c",
            "generated-cell private flags at +0x2c",
            "generated-cell bit-state word at +0x28",
            "generator byte-state vector at +0x1104/+0x1108",
        ],
        "writes": [
            "searches generator+0xd8/+0xdc for an entry whose dereferenced record +0x20 matches generator+0xf5c",
            "returns -1 when the +0xd8 vector has no matching entry",
            "searches generator+0xc8/+0xcc for an entry whose dereferenced record +0x20 matches generator+0xf5c",
            "returns 0 when the +0xd8 match exists but the +0xc8 vector has no matching entry",
            "allocates a 0x1c-byte object record and initializes it through 0x49ba89 using the +0xd8 matched entry",
            "calls 0x4a7312(generator, allocated record, arg5) and returns -1 after destroying the record when that helper rejects it",
            "when repeat/count arg is positive, allocates one 0x1c-byte object record per repeat and initializes it through 0x49ba89 using the +0xc8 matched entry",
            "for each repeated coordinate, clears low five bits of generated-cell +0x2c, then sets bit27 and clears bit26 in +0x28",
            "calls generator vtable slot +0x04 with the current coordinate triple and the per-repeat object record",
            "increments x for each repeat and decrements the repeat counter until exhausted",
            "marks generator+0x1104[original +0xf5c] = 1",
            "resets generator+0xf5c to zero and advances it while generator+0x1104[index] is nonzero within the +0x1104/+0x1108 byte-vector range",
            "returns the original generator+0xf5c index after successful validation/projection",
        ],
        "ghidra_dump": "Called by 0x4a61bc, 0x4a696b, 0x4a6cf2, and 0x4a746b. Static recovery shows an endpoint helper keyed by generator+0xf5c: it matches entries in generator+0xd8/+0xdc and +0xc8/+0xcc pointer vectors, validates an allocated +0xd8-derived object through 0x4a7312, optionally projects a repeated run of +0xc8-derived records across generated cells while forcing bit27 and clearing bit26, updates the byte-state vector at +0x1104/+0x1108, advances +0xf5c, and returns the original index or a failure sentinel. Exact vector-entry semantic names and runtime ordered replay remain pending.",
    },
    {
        "address": "0x4a7312",
        "name": "connection_endpoint_source_bounded_object_picker",
        "status": "recovered_static_contract_replay_pending",
        "calls": ["0x49aa93", "0x4ae1fd", "0x4e7276", "generator_vtable+0x04", "0x42c92d"],
        "reads": [
            "generator pointer in ecx",
            "object record arg at stack+0x08",
            "source/relation record arg at stack+0x0c",
            "object descriptor through object record+0x04",
            "descriptor dimensions at +0x34/+0x38",
            "source/relation coordinate triple at +0x10/+0x14/+0x18",
            "source/relation scan bounds at +0x20/+0x24/+0x28/+0x2c",
            "source/relation leading pointer chain used to derive the owner/relation id",
            "generated-cell buffer/width/height at generator+0x14/+0x18/+0x1c",
            "generated-cell owner/score word at +0x20, including byte2 owner/relation id",
        ],
        "writes": [
            "scans candidate x/y positions inside the source/relation bounds adjusted by descriptor width/height",
            "rejects candidates whose generated-cell +0x20 byte2 owner/relation id does not match the source/relation id",
            "calls 0x49aa93(generator, object descriptor/record, candidate coordinate triple, source/relation record) for matching-owner candidates",
            "appends accepted 12-byte coordinate triples into a local vector through 0x4ae1fd",
            "returns false when the accepted-coordinate vector is empty or its 12-byte record count is zero",
            "selects one accepted coordinate with 0x4e7276 % candidate_count",
            "calls generator vtable slot +0x04 with the selected coordinate triple and object record",
            "destroys the local coordinate vector through 0x42c92d before return",
        ],
        "returns": ["true after committing the selected object coordinate through generator vtable slot +0x04", "false when no eligible coordinate exists"],
        "ghidra_dump": "Focused dump .artifacts/rmg_recovery/ghidra_4a7312_policy_dump recovers the policy from assembly. Ghidra decompile still fails, so exact source/relation field names and runtime ordered replay remain pending.",
    },
]

STRUCTS: list[dict[str, Any]] = [
    {
        "name": "H3MapEdGenerator",
        "status": "must_recover_with_xrefs_and_runtime_dumps",
        "known_fields": {
            "+0x14": "generated_cell_buffer_begin",
            "+0x18": "map_width",
            "+0x1c": "map_height",
            "+0x20": "level_count",
            "+0xc8": "index-keyed pointer vector begin used by 0x4a5e73",
            "+0xcc": "index-keyed pointer vector end used by 0x4a5e73",
            "+0xd8": "index-keyed pointer vector begin used by 0x4a5e73",
            "+0xdc": "index-keyed pointer vector end used by 0x4a5e73",
            "+0xec4": "object record vector anchor observed by 0x4a54a7",
            "+0xecc": "object record vector insertion/end pointer observed by 0x4a54a7",
            "+0xed4": "optional handler pointer used by 0x49eb8d for invalid bit26 candidate cells; vtable slot +0x08 is called with the per-cell budget",
            "+0xf5c": "current endpoint/index cursor used and advanced by 0x4a5e73",
            "+0x10e4": "runtime_zone_relation_vector_begin",
            "+0x10e8": "runtime_zone_relation_vector_end",
            "+0x1104": "byte-state vector begin used by 0x4a5e73 to mark and advance index cursor",
            "+0x1108": "byte-state vector end used by 0x4a5e73",
            "+0x1110": "descriptor-type counter table indexed by descriptor+0x1c in 0x4a54a7",
            "+0x14b0": "strategic_route_coordinate_vector_begin",
            "+0x14b4": "strategic_route_coordinate_vector_end",
            "+0x14b8": "strategic_route_coordinate_vector_capacity",
        },
    },
    {
        "name": "GeneratedCell",
        "stride_bytes": 0x30,
        "status": "must_match_per_cell_at_checkpoints",
        "known_fields": {
            "+0x04": "object-reference dword vector begin pointer observed by 0x49e1bf",
            "+0x08": "object-reference dword vector end pointer observed by 0x49e1bf",
            "+0x10": "projection/local coordinate dword 0 written by 0x4a5767 and read by 0x4a606b",
            "+0x14": "projection/local coordinate dword 1 written by 0x4a5767 and read by 0x4a606b",
            "+0x18": "projection/local coordinate dword 2 written by 0x4a5767 and read by 0x4a606b",
            "+0x1c": "projection/local dword; 0x4a59e2 writes the high word and 0x4a5767 forces the low word before 0x4a746b thresholds it",
            "+0x20": "owner/score dword consumed by 0x4a4c8e byte2 owner; 0x4a59e2 writes byte3 while preserving the lower 24 bits",
            "+0x24": "terrain/art dword consumed by 0x4a4c8e and 0x49b2b6; 0x49acf6 writes terrain low six bits and an arg2 byte at bits 6..13",
            "+0x28": "generated-cell bit-state dword; 0x4a59e2 writes bits 12..14, 0x49acf6 writes bits 15..16, 0x49aa63/0x49a932 toggle bits 26/27",
            "+0x2b": "validity/private byte; bit 0x02 is required by 0x49a1d8 and tested by 0x49e1bf neighbor scans; bit 0x04 is cleared by 0x4a5a23 for nearby same-owner cells",
            "+0x2c": "cell private flags; bit0 skips 0x49a932/0x49aa63 helpers",
        },
    },
    {
        "name": "H3MapEdRelationRecord",
        "status": "observed_static_fields_replay_pending",
        "known_fields": {
            "+0x0c": "type/class value compared with 8 by 0x4a5767",
            "+0x10..+0x1b": "12-byte coordinate/range triple copied by 0x4a5767 before object-anchor projection",
            "+0x20..+0x2f": "four dword scan bounds copied by 0x4a5767 for relation-local generated-cell scans",
        },
    },
    {
        "name": "RouteCoordinateVector",
        "record_size_bytes": 8,
        "status": "recovered_static_helper_contract",
        "known_fields": {
            "+0x04": "begin pointer",
            "+0x08": "end pointer",
            "+0x0c": "capacity pointer",
        },
    },
    {
        "name": "Coord12CandidateVector",
        "record_size_bytes": 12,
        "status": "recovered_static_helper_contract",
        "known_fields": {
            "+0x04/+0x08/+0x0c": "begin/end/capacity pointer triad for 12-byte coordinate records; helper callers may pass the anchor or an interior anchor depending on wrapper layout",
            "+0x08": "end pointer read/written by 0x4ae1fd and 0x4ae52a when ecx is the vector anchor",
        },
    },
    {
        "name": "DwordVector",
        "record_size_bytes": 4,
        "status": "recovered_static_helper_contract",
        "known_fields": {
            "+0x04": "begin pointer",
            "+0x08": "end pointer",
            "+0x0c": "capacity pointer",
        },
    },
    {
        "name": "RewardGuardGridWrapper",
        "status": "recovered_static_fields_replay_pending",
        "known_fields": {
            "+0x08": "generated_cell_buffer",
            "+0x0c": "width",
            "+0x10": "height",
            "+0x18": "candidate_bounds_min_x",
            "+0x1c": "candidate_bounds_min_y",
            "+0x20": "candidate_bounds_max_x_exclusive",
            "+0x24": "candidate_bounds_max_y_exclusive",
            "+0x28": "selected_member_dword_vector_anchor; vector begin/end/capacity at +0x2c/+0x30/+0x34",
            "+0x38": "candidate_coordinate_vector_anchor; vector begin/end/capacity at +0x3c/+0x40/+0x44",
            "+0x48": "selected-member attached flag set by 0x49cf34 after successful candidate selection",
            "+0x4c": "selected_member_relative_x_after_0x49cf34",
            "+0x50": "selected_member_relative_y_after_0x49cf34",
            "+0x54..+0x5c": "selected coordinate triple written by 0x4aa3e9 before final wrapper projection",
        },
    },
    {
        "name": "H3MapEdObjectDescriptorMaskFields",
        "status": "recovered_static_fields_semantics_pending",
        "known_fields": {
            "+0x04": "48-bit object descriptor bitset tested by 0x41e951 with bit index 47 - 8*y - x",
            "+0x0c": "48-bit object descriptor bitset tested by 0x4268eb with bit index 47 - 8*y - x",
            "+0x34": "descriptor width used by placement, footprint, and contour helpers",
            "+0x38": "descriptor height used by placement, footprint, and contour helpers",
            "+0x3c": "48-bit object descriptor bitset tested by 0x41e915 with bit index 47 - 8*y - x",
        },
    },
    {
        "name": "H3MapEdObjectRecord",
        "status": "recovered_static_fields_replay_pending",
        "constructor": "0x49ba89",
        "known_fields": {
            "+0x00": "vtable pointer 0x540a74",
            "+0x04": "object descriptor pointer",
            "+0x08": "initialized to -1 by 0x49ba89; relative x coordinate in reward/guard selected-member wrapper passes",
            "+0x0c": "initialized to -1 by 0x49ba89; relative y coordinate in reward/guard selected-member wrapper passes",
            "+0x10": "initialized to -1 by 0x49ba89; relative level/z coordinate in reward/guard selected-member wrapper passes",
            "+0x18": "start of record-local dword table filled by 0x49b89c",
            "+0xe4": "cache-built byte checked and set by 0x49b89c",
        },
    },
    {
        "name": "ObjectDescriptorContourCacheRecord",
        "status": "recovered_static_fields_replay_pending",
        "producer": "0x49b76d",
        "known_fields": {
            "+0x00": "object descriptor pointer read by 0x49b76d",
            "+0x14": "8-byte coordinate/vector anchor populated by 0x49b76d",
            "+0x18": "vector begin pointer for the record+0x14 vector",
            "+0x1c": "vector end pointer for the record+0x14 vector",
            "+0x20": "vector capacity pointer inferred from the standard 8-byte vector anchor layout",
        },
    },
    {
        "name": "GeneratedCellObjectReference",
        "status": "recovered_static_field_offsets_semantics_pending",
        "known_fields": {
            "+0x04": "object record pointer passed to 0x49b89c and descriptor score-table reads",
            "+0x08": "x-like coordinate used by 0x49e1bf table lookup",
            "+0x0c": "y-like coordinate used by 0x49e1bf table lookup",
            "+0x14": "temporary neighbor flag set/cleared by 0x49e1bf",
            "+0x15": "temporary neighbor flag set/cleared by 0x49e1bf; paired with +0x14 for hard-conflict rejection",
            "+0x16": "temporary neighbor flag set/cleared by 0x49e1bf; applies descriptor +0x30 score table when record+0x10 is present",
            "+0x17": "temporary neighbor flag set/cleared by 0x49e1bf after 0x49b89c table comparison",
            "+0x18": "temporary neighbor flag set/cleared by 0x49e1bf; applies descriptor +0x40 score table or hard rejection when record+0x10 is absent",
        },
    },
    {
        "name": "RouteCoordinateListNode",
        "record_size_bytes": 16,
        "status": "recovered_static_helper_contract",
        "known_fields": {
            "+0x00": "prev pointer",
            "+0x04": "next pointer",
            "+0x08": "coord_x dword",
            "+0x0c": "coord_y dword",
        },
    },
]

CHECKPOINTS: list[dict[str, Any]] = [
    {"id": "after_terrain_live_feedback", "required_words": ["0x20", "0x24", "0x28", "0x2c"]},
    {"id": "after_town_castle", "required_words": ["0x20", "0x24", "0x28", "0x2c"]},
    {"id": "object_vector_entry", "required_words": ["0x20", "0x24", "0x28", "0x2c"]},
    {"id": "after_each_0x49a932_call", "required_words": ["0x28", "0x2c"], "requires_caller": True},
    {"id": "after_each_0x49aa63_call", "required_words": ["0x28", "0x2c"], "requires_caller": True},
    {"id": "after_object_vector_exit", "required_words": ["0x20", "0x24", "0x28", "0x2c"]},
    {"id": "pre_0x4a4c8e", "required_words": ["0x20", "0x24", "0x28", "0x2c"]},
]


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def objdump_probe(path: Path, addresses: list[str], context_bytes: int) -> dict[str, Any]:
    result: dict[str, Any] = {"status": "not_run", "functions": {}}
    try:
        completed = subprocess.run(
            ["objdump", "-Mintel", "-D", str(path)],
            check=False,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            timeout=90,
        )
    except Exception as exc:
        result["status"] = "failed"
        result["error"] = str(exc)
        return result
    result["status"] = "pass" if completed.returncode == 0 else "objdump_nonzero"
    text = completed.stdout
    lines = text.splitlines()
    for address in addresses:
        needle = address.lower().replace("0x", "").lstrip("0") or "0"
        found_index = -1
        for index, line in enumerate(lines):
            if line.strip().lower().startswith(needle + ":"):
                found_index = index
                break
        if found_index < 0:
            result["functions"][address] = {"status": "missing"}
            continue
        excerpt = lines[found_index : found_index + context_bytes]
        result["functions"][address] = {"status": "found", "disassembly_excerpt": excerpt}
    return result


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--h3maped-exe", type=Path, default=DEFAULT_H3MAPED)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--objdump-context-lines", type=int, default=32)
    return parser


def main() -> int:
    args = build_parser().parse_args()
    exe = args.h3maped_exe.resolve()
    if not exe.exists():
        raise SystemExit(f"missing h3maped.exe: {exe}")
    addresses = [str(record["address"]) for record in FUNCTIONS]
    manifest = {
        "schema_id": "h3maped_rmg_end_to_end_recovery_manifest_v1",
        "h3maped_exe": str(exe),
        "h3maped_sha256": sha256(exe),
        "recovery_policy": "no native behavior edits until trace replay matches H3MapEd private state",
        "functions": FUNCTIONS,
        "structs": STRUCTS,
        "checkpoints": CHECKPOINTS,
        "objdump_probe": objdump_probe(exe, addresses, args.objdump_context_lines),
    }
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"RMG_H3MAPED_RECOVERY_MANIFEST status=pass functions={len(FUNCTIONS)} out={args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
